import js from "@eslint/js";
import eslintPluginPrettier from "eslint-plugin-prettier/recommended";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    ignores: [
      "dist",
      ".output",
      ".vinxi",
      "src/routeTree.gen.ts",
      "src/integrations/supabase/types.ts",
      // Auto-generated by the platform's MCP Vite plugin (carry an
      // "AUTO-GENERATED … Regenerated by the Vite plugin" banner) and rewritten
      // on every build, so linting/formatting them is futile - CI lints after
      // build. Same treatment as the other generated files above.
      "src/routes/mcp.ts",
      "src/routes/**/list-tools.ts",
      "src/routes/**/invoke-tool/*.ts",
      "src/routes/**/oauth-protected-resource.ts",
      // Brokerowany magazyn sesji podglądu - plik nosi w pierwszej linii
      // "This file is automatically generated. Do not edit it directly." i
      // platforma NAPRAWDĘ go przepisuje. Dowód, a nie przypuszczenie: 30.08
      // jedna regeneracja skasowała DWIE niezależne poprawki `prefer-const`
      // (uchwyt `{ id? }` z #303 i deklarację przy przypisaniu z tej gałęzi)
      // i cofnęła cały plik do apostrofów oraz linii po 130 znaków. Skutek:
      // 23 błędy `prettier/prettier` w kroku `Lint` i czerwony `format:check`
      // - PIERWSZY krok joba, więc 36 kolejnych (typy, testy, build, bramki
      // artefaktu) nie startowało. Bramka blokowała wydania na treści, której
      // nikt w tym repo nie pisze i której żadna poprawka nie przeżywa.
      // KOSZT JEST JAWNY: defekty tego pliku nie są tu bramkowane. To ta sama
      // umowa, co dla `types.ts` i plików MCP wyżej.
      "src/integrations/supabase/previewAuthStorage.ts",
    ],
  },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "server-only",
              message:
                "TanStack Start does not use the Next.js `server-only` package. Rename the module to `*.server.ts` or mark it with `@tanstack/react-start/server-only`.",
            },
            {
              name: "isomorphic-dompurify",
              message:
                "isomorphic-dompurify crashes the Cloudflare Worker at module init (its browser build binds DOMPurify methods eagerly and there is no DOM in workerd) - every request then 500s. Use sanitizeHtml/sanitizeMarkdownHtml from @/lib/sanitize instead.",
            },
            {
              name: "i18n-iso-countries",
              message:
                "The bare package resolves to its Node entry in the SSR Worker build, which registers every locale via a dynamic require that Rollup cannot bundle - the Worker then 500s at module init. Import 'i18n-iso-countries/index.js' and register the needed langs explicitly.",
            },
          ],
        },
      ],
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
      "@typescript-eslint/no-unused-vars": "off",
      "@typescript-eslint/no-explicit-any": "error",
    },
  },
  {
    files: ["**/*.test.{ts,tsx}", "vitest.setup.ts", "vitest.config.ts"],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
    },
  },
  eslintPluginPrettier,
);
