// Curated emoji dataset for the chat picker - dependency-free and compact
// (~300 entries) so it ships in the lazy chat chunk without bloating the app.
// Keywords mix EN + PL so search works in both languages.
export interface EmojiEntry {
  /** The emoji itself. */
  e: string;
  /** Lowercase search keywords (EN + PL), space separated. */
  k: string;
}

export interface EmojiCategory {
  id: "smileys" | "gestures" | "hearts" | "animals" | "food" | "activities" | "travel" | "objects";
  emojis: ReadonlyArray<EmojiEntry>;
}

/** Messenger-style quick reaction bar. */
export const QUICK_REACTIONS: ReadonlyArray<string> = ["👍", "❤️", "😂", "😮", "😢", "🙏"];

export const EMOJI_CATEGORIES: ReadonlyArray<EmojiCategory> = [
  {
    id: "smileys",
    emojis: [
      { e: "😀", k: "grin smile usmiech" },
      { e: "😃", k: "smile happy wesoly" },
      { e: "😄", k: "laugh smile smiech" },
      { e: "😁", k: "beam grin usmiech" },
      { e: "😆", k: "laugh haha smiech" },
      { e: "😅", k: "sweat laugh pot smiech" },
      { e: "🤣", k: "rofl laugh smiech" },
      { e: "😂", k: "joy tears laugh lzy smiech" },
      { e: "🙂", k: "slight smile usmiech" },
      { e: "😉", k: "wink oczko" },
      { e: "😊", k: "blush smile rumieniec" },
      { e: "😇", k: "halo angel aniol" },
      { e: "🥰", k: "love hearts zakochany milosc" },
      { e: "😍", k: "heart eyes love zakochany" },
      { e: "🤩", k: "star struck gwiazdy wow" },
      { e: "😘", k: "kiss buziak calus" },
      { e: "😋", k: "yum tasty pyszne mniam" },
      { e: "😛", k: "tongue jezyk" },
      { e: "😜", k: "wink tongue jezyk oczko" },
      { e: "🤪", k: "zany crazy szalony" },
      { e: "🤨", k: "raised eyebrow sceptyczny" },
      { e: "🧐", k: "monocle badawczy" },
      { e: "🤓", k: "nerd okulary kujon" },
      { e: "😎", k: "cool sunglasses okulary luz" },
      { e: "🤗", k: "hug przytulas" },
      { e: "🤭", k: "giggle chichot ups" },
      { e: "🤫", k: "shush quiet cicho" },
      { e: "🤔", k: "think hmm myslec" },
      { e: "😐", k: "neutral obojetny" },
      { e: "😶", k: "no mouth cisza" },
      { e: "🙄", k: "eye roll przewracanie oczami" },
      { e: "😏", k: "smirk usmieszek" },
      { e: "😒", k: "unamused niezadowolony" },
      { e: "😬", k: "grimace zgrzyt" },
      { e: "😌", k: "relieved ulga spokoj" },
      { e: "😔", k: "pensive smutny zaduma" },
      { e: "😪", k: "sleepy spiacy" },
      { e: "😴", k: "sleep sen spanie" },
      { e: "😷", k: "mask maska chory" },
      { e: "🤒", k: "sick fever goraczka chory" },
      { e: "🤢", k: "nausea mdlosci" },
      { e: "🤧", k: "sneeze kichac przeziebienie" },
      { e: "🥵", k: "hot goraco upal" },
      { e: "🥶", k: "cold zimno mroz" },
      { e: "🤯", k: "mind blown eksplozja wow" },
      { e: "🥳", k: "party impreza urodziny" },
      { e: "😳", k: "flushed zawstydzony" },
      { e: "🥺", k: "pleading blagam prosze" },
      { e: "😢", k: "cry sad placz lza" },
      { e: "😭", k: "sob cry placz szloch" },
      { e: "😤", k: "triumph frustracja para" },
      { e: "😠", k: "angry zly gniew" },
      { e: "😡", k: "rage furia wsciekly" },
      { e: "🤬", k: "cursing przeklenstwa" },
      { e: "😨", k: "fear strach" },
      { e: "😰", k: "anxious niepokoj" },
      { e: "😱", k: "scream krzyk przerazenie" },
      { e: "😮", k: "wow open mouth zdziwienie" },
      { e: "😲", k: "astonished zdumiony" },
      { e: "🥱", k: "yawn ziewanie nuda" },
      { e: "😵", k: "dizzy oszolomiony" },
      { e: "🤠", k: "cowboy kowboj" },
      { e: "🤑", k: "money pieniadze" },
      { e: "😈", k: "devil diabel psotny" },
      { e: "👻", k: "ghost duch" },
      { e: "💀", k: "skull czaszka" },
      { e: "🤖", k: "robot" },
      { e: "👽", k: "alien kosmita ufo" },
      { e: "🎃", k: "pumpkin halloween dynia" },
      { e: "😺", k: "cat smile kot" },
      { e: "🙈", k: "monkey see no evil malpa nie patrze" },
      { e: "🙉", k: "monkey hear no evil malpa nie slysze" },
      { e: "🙊", k: "monkey speak no evil malpa nie mowie" },
    ],
  },
  {
    id: "gestures",
    emojis: [
      { e: "👍", k: "thumbs up ok dobrze kciuk" },
      { e: "👎", k: "thumbs down zle kciuk" },
      { e: "👌", k: "ok perfect okej" },
      { e: "🤌", k: "pinched fingers wlosko" },
      { e: "✌️", k: "victory peace zwyciestwo" },
      { e: "🤞", k: "crossed fingers szczescie trzymam kciuki" },
      { e: "🤟", k: "love you kocham cie" },
      { e: "🤘", k: "rock metal" },
      { e: "🤙", k: "call me zadzwon" },
      { e: "👈", k: "point left wskazuje lewo" },
      { e: "👉", k: "point right wskazuje prawo" },
      { e: "👆", k: "point up gora" },
      { e: "👇", k: "point down dol" },
      { e: "☝️", k: "index up uwaga" },
      { e: "✋", k: "hand stop reka" },
      { e: "🖐️", k: "hand splayed dlon" },
      { e: "🖖", k: "vulcan spock" },
      { e: "👋", k: "wave hello czesc pa" },
      { e: "🤚", k: "raised back hand reka" },
      { e: "💪", k: "muscle strong sila biceps" },
      { e: "🙏", k: "pray thanks dziekuje prosze modlitwa" },
      { e: "🤝", k: "handshake deal umowa" },
      { e: "👏", k: "clap brawo oklaski" },
      { e: "🙌", k: "raised hands hurra" },
      { e: "👐", k: "open hands otwarte dlonie" },
      { e: "🤲", k: "palms up prosba" },
      { e: "✊", k: "fist piesc" },
      { e: "👊", k: "fist bump zolwik" },
      { e: "🫶", k: "heart hands serce dlonie" },
      { e: "✍️", k: "writing pisanie" },
      { e: "💅", k: "nails paznokcie" },
      { e: "🤳", k: "selfie" },
      { e: "👀", k: "eyes oczy patrze" },
      { e: "🧠", k: "brain mozg" },
      { e: "🗣️", k: "speaking mowa" },
      { e: "👤", k: "person osoba" },
      { e: "👥", k: "people ludzie" },
      { e: "🚶", k: "walk spacer" },
      { e: "🏃", k: "run bieg" },
      { e: "💃", k: "dance taniec" },
      { e: "🕺", k: "dance taniec" },
    ],
  },
  {
    id: "hearts",
    emojis: [
      { e: "❤️", k: "heart love serce milosc" },
      { e: "🧡", k: "orange heart pomaranczowe serce" },
      { e: "💛", k: "yellow heart zolte serce" },
      { e: "💚", k: "green heart zielone serce" },
      { e: "💙", k: "blue heart niebieskie serce" },
      { e: "💜", k: "purple heart fioletowe serce" },
      { e: "🖤", k: "black heart czarne serce" },
      { e: "🤍", k: "white heart biale serce" },
      { e: "🤎", k: "brown heart brazowe serce" },
      { e: "💔", k: "broken heart zlamane serce" },
      { e: "❣️", k: "heart exclamation serce wykrzyknik" },
      { e: "💕", k: "two hearts dwa serca" },
      { e: "💞", k: "revolving hearts wirujace serca" },
      { e: "💓", k: "beating heart bijace serce" },
      { e: "💗", k: "growing heart rosnace serce" },
      { e: "💖", k: "sparkling heart blyszczace serce" },
      { e: "💘", k: "cupid strzala amora" },
      { e: "💝", k: "heart gift prezent serce" },
      { e: "💯", k: "hundred sto procent" },
      { e: "💢", k: "anger gniew" },
      { e: "💥", k: "boom collision wybuch" },
      { e: "💫", k: "dizzy star gwiazdka" },
      { e: "💦", k: "sweat drops krople" },
      { e: "💨", k: "dash wind pospiech" },
      { e: "🕳️", k: "hole dziura" },
      { e: "💬", k: "speech bubble dymek wiadomosc" },
      { e: "💭", k: "thought bubble mysl" },
      { e: "💤", k: "zzz sen spanie" },
      { e: "✨", k: "sparkles blysk magia" },
      { e: "⭐", k: "star gwiazda" },
      { e: "🌟", k: "glowing star gwiazda" },
      { e: "🔥", k: "fire ogien hot" },
      { e: "🎉", k: "party tada konfetti impreza" },
      { e: "🎊", k: "confetti konfetti" },
      { e: "🎈", k: "balloon balon" },
      { e: "🎁", k: "gift prezent" },
      { e: "🏆", k: "trophy puchar zwyciestwo" },
      { e: "🥇", k: "gold medal zloto" },
      { e: "✅", k: "check done zrobione ok" },
      { e: "❌", k: "cross x nie blad" },
      { e: "❓", k: "question pytanie" },
      { e: "❗", k: "exclamation wykrzyknik" },
      { e: "⚠️", k: "warning ostrzezenie uwaga" },
      { e: "♻️", k: "recycle recykling" },
      { e: "🔔", k: "bell dzwonek powiadomienie" },
      { e: "🎵", k: "music note nuta muzyka" },
      { e: "🎶", k: "music notes nuty muzyka" },
    ],
  },
  {
    id: "animals",
    emojis: [
      { e: "🐶", k: "dog pies piesek" },
      { e: "🐱", k: "cat kot kotek" },
      { e: "🐭", k: "mouse mysz" },
      { e: "🐹", k: "hamster chomik" },
      { e: "🐰", k: "rabbit krolik" },
      { e: "🦊", k: "fox lis" },
      { e: "🐻", k: "bear miedzwiedz mis" },
      { e: "🐼", k: "panda" },
      { e: "🐨", k: "koala" },
      { e: "🐯", k: "tiger tygrys" },
      { e: "🦁", k: "lion lew" },
      { e: "🐮", k: "cow krowa" },
      { e: "🐷", k: "pig swinia" },
      { e: "🐸", k: "frog zaba" },
      { e: "🐵", k: "monkey malpa" },
      { e: "🐔", k: "chicken kura" },
      { e: "🐧", k: "penguin pingwin" },
      { e: "🐦", k: "bird ptak" },
      { e: "🦅", k: "eagle orzel" },
      { e: "🦉", k: "owl sowa" },
      { e: "🐴", k: "horse kon" },
      { e: "🦄", k: "unicorn jednorozec" },
      { e: "🐝", k: "bee pszczola" },
      { e: "🦋", k: "butterfly motyl" },
      { e: "🐌", k: "snail slimak" },
      { e: "🐢", k: "turtle zolw" },
      { e: "🐍", k: "snake waz" },
      { e: "🐙", k: "octopus osmiornica" },
      { e: "🦀", k: "crab krab" },
      { e: "🐬", k: "dolphin delfin" },
      { e: "🐳", k: "whale wieloryb" },
      { e: "🦈", k: "shark rekin" },
      { e: "🐺", k: "wolf wilk" },
      { e: "🦒", k: "giraffe zyrafa" },
      { e: "🐘", k: "elephant slon" },
      { e: "🌸", k: "blossom kwiat wisnia" },
      { e: "🌹", k: "rose roza" },
      { e: "🌻", k: "sunflower slonecznik" },
      { e: "🌳", k: "tree drzewo" },
      { e: "🍀", k: "clover koniczyna szczescie" },
      { e: "🌍", k: "earth europe ziemia europa" },
      { e: "🌙", k: "moon ksiezyc" },
      { e: "☀️", k: "sun slonce" },
      { e: "🌈", k: "rainbow tecza" },
      { e: "⛅", k: "cloud sun chmura slonce" },
      { e: "🌧️", k: "rain deszcz" },
      { e: "⛈️", k: "storm burza" },
      { e: "❄️", k: "snow snieg platek" },
      { e: "🌊", k: "wave fala morze" },
    ],
  },
  {
    id: "food",
    emojis: [
      { e: "🍏", k: "apple green jablko" },
      { e: "🍎", k: "apple red jablko" },
      { e: "🍐", k: "pear gruszka" },
      { e: "🍊", k: "orange pomarancza" },
      { e: "🍋", k: "lemon cytryna" },
      { e: "🍌", k: "banana banan" },
      { e: "🍉", k: "watermelon arbuz" },
      { e: "🍇", k: "grapes winogrona" },
      { e: "🍓", k: "strawberry truskawka" },
      { e: "🍒", k: "cherry wisnia czeresnia" },
      { e: "🍑", k: "peach brzoskwinia" },
      { e: "🥭", k: "mango" },
      { e: "🍍", k: "pineapple ananas" },
      { e: "🥑", k: "avocado awokado" },
      { e: "🍅", k: "tomato pomidor" },
      { e: "🥕", k: "carrot marchewka" },
      { e: "🌽", k: "corn kukurydza" },
      { e: "🥐", k: "croissant rogalik" },
      { e: "🍞", k: "bread chleb" },
      { e: "🥨", k: "pretzel precel" },
      { e: "🧀", k: "cheese ser" },
      { e: "🥚", k: "egg jajko" },
      { e: "🍳", k: "cooking jajko sadzone" },
      { e: "🥞", k: "pancakes nalesniki" },
      { e: "🍕", k: "pizza" },
      { e: "🍔", k: "burger hamburger" },
      { e: "🍟", k: "fries frytki" },
      { e: "🌭", k: "hot dog hotdog parowka" },
      { e: "🥪", k: "sandwich kanapka" },
      { e: "🌮", k: "taco" },
      { e: "🍝", k: "spaghetti makaron" },
      { e: "🍜", k: "ramen zupa" },
      { e: "🍣", k: "sushi" },
      { e: "🍦", k: "ice cream lody" },
      { e: "🍩", k: "donut paczek" },
      { e: "🍪", k: "cookie ciastko" },
      { e: "🎂", k: "cake tort urodziny" },
      { e: "🍰", k: "cake ciasto" },
      { e: "🍫", k: "chocolate czekolada" },
      { e: "🍿", k: "popcorn" },
      { e: "☕", k: "coffee kawa" },
      { e: "🍵", k: "tea herbata" },
      { e: "🥤", k: "cup drink napoj" },
      { e: "🍺", k: "beer piwo" },
      { e: "🍷", k: "wine wino" },
      { e: "🥂", k: "cheers toast szampan" },
      { e: "🍾", k: "champagne szampan" },
    ],
  },
  {
    id: "activities",
    emojis: [
      { e: "⚽", k: "soccer football pilka nozna" },
      { e: "🏀", k: "basketball koszykowka" },
      { e: "🏈", k: "american football futbol" },
      { e: "⚾", k: "baseball" },
      { e: "🎾", k: "tennis tenis" },
      { e: "🏐", k: "volleyball siatkowka" },
      { e: "🏉", k: "rugby" },
      { e: "🎱", k: "billiards bilard" },
      { e: "🏓", k: "ping pong tenis stolowy" },
      { e: "🏸", k: "badminton" },
      { e: "🥅", k: "goal bramka" },
      { e: "⛳", k: "golf" },
      { e: "🎣", k: "fishing wedkarstwo" },
      { e: "🥊", k: "boxing boks" },
      { e: "🎽", k: "running bieganie" },
      { e: "🛹", k: "skateboard deskorolka" },
      { e: "⛸️", k: "ice skate lyzwy" },
      { e: "🎿", k: "ski narty" },
      { e: "🏂", k: "snowboard" },
      { e: "🚴", k: "cycling rower" },
      { e: "🏊", k: "swimming plywanie" },
      { e: "🧘", k: "yoga joga medytacja" },
      { e: "🎯", k: "target dart cel" },
      { e: "🎮", k: "game controller gry pad" },
      { e: "🕹️", k: "joystick gry" },
      { e: "🎲", k: "dice kostka" },
      { e: "♟️", k: "chess szachy" },
      { e: "🧩", k: "puzzle" },
      { e: "🎳", k: "bowling kregle" },
      { e: "🎤", k: "microphone mikrofon karaoke" },
      { e: "🎧", k: "headphones sluchawki" },
      { e: "🎸", k: "guitar gitara" },
      { e: "🎹", k: "piano pianino" },
      { e: "🥁", k: "drums perkusja" },
      { e: "🎺", k: "trumpet trabka" },
      { e: "🎻", k: "violin skrzypce" },
      { e: "🎬", k: "clapper film kino" },
      { e: "🎨", k: "art palette sztuka malarstwo" },
      { e: "🎭", k: "theater teatr maski" },
      { e: "📚", k: "books ksiazki" },
      { e: "🎓", k: "graduation studia dyplom" },
    ],
  },
  {
    id: "travel",
    emojis: [
      { e: "🚗", k: "car auto samochod" },
      { e: "🚕", k: "taxi taksowka" },
      { e: "🚙", k: "suv auto" },
      { e: "🚌", k: "bus autobus" },
      { e: "🚎", k: "trolleybus trolejbus" },
      { e: "🚓", k: "police policja" },
      { e: "🚑", k: "ambulance karetka" },
      { e: "🚒", k: "fire truck straz" },
      { e: "🚚", k: "truck ciezarowka" },
      { e: "🚜", k: "tractor traktor" },
      { e: "🏍️", k: "motorcycle motocykl" },
      { e: "🚲", k: "bicycle rower" },
      { e: "🛴", k: "scooter hulajnoga" },
      { e: "🚂", k: "train pociag lokomotywa" },
      { e: "🚆", k: "train pociag" },
      { e: "🚇", k: "metro" },
      { e: "🚊", k: "tram tramwaj" },
      { e: "✈️", k: "airplane samolot" },
      { e: "🛫", k: "departure odlot" },
      { e: "🛬", k: "arrival przylot" },
      { e: "🚁", k: "helicopter helikopter" },
      { e: "🚀", k: "rocket rakieta start" },
      { e: "🛸", k: "ufo" },
      { e: "⛵", k: "sailboat zaglowka" },
      { e: "🚢", k: "ship statek" },
      { e: "⚓", k: "anchor kotwica" },
      { e: "🗺️", k: "map mapa" },
      { e: "🧭", k: "compass kompas" },
      { e: "🏔️", k: "mountain gory" },
      { e: "🏕️", k: "camping biwak" },
      { e: "🏖️", k: "beach plaza" },
      { e: "🏙️", k: "city miasto" },
      { e: "🏰", k: "castle zamek" },
      { e: "🗽", k: "statue liberty statua wolnosci" },
      { e: "🗼", k: "tower wieza" },
      { e: "⛪", k: "church kosciol" },
      { e: "🕌", k: "mosque meczet" },
      { e: "🏛️", k: "classical building muzeum" },
      { e: "🏠", k: "house dom" },
      { e: "🏢", k: "office biuro" },
      { e: "🏨", k: "hotel" },
      { e: "🏥", k: "hospital szpital" },
      { e: "🇪🇺", k: "eu europe flaga europa unia" },
      { e: "🇵🇱", k: "poland polska flaga" },
    ],
  },
  {
    id: "objects",
    emojis: [
      { e: "⌚", k: "watch zegarek" },
      { e: "📱", k: "phone telefon smartfon" },
      { e: "💻", k: "laptop komputer" },
      { e: "🖥️", k: "desktop komputer monitor" },
      { e: "🖨️", k: "printer drukarka" },
      { e: "⌨️", k: "keyboard klawiatura" },
      { e: "🖱️", k: "mouse myszka" },
      { e: "📷", k: "camera aparat" },
      { e: "🎥", k: "video camera kamera" },
      { e: "📞", k: "phone telefon sluchawka" },
      { e: "📺", k: "tv telewizor" },
      { e: "📻", k: "radio" },
      { e: "🎙️", k: "studio microphone mikrofon podcast" },
      { e: "⏰", k: "alarm budzik" },
      { e: "⏳", k: "hourglass klepsydra czas" },
      { e: "🔋", k: "battery bateria" },
      { e: "🔌", k: "plug wtyczka" },
      { e: "💡", k: "bulb idea pomysl zarowka" },
      { e: "🔦", k: "flashlight latarka" },
      { e: "🕯️", k: "candle swieca" },
      { e: "💸", k: "money flying pieniadze" },
      { e: "💰", k: "money bag worek pieniedzy" },
      { e: "💳", k: "credit card karta" },
      { e: "💎", k: "diamond diament" },
      { e: "🧰", k: "toolbox narzedzia" },
      { e: "🔧", k: "wrench klucz" },
      { e: "🔨", k: "hammer mlotek" },
      { e: "🧲", k: "magnet magnes" },
      { e: "🔬", k: "microscope mikroskop" },
      { e: "🔭", k: "telescope teleskop" },
      { e: "💊", k: "pill tabletka" },
      { e: "🧬", k: "dna" },
      { e: "🛒", k: "cart koszyk zakupy" },
      { e: "🚪", k: "door drzwi" },
      { e: "🛋️", k: "couch kanapa" },
      { e: "🛏️", k: "bed lozko" },
      { e: "🧸", k: "teddy bear mis pluszak" },
      { e: "🖼️", k: "picture obraz" },
      { e: "📦", k: "package paczka" },
      { e: "✉️", k: "envelope koperta list" },
      { e: "📧", k: "email mail" },
      { e: "📝", k: "memo notatka" },
      { e: "📌", k: "pin pinezka" },
      { e: "📎", k: "paperclip spinacz" },
      { e: "✂️", k: "scissors nozyczki" },
      { e: "🔒", k: "lock klodka zamkniete" },
      { e: "🔑", k: "key klucz" },
      { e: "📅", k: "calendar kalendarz" },
      { e: "📊", k: "chart wykres" },
      { e: "📈", k: "chart up wzrost" },
      { e: "📰", k: "newspaper gazeta wiadomosci" },
    ],
  },
];

/** Search across every category by emoji keywords (EN + PL). */
export function searchEmoji(query: string, limit = 48): EmojiEntry[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const hits: EmojiEntry[] = [];
  for (const category of EMOJI_CATEGORIES) {
    for (const entry of category.emojis) {
      if (entry.k.includes(q)) {
        hits.push(entry);
        if (hits.length >= limit) return hits;
      }
    }
  }
  return hits;
}

const EMOJI_ONLY_PATTERN =
  /^(?:\p{Extended_Pictographic}(?:️|‍\p{Extended_Pictographic})*|\s){1,12}$/u;

/** True when a message consists of emoji only (rendered enlarged, Messenger-style). */
export function isEmojiOnly(text: string): boolean {
  const trimmed = text.trim();
  if (!trimmed) return false;
  return EMOJI_ONLY_PATTERN.test(trimmed);
}
