// Rejestr bloków block editora. MVP: 5 bloków core.
// Pozostałe 10 wpisuje się analogicznie w kolejnych etapach.

import type { Block, BlockType } from "./types";
import { newBlockId } from "./types";
import {
  Type,
  Heading1 as HeadingIcon,
  Image as ImageIcon,
  List as ListIcon,
  Quote as QuoteIcon,
  Code2 as CodeIcon,
  Video as VideoIcon,
  Minus,
  AlertTriangle as AlertCircle,
  Table2 as TableIcon,
  MousePointerClick as MousePointer2,
  Columns2 as ColumnsIcon,
  FileCode2 as FileCode,
  PlaySquare,
  Images,
  Radio as RadioIcon,
  Star as StarIcon,
  ThumbsUp as ProsConsIcon,
  EyeOff as SpoilerIcon,
  HelpCircle as FaqIcon,
  ListTree as TocIcon,
  Mail as MailIcon,
  ShoppingBag as AffiliateIcon,
  Twitter as XIcon,
  GitCompareArrows as CompareIcon,
  type LucideIcon,
} from "lucide-react";

export interface BlockSpec {
  type: BlockType;
  label: string;
  description: string;
  icon: LucideIcon;
  category: "text" | "media" | "layout" | "advanced";
  /** Tworzy domyślną instancję bloku. */
  create: () => Block;
}

export const BLOCK_SPECS: Record<BlockType, BlockSpec> = {
  paragraph: {
    type: "paragraph",
    label: "Akapit",
    description: "Tekst z formatowaniem inline.",
    icon: Type,
    category: "text",
    create: () => ({ id: newBlockId(), type: "paragraph", data: { html: "" } }),
  },
  heading: {
    type: "heading",
    label: "Nagłówek",
    description: "H2, H3 lub H4 z opcjonalnym anchorem.",
    icon: HeadingIcon,
    category: "text",
    create: () => ({ id: newBlockId(), type: "heading", data: { level: 2, text: "", anchor: "" } }),
  },
  image: {
    type: "image",
    label: "Obraz",
    description: "Pojedynczy obraz z podpisem.",
    icon: ImageIcon,
    category: "media",
    create: () => ({ id: newBlockId(), type: "image", data: { url: "", alt: "", caption: "", href: "" } }),
  },
  list: {
    type: "list",
    label: "Lista",
    description: "Lista numerowana lub punktowana.",
    icon: ListIcon,
    category: "text",
    create: () => ({ id: newBlockId(), type: "list", data: { ordered: false, items: [""] } }),
  },
  quote: {
    type: "quote",
    label: "Cytat",
    description: "Wyróżniony cytat z opcjonalnym autorem.",
    icon: QuoteIcon,
    category: "text",
    create: () => ({ id: newBlockId(), type: "quote", data: { text: "", cite: "" } }),
  },
  // Stuby — pełne implementacje w kolejnym etapie. Tworzenie blokuje fallback.
  code: {
    type: "code",
    label: "Kod",
    description: "Blok kodu z podświetlaniem.",
    icon: CodeIcon,
    category: "advanced",
    create: () => ({ id: newBlockId(), type: "code", data: { lang: "ts", code: "" } }),
  },
  embed: {
    type: "embed",
    label: "Embed",
    description: "YouTube, Vimeo, X — z URL.",
    icon: PlaySquare,
    category: "media",
    create: () => ({ id: newBlockId(), type: "embed", data: { url: "" } }),
  },
  video: {
    type: "video",
    label: "Wideo",
    description: "Plik wideo lub URL.",
    icon: VideoIcon,
    category: "media",
    create: () => ({ id: newBlockId(), type: "video", data: { url: "", poster: "" } }),
  },
  gallery: {
    type: "gallery",
    label: "Galeria",
    description: "Siatka obrazów.",
    icon: Images,
    category: "media",
    create: () => ({ id: newBlockId(), type: "gallery", data: { images: [] } }),
  },
  separator: {
    type: "separator",
    label: "Separator",
    description: "Linia rozdzielająca.",
    icon: Minus,
    category: "layout",
    create: () => ({ id: newBlockId(), type: "separator", data: { variant: "line" } }),
  },
  callout: {
    type: "callout",
    label: "Callout",
    description: "Info / warning / success / danger.",
    icon: AlertCircle,
    category: "text",
    create: () => ({ id: newBlockId(), type: "callout", data: { variant: "info", text: "" } }),
  },
  table: {
    type: "table",
    label: "Tabela",
    description: "Wiersze i kolumny.",
    icon: TableIcon,
    category: "advanced",
    create: () => ({ id: newBlockId(), type: "table", data: { rows: [[""]], header: false } }),
  },
  button: {
    type: "button",
    label: "Przycisk",
    description: "Etykieta + link.",
    icon: MousePointer2,
    category: "layout",
    create: () => ({ id: newBlockId(), type: "button", data: { label: "Kliknij", href: "#", variant: "default" } }),
  },
  columns: {
    type: "columns",
    label: "Kolumny",
    description: "Dwie kolumny z blokami.",
    icon: ColumnsIcon,
    category: "layout",
    create: () => ({ id: newBlockId(), type: "columns", data: { left: [], right: [] } }),
  },
  html: {
    type: "html",
    label: "HTML",
    description: "Surowy HTML (sanitizowany).",
    icon: FileCode,
    category: "advanced",
    create: () => ({ id: newBlockId(), type: "html", data: { html: "" } }),
  },
  liveblog: {
    type: "liveblog",
    label: "Live Blog",
    description: "Wpisy na żywo z auto-odświeżaniem (timestamped).",
    icon: RadioIcon,
    category: "advanced",
    create: () => ({
      id: newBlockId(),
      type: "liveblog",
      data: { title: "", reverseChronological: true, autoRefresh: true },
    }),
  },
  review: {
    type: "review",
    label: "Recenzja (Review Box)",
    description: "Ocena z paskami kryteriów + CTA (Foxiz-style).",
    icon: StarIcon,
    category: "advanced",
    create: () => ({
      id: newBlockId(),
      type: "review",
      data: {
        title: "",
        summary: "",
        criteria: [
          { label: "", score: 8 },
          { label: "", score: 8 },
        ],
        ctaLabel: "",
        ctaHref: "",
        scale: 10,
      },
    }),
  },
  proscons: {
    type: "proscons",
    label: "Plusy i minusy",
    description: "Dwie kolumny: zalety i wady.",
    icon: ProsConsIcon,
    category: "advanced",
    create: () => ({
      id: newBlockId(),
      type: "proscons",
      data: {
        title: "",
        pros: [""],
        cons: [""],
      },
    }),
  },
  spoiler: {
    type: "spoiler",
    label: "Spoiler / Rozwijany",
    description: "Ukryty blok, otwierany po kliknięciu.",
    icon: SpoilerIcon,
    category: "advanced",
    create: () => ({
      id: newBlockId(),
      type: "spoiler",
      data: { summary: "", html: "", defaultOpen: false },
    }),
  },
  faq: {
    type: "faq",
    label: "FAQ",
    description: "Lista pytań i odpowiedzi (schema.org FAQPage).",
    icon: FaqIcon,
    category: "advanced",
    create: () => ({
      id: newBlockId(),
      type: "faq",
      data: {
        title: "",
        items: [
          { q: "", a: "" },
        ],
      },
    }),
  },
  toc: {
    type: "toc",
    label: "Spis treści",
    description: "Auto-generowany z nagłówków H2/H3.",
    icon: TocIcon,
    category: "advanced",
    create: () => ({
      id: newBlockId(),
      type: "toc",
      data: { title: "", maxLevel: 3, ordered: false, sticky: false },
    }),
  },
  newsletter: {
    type: "newsletter",
    label: "Newsletter (inline)",
    description: "Formularz zapisu osadzony w treści wpisu.",
    icon: MailIcon,
    category: "advanced",
    create: () => ({
      id: newBlockId(),
      type: "newsletter",
      data: { title: "", description: "", variant: "card" },
    }),
  },
  affiliate: {
    type: "affiliate",
    label: "Produkt afiliacyjny",
    description: "Karta produktu z ceną, sklepem i CTA.",
    icon: AffiliateIcon,
    category: "advanced",
    create: () => ({
      id: newBlockId(),
      type: "affiliate",
      data: {
        title: "",
        description: "",
        image: "",
        price: "",
        currency: "PLN",
        store: "",
        ctaLabel: "",
        ctaHref: "",
        rating: 0,
        sponsored: true,
      },
    }),
  },
  xquote: {
    type: "xquote",
    label: "X Quote (Click-to-Tweet)",
    description: "Wyróżniony cytat w stylu X/Twittera z udostępnianiem.",
    icon: XIcon,
    category: "advanced",
    create: () => ({
      id: newBlockId(),
      type: "xquote",
      data: { text: "", via: "", hashtags: "" },
    }),
  },
  compare: {
    type: "compare",
    label: "Before / After",
    description: "Slider porównujący dwa obrazy.",
    icon: CompareIcon,
    category: "advanced",
    create: () => ({
      id: newBlockId(),
      type: "compare",
      data: {
        before: "",
        after: "",
        labelBefore: "Przed",
        labelAfter: "Po",
      },
    }),
  },
};

export const BLOCK_LIST: BlockSpec[] = Object.values(BLOCK_SPECS);

/** Bloki, które mają już dedykowany edytor i renderer. */
export const IMPLEMENTED_BLOCKS: BlockType[] = [
  "paragraph",
  "heading",
  "image",
  "list",
  "quote",
  "code",
  "embed",
  "video",
  "gallery",
  "separator",
  "callout",
  "table",
  "button",
  "columns",
  "html",
  "liveblog",
  "review",
  "proscons",
  "spoiler",
  "faq",
  "toc",
  "newsletter",
  "affiliate",
  "xquote",
  "compare",
];
