// Rejestr bloków block editora. MVP: 5 bloków core.
// Pozostałe 10 wpisuje się analogicznie w kolejnych etapach.

import type { Block, BlockType } from "./types";
import { newBlockId } from "./types";
import {
  Type,
  Heading1 as HeadingIcon,
  Image as ImageIcon,
  List as ListIcon,
  Quote as QuoteIcon,
  Code2 as CodeIcon,
  Video as VideoIcon,
  Minus,
  AlertTriangle as AlertCircle,
  Table2 as TableIcon,
  MousePointerClick as MousePointer2,
  Columns2 as ColumnsIcon,
  FileCode2 as FileCode,
  PlaySquare,
  Images,
  Radio as RadioIcon,
  Star as StarIcon,
  ThumbsUp as ProsConsIcon,
  EyeOff as SpoilerIcon,
  HelpCircle as FaqIcon,
  ListTree as TocIcon,
  Mail as MailIcon,
  ShoppingBag as AffiliateIcon,
  Twitter as XIcon,
  GitCompareArrows as CompareIcon,
  LogIn as LoginIcon,
  UserPlus as RegisterIcon,
  KeyRound as LostPasswordIcon,
  ShieldCheck as ResetPasswordIcon,
  Music as AudioIcon,
  ImagePlus as CoverIcon,
  FileDown as FileIcon,
  PanelsTopLeft as MediaTextIcon,
  Square as GroupIcon,
  MoveVertical as SpacerIcon,
  SeparatorHorizontal as PageBreakIcon,
  MoreHorizontal as MoreIcon,
  Quote as PullquoteIcon,
  AlignLeft as PreformattedIcon,
  Feather as VerseIcon,
  ChevronDownSquare as DetailsIcon,
  Rows3 as RowIcon,
  StretchVertical as StackIcon,
  LayoutGrid as GridIcon,
  MousePointer as ButtonsIcon,
  Share2 as SocialIcon,
  Search as SearchIcon,
  Newspaper as LatestPostsIcon,
  Tags as TagCloudIcon,
  FolderTree as CategoriesIcon,
  Archive as ArchivesIcon,
  CalendarDays as CalendarIcon,
  Heading2 as PostTitleIcon,
  Clock as PostDateIcon,
  User as PostAuthorIcon,
  AlignJustify as PostExcerptIcon,
  Camera as PostFeaturedIcon,
  Hash as PostTermsIcon,
  Globe as SiteTitleIcon,
  Megaphone as SiteTaglineIcon,
  Building2 as SiteLogoIcon,
  Menu as NavigationIcon,
  ArrowLeftRight as PostNavIcon,
  Repeat as QueryLoopIcon,
  Home as BreadcrumbsIcon,
  Timer as ReadingTimeIcon,
  Share2 as ShareIcon,
  Eye as ViewsIcon,
  UserCircle2 as AuthorBioIcon,
  Sparkles as RelatedIcon,
  type LucideIcon,
} from "lucide-react";

export interface BlockSpec {
  type: BlockType;
  label: string;
  description: string;
  icon: LucideIcon;
  category: "text" | "media" | "layout" | "advanced";
  /** Tworzy domyślną instancję bloku. */
  create: () => Block;
}

export const BLOCK_SPECS: Record<BlockType, BlockSpec> = {
  paragraph: {
    type: "paragraph",
    label: "Akapit",
    description: "Tekst z formatowaniem inline.",
    icon: Type,
    category: "text",
    create: () => ({ id: newBlockId(), type: "paragraph", data: { html: "" } }),
  },
  heading: {
    type: "heading",
    label: "Nagłówek",
    description: "H2, H3 lub H4 z opcjonalnym anchorem.",
    icon: HeadingIcon,
    category: "text",
    create: () => ({ id: newBlockId(), type: "heading", data: { level: 2, text: "", anchor: "" } }),
  },
  image: {
    type: "image",
    label: "Obraz",
    description: "Pojedynczy obraz z podpisem.",
    icon: ImageIcon,
    category: "media",
    create: () => ({ id: newBlockId(), type: "image", data: { url: "", alt: "", caption: "", href: "" } }),
  },
  list: {
    type: "list",
    label: "Lista",
    description: "Lista numerowana lub punktowana.",
    icon: ListIcon,
    category: "text",
    create: () => ({ id: newBlockId(), type: "list", data: { ordered: false, items: [""] } }),
  },
  quote: {
    type: "quote",
    label: "Cytat",
    description: "Wyróżniony cytat z opcjonalnym autorem.",
    icon: QuoteIcon,
    category: "text",
    create: () => ({ id: newBlockId(), type: "quote", data: { text: "", cite: "" } }),
  },
  // Stuby - pełne implementacje w kolejnym etapie. Tworzenie blokuje fallback.
  code: {
    type: "code",
    label: "Kod",
    description: "Blok kodu z podświetlaniem.",
    icon: CodeIcon,
    category: "advanced",
    create: () => ({ id: newBlockId(), type: "code", data: { lang: "ts", code: "" } }),
  },
  embed: {
    type: "embed",
    label: "Embed",
    description: "YouTube, Vimeo, X - z URL.",
    icon: PlaySquare,
    category: "media",
    create: () => ({ id: newBlockId(), type: "embed", data: { url: "" } }),
  },
  video: {
    type: "video",
    label: "Wideo",
    description: "Plik wideo lub URL.",
    icon: VideoIcon,
    category: "media",
    create: () => ({ id: newBlockId(), type: "video", data: { url: "", poster: "" } }),
  },
  gallery: {
    type: "gallery",
    label: "Galeria",
    description: "Siatka obrazów.",
    icon: Images,
    category: "media",
    create: () => ({ id: newBlockId(), type: "gallery", data: { images: [] } }),
  },
  separator: {
    type: "separator",
    label: "Separator",
    description: "Linia rozdzielająca.",
    icon: Minus,
    category: "layout",
    create: () => ({ id: newBlockId(), type: "separator", data: { variant: "line" } }),
  },
  callout: {
    type: "callout",
    label: "Callout",
    description: "Info / warning / success / danger.",
    icon: AlertCircle,
    category: "text",
    create: () => ({ id: newBlockId(), type: "callout", data: { variant: "info", text: "" } }),
  },
  table: {
    type: "table",
    label: "Tabela",
    description: "Wiersze i kolumny.",
    icon: TableIcon,
    category: "advanced",
    create: () => ({ id: newBlockId(), type: "table", data: { rows: [[""]], header: false } }),
  },
  button: {
    type: "button",
    label: "Przycisk",
    description: "Etykieta + link.",
    icon: MousePointer2,
    category: "layout",
    create: () => ({ id: newBlockId(), type: "button", data: { label: "Kliknij", href: "#", variant: "default" } }),
  },
  columns: {
    type: "columns",
    label: "Kolumny",
    description: "Dwie kolumny z blokami.",
    icon: ColumnsIcon,
    category: "layout",
    create: () => ({ id: newBlockId(), type: "columns", data: { left: [], right: [] } }),
  },
  html: {
    type: "html",
    label: "HTML",
    description: "Surowy HTML (sanitizowany).",
    icon: FileCode,
    category: "advanced",
    create: () => ({ id: newBlockId(), type: "html", data: { html: "" } }),
  },
  liveblog: {
    type: "liveblog",
    label: "Live Blog",
    description: "Wpisy na żywo z auto-odświeżaniem (timestamped).",
    icon: RadioIcon,
    category: "advanced",
    create: () => ({
      id: newBlockId(),
      type: "liveblog",
      data: { title: "", reverseChronological: true, autoRefresh: true },
    }),
  },
  review: {
    type: "review",
    label: "Recenzja (Review Box)",
    description: "Ocena z paskami kryteriów + CTA (Foxiz-style).",
    icon: StarIcon,
    category: "advanced",
    create: () => ({
      id: newBlockId(),
      type: "review",
      data: {
        title: "",
        summary: "",
        criteria: [
          { label: "", score: 8 },
          { label: "", score: 8 },
        ],
        ctaLabel: "",
        ctaHref: "",
        scale: 10,
      },
    }),
  },
  proscons: {
    type: "proscons",
    label: "Plusy i minusy",
    description: "Dwie kolumny: zalety i wady.",
    icon: ProsConsIcon,
    category: "advanced",
    create: () => ({
      id: newBlockId(),
      type: "proscons",
      data: {
        title: "",
        pros: [""],
        cons: [""],
      },
    }),
  },
  spoiler: {
    type: "spoiler",
    label: "Spoiler / Rozwijany",
    description: "Ukryty blok, otwierany po kliknięciu.",
    icon: SpoilerIcon,
    category: "advanced",
    create: () => ({
      id: newBlockId(),
      type: "spoiler",
      data: { summary: "", html: "", defaultOpen: false },
    }),
  },
  faq: {
    type: "faq",
    label: "FAQ",
    description: "Lista pytań i odpowiedzi (schema.org FAQPage).",
    icon: FaqIcon,
    category: "advanced",
    create: () => ({
      id: newBlockId(),
      type: "faq",
      data: {
        title: "",
        items: [
          { q: "", a: "" },
        ],
      },
    }),
  },
  toc: {
    type: "toc",
    label: "Spis treści",
    description: "Auto-generowany z nagłówków H2/H3.",
    icon: TocIcon,
    category: "advanced",
    create: () => ({
      id: newBlockId(),
      type: "toc",
      data: { title: "", maxLevel: 3, ordered: false, sticky: false },
    }),
  },
  newsletter: {
    type: "newsletter",
    label: "Newsletter (inline)",
    description: "Formularz zapisu osadzony w treści wpisu.",
    icon: MailIcon,
    category: "advanced",
    create: () => ({
      id: newBlockId(),
      type: "newsletter",
      data: { title: "", description: "", variant: "card" },
    }),
  },
  affiliate: {
    type: "affiliate",
    label: "Produkt afiliacyjny",
    description: "Karta produktu z ceną, sklepem i CTA.",
    icon: AffiliateIcon,
    category: "advanced",
    create: () => ({
      id: newBlockId(),
      type: "affiliate",
      data: {
        title: "",
        description: "",
        image: "",
        price: "",
        currency: "PLN",
        store: "",
        ctaLabel: "",
        ctaHref: "",
        rating: 0,
        sponsored: true,
      },
    }),
  },
  xquote: {
    type: "xquote",
    label: "X Quote (Click-to-Tweet)",
    description: "Wyróżniony cytat w stylu X/Twittera z udostępnianiem.",
    icon: XIcon,
    category: "advanced",
    create: () => ({
      id: newBlockId(),
      type: "xquote",
      data: { text: "", via: "", hashtags: "" },
    }),
  },
  compare: {
    type: "compare",
    label: "Before / After",
    description: "Slider porównujący dwa obrazy.",
    icon: CompareIcon,
    category: "advanced",
    create: () => ({
      id: newBlockId(),
      type: "compare",
      data: {
        before: "",
        after: "",
        labelBefore: "Przed",
        labelAfter: "Po",
      },
    }),
  },
  "login-form": {
    type: "login-form",
    label: "Logowanie",
    description: "Strukturalny formularz logowania (email/hasło, remember-me, OAuth).",
    icon: LoginIcon,
    category: "advanced",
    create: () => ({
      id: newBlockId(),
      type: "login-form",
      data: {
        title_pl: "Zaloguj się",
        title_en: "Sign in",
        subtitle_pl: "",
        subtitle_en: "",
        showRemember: true,
        showShowPassword: true,
        showForgot: true,
        showRegister: true,
        showOAuthGoogle: false,
        redirectTo: "/",
        registerHref: "?mode=signup",
        forgotHref: "?mode=reset",
        submitLabel_pl: "Zaloguj się",
        submitLabel_en: "Sign in",
        variant: "card",
      },
    }),
  },
  "register-form": {
    type: "register-form",
    label: "Rejestracja",
    description: "Strukturalny formularz rejestracji (imię, e-mail, hasło, RODO).",
    icon: RegisterIcon,
    category: "advanced",
    create: () => ({
      id: newBlockId(),
      type: "register-form",
      data: {
        title_pl: "Utwórz konto",
        title_en: "Create account",
        subtitle_pl: "",
        subtitle_en: "",
        showName: true,
        showConfirmPassword: true,
        showNewsletterOptIn: true,
        requireConsent: true,
        consentLabel_pl: "Akceptuję regulamin i politykę prywatności.",
        consentLabel_en: "I accept the terms and privacy policy.",
        redirectTo: "/",
        loginHref: "?mode=signin",
        submitLabel_pl: "Zarejestruj się",
        submitLabel_en: "Sign up",
        variant: "card",
      },
    }),
  },
  "lost-password-form": {
    type: "lost-password-form",
    label: "Reset hasła (zapomniałem)",
    description: "Formularz wysyłki linku resetującego hasło.",
    icon: LostPasswordIcon,
    category: "advanced",
    create: () => ({
      id: newBlockId(),
      type: "lost-password-form",
      data: {
        title_pl: "Resetuj hasło",
        title_en: "Reset password",
        subtitle_pl: "Wyślemy link do zmiany hasła na Twój e-mail.",
        subtitle_en: "We'll email you a password reset link.",
        redirectTo: "/reset-password",
        loginHref: "?mode=signin",
        submitLabel_pl: "Wyślij link",
        submitLabel_en: "Send link",
        variant: "card",
      },
    }),
  },
  "reset-password-form": {
    type: "reset-password-form",
    label: "Ustaw nowe hasło",
    description: "Formularz ustawienia nowego hasła (token z URL recovery).",
    icon: ResetPasswordIcon,
    category: "advanced",
    create: () => ({
      id: newBlockId(),
      type: "reset-password-form",
      data: {
        title_pl: "Ustaw nowe hasło",
        title_en: "Set new password",
        subtitle_pl: "",
        subtitle_en: "",
        showConfirmPassword: true,
        minLength: 8,
        redirectTo: "/login",
        submitLabel_pl: "Zapisz hasło",
        submitLabel_en: "Save password",
        variant: "card",
      },
    }),
  },
  // ===== Gutenberg core - batch 1 =====
  audio: {
    type: "audio", label: "Plik dźwiękowy", description: "Odtwarzacz audio (mp3, ogg, wav).",
    icon: AudioIcon, category: "media",
    create: () => ({ id: newBlockId(), type: "audio", data: { url: "", caption: "" } }),
  },
  cover: {
    type: "cover", label: "Okładka", description: "Obraz tła z nakładką i tytułem.",
    icon: CoverIcon, category: "media",
    create: () => ({ id: newBlockId(), type: "cover", data: { url: "", title: "", overlay: 50, minHeight: 360 } }),
  },
  file: {
    type: "file", label: "Plik", description: "Link do pobrania pliku z przyciskiem.",
    icon: FileIcon, category: "media",
    create: () => ({ id: newBlockId(), type: "file", data: { url: "", label: "", showButton: true } }),
  },
  "media-text": {
    type: "media-text", label: "Media i tekst", description: "Obraz obok tekstu (50/50).",
    icon: MediaTextIcon, category: "media",
    create: () => ({ id: newBlockId(), type: "media-text", data: { url: "", text: "", mediaPosition: "left" } }),
  },
  group: {
    type: "group", label: "Grupa", description: "Kontener łączący bloki w sekcję.",
    icon: GroupIcon, category: "layout",
    create: () => ({ id: newBlockId(), type: "group", data: { layout: "group", children: [], background: "", padding: 16 } }),
  },
  spacer: {
    type: "spacer", label: "Odstęp", description: "Pusta przestrzeń pionowa.",
    icon: SpacerIcon, category: "layout",
    create: () => ({ id: newBlockId(), type: "spacer", data: { height: 40 } }),
  },
  "page-break": {
    type: "page-break", label: "Podział strony", description: "Dzieli wpis na strony (paginacja).",
    icon: PageBreakIcon, category: "layout",
    create: () => ({ id: newBlockId(), type: "page-break", data: {} }),
  },
  "read-more": {
    type: "read-more", label: "Więcej", description: "Granica zajawki (Read More).",
    icon: MoreIcon, category: "layout",
    create: () => ({ id: newBlockId(), type: "read-more", data: { text: "Czytaj dalej" } }),
  },
  pullquote: {
    type: "pullquote", label: "Cytat wyróżniony", description: "Duży, ozdobny cytat.",
    icon: PullquoteIcon, category: "text",
    create: () => ({ id: newBlockId(), type: "pullquote", data: { text: "", cite: "" } }),
  },
  preformatted: {
    type: "preformatted", label: "Wstępnie sformatowany", description: "Zachowuje spacje i nowe linie (<pre>).",
    icon: PreformattedIcon, category: "text",
    create: () => ({ id: newBlockId(), type: "preformatted", data: { text: "" } }),
  },
  verse: {
    type: "verse", label: "Poezja", description: "Tekst z zachowanym łamaniem linii (wiersz).",
    icon: VerseIcon, category: "text",
    create: () => ({ id: newBlockId(), type: "verse", data: { text: "" } }),
  },
  details: {
    type: "details", label: "Szczegóły", description: "Rozwijany blok (HTML <details>).",
    icon: DetailsIcon, category: "text",
    create: () => ({ id: newBlockId(), type: "details", data: { summary: "", body: "" } }),
  },
  // ===== Gutenberg core - batch 2 (layout + widgets) =====
  row: {
    type: "row", label: "Wiersz", description: "Bloki ułożone poziomo (flex row).",
    icon: RowIcon, category: "layout",
    create: () => ({ id: newBlockId(), type: "row", data: { children: [], background: "", padding: 0 } }),
  },
  stack: {
    type: "stack", label: "Stos", description: "Bloki ułożone pionowo (flex column).",
    icon: StackIcon, category: "layout",
    create: () => ({ id: newBlockId(), type: "stack", data: { children: [], background: "", padding: 0 } }),
  },
  grid: {
    type: "grid", label: "Siatka", description: "Bloki w siatce responsywnej (CSS grid).",
    icon: GridIcon, category: "layout",
    create: () => ({ id: newBlockId(), type: "grid", data: { children: [], columns: 3, background: "", padding: 0 } }),
  },
  buttons: {
    type: "buttons", label: "Przyciski", description: "Grupa przycisków w jednej linii.",
    icon: ButtonsIcon, category: "layout",
    create: () => ({ id: newBlockId(), type: "buttons", data: { items: [{ label: "Button", href: "#", variant: "default" }], align: "left" } }),
  },
  "social-icons": {
    type: "social-icons", label: "Ikony społeczności", description: "Linki do mediów społecznościowych.",
    icon: SocialIcon, category: "layout",
    create: () => ({ id: newBlockId(), type: "social-icons", data: { items: [{ platform: "facebook", url: "" }], size: "md", align: "left" } }),
  },
  search: {
    type: "search", label: "Wyszukiwarka", description: "Formularz wyszukiwania witryny.",
    icon: SearchIcon, category: "layout",
    create: () => ({ id: newBlockId(), type: "search", data: { placeholder: "Szukaj…", buttonLabel: "Szukaj", action: "/search" } }),
  },
  "latest-posts": {
    type: "latest-posts", label: "Najnowsze wpisy", description: "Lista lub siatka ostatnich publikacji.",
    icon: LatestPostsIcon, category: "advanced",
    create: () => ({ id: newBlockId(), type: "latest-posts", data: { count: 5, category: "", showImage: true, showExcerpt: false, layout: "list" } }),
  },
  // ===== Gutenberg core - batch 3 (taxonomy + widgets) =====
  "tag-cloud": {
    type: "tag-cloud", label: "Chmura tagów", description: "Lista tagów z proporcjonalnym rozmiarem.",
    icon: TagCloudIcon, category: "advanced",
    create: () => ({ id: newBlockId(), type: "tag-cloud", data: { count: 30, showCount: false } }),
  },
  "categories-list": {
    type: "categories-list", label: "Lista kategorii", description: "Lista kategorii lub dropdown.",
    icon: CategoriesIcon, category: "advanced",
    create: () => ({ id: newBlockId(), type: "categories-list", data: { showCount: false, hierarchical: false, layout: "list" } }),
  },
  archives: {
    type: "archives", label: "Archiwa", description: "Archiwa miesięczne (lista lub dropdown).",
    icon: ArchivesIcon, category: "advanced",
    create: () => ({ id: newBlockId(), type: "archives", data: { showCount: true, layout: "list" } }),
  },
  calendar: {
    type: "calendar", label: "Kalendarz", description: "Kalendarz publikacji w danym miesiącu.",
    icon: CalendarIcon, category: "advanced",
    create: () => ({ id: newBlockId(), type: "calendar", data: { month: "" } }),
  },
  // ===== Phase 2 - theme/post (Query) blocks =====
  "post-title": {
    type: "post-title", label: "Tytuł wpisu", description: "Dynamiczny tytuł bieżącego wpisu.",
    icon: PostTitleIcon, category: "advanced",
    create: () => ({ id: newBlockId(), type: "post-title", data: { level: 1 } }),
  },
  "post-date": {
    type: "post-date", label: "Data wpisu", description: "Data publikacji (lub aktualizacji).",
    icon: PostDateIcon, category: "advanced",
    create: () => ({ id: newBlockId(), type: "post-date", data: { format: "long", showUpdated: false } }),
  },
  "post-author": {
    type: "post-author", label: "Autor wpisu", description: "Awatar, imię i (opcjonalnie) bio.",
    icon: PostAuthorIcon, category: "advanced",
    create: () => ({ id: newBlockId(), type: "post-author", data: { showAvatar: true, showBio: false } }),
  },
  "post-excerpt": {
    type: "post-excerpt", label: "Zajawka wpisu", description: "Krótki opis (excerpt).",
    icon: PostExcerptIcon, category: "advanced",
    create: () => ({ id: newBlockId(), type: "post-excerpt", data: { showMore: false } }),
  },
  "post-featured-image": {
    type: "post-featured-image", label: "Obraz wyróżniony", description: "Cover wpisu z proporcjami.",
    icon: PostFeaturedIcon, category: "advanced",
    create: () => ({ id: newBlockId(), type: "post-featured-image", data: { aspect: "16/9", rounded: true } }),
  },
  "post-terms": {
    type: "post-terms", label: "Taksonomie wpisu", description: "Kategorie lub tagi powiązane z wpisem.",
    icon: PostTermsIcon, category: "advanced",
    create: () => ({ id: newBlockId(), type: "post-terms", data: { taxonomy: "categories" } }),
  },
  "site-title": {
    type: "site-title", label: "Tytuł witryny", description: "Nazwa witryny z site_settings.",
    icon: SiteTitleIcon, category: "advanced",
    create: () => ({ id: newBlockId(), type: "site-title", data: { level: 1 } }),
  },
  "site-tagline": {
    type: "site-tagline", label: "Slogan witryny", description: "Tagline witryny.",
    icon: SiteTaglineIcon, category: "advanced",
    create: () => ({ id: newBlockId(), type: "site-tagline", data: {} }),
  },
  "site-logo": {
    type: "site-logo", label: "Logo witryny", description: "Logo z linkiem do strony głównej.",
    icon: SiteLogoIcon, category: "advanced",
    create: () => ({ id: newBlockId(), type: "site-logo", data: { width: 120 } }),
  },
  navigation: {
    type: "navigation", label: "Nawigacja", description: "Menu nawigacyjne (mega menu / linki).",
    icon: NavigationIcon, category: "layout",
    create: () => ({ id: newBlockId(), type: "navigation", data: { menuKey: "primary", layout: "horizontal" } }),
  },
  "post-navigation-link": {
    type: "post-navigation-link", label: "Poprzedni / Następny wpis", description: "Link do poprzedniego lub następnego wpisu.",
    icon: PostNavIcon, category: "advanced",
    create: () => ({ id: newBlockId(), type: "post-navigation-link", data: { direction: "next", showTitle: true } }),
  },
  "query-loop": {
    type: "query-loop", label: "Pętla zapytań", description: "Lista wpisów wg filtrów (kategoria, limit, sortowanie).",
    icon: QueryLoopIcon, category: "advanced",
    create: () => ({
      id: newBlockId(), type: "query-loop",
      data: { categorySlug: "", limit: 6, layout: "grid", showExcerpt: true, showDate: true, showImage: true, orderBy: "date" },
    }),
  },
  breadcrumbs: {
    type: "breadcrumbs", label: "Okruszki", description: "Ścieżka nawigacji do bieżącej strony.",
    icon: BreadcrumbsIcon, category: "advanced",
    create: () => ({ id: newBlockId(), type: "breadcrumbs", data: { separator: "/", showHome: true } }),
  },
  "reading-time": {
    type: "reading-time", label: "Czas czytania", description: "Szacowany czas czytania wpisu.",
    icon: ReadingTimeIcon, category: "advanced",
    create: () => ({ id: newBlockId(), type: "reading-time", data: { wpm: 220, prefix: "" } }),
  },
  "share-buttons": {
    type: "share-buttons", label: "Udostępnij", description: "Przyciski udostępniania w social media.",
    icon: ShareIcon, category: "advanced",
    create: () => ({
      id: newBlockId(), type: "share-buttons",
      data: { networks: ["facebook", "x", "linkedin", "copy"], variant: "filled" },
    }),
  },
  "post-views": {
    type: "post-views", label: "Wyświetlenia", description: "Licznik wyświetleń wpisu.",
    icon: ViewsIcon, category: "advanced",
    create: () => ({ id: newBlockId(), type: "post-views", data: { suffix: "" } }),
  },
  "author-bio": {
    type: "author-bio", label: "Bio autora", description: "Karta autora z avatarem, bio i linkami.",
    icon: AuthorBioIcon, category: "advanced",
    create: () => ({
      id: newBlockId(), type: "author-bio",
      data: { showAvatar: true, showSocial: true, showPostsCount: true, variant: "card" },
    }),
  },
  "related-posts": {
    type: "related-posts", label: "Powiązane wpisy", description: "Sugerowane wpisy z tej samej kategorii.",
    icon: RelatedIcon, category: "advanced",
    create: () => ({
      id: newBlockId(), type: "related-posts",
      data: { limit: 3, strategy: "category", layout: "grid", heading: "" },
    }),
  },
};

export const BLOCK_LIST: BlockSpec[] = Object.values(BLOCK_SPECS);

export const IMPLEMENTED_BLOCKS: BlockType[] = [
  "paragraph", "heading", "image", "list", "quote", "code", "embed", "video", "gallery",
  "separator", "callout", "table", "button", "columns", "html", "liveblog",
  "review", "proscons", "spoiler", "faq", "toc", "newsletter", "affiliate", "xquote", "compare",
  "login-form", "register-form", "lost-password-form", "reset-password-form",
  "audio", "cover", "file", "media-text", "group", "spacer",
  "page-break", "read-more", "pullquote", "preformatted", "verse", "details",
  "row", "stack", "grid", "buttons", "social-icons", "search", "latest-posts",
  "tag-cloud", "categories-list", "archives", "calendar",
  "post-title", "post-date", "post-author", "post-excerpt", "post-featured-image", "post-terms",
  "site-title", "site-tagline", "site-logo",
  "navigation", "post-navigation-link", "query-loop",
  "breadcrumbs", "reading-time", "share-buttons", "post-views",
  "author-bio", "related-posts",
];
