// BROKER TOKENU SESJI DO EDYTORA: `src/integrations/supabase/previewAuthStorage.ts`.
//
// PO CO TEN PLIK ISTNIEJE. `brokeredPreviewStorage()` jest wstrzykiwany jako
// `auth.storage` prawdziwego klienta Supabase (`client.ts`, linia 35), czyli
// decyduje o tym, GDZIE LEŻY I KOMU JEST PODAWANY TOKEN SESJI. Do 04.09.2026
// miał 0,00% pokrycia w każdym wymiarze: 0/50 linii, 0/14 funkcji, 0/51 gałęzi
// (zmierzone `--coverage.reporter=json-summary` przed napisaniem tego pliku).
// Zero nie wynikało z braku wartości kodu, a z jego położenia: klient Supabase
// jest w testach podmieniany na atrapę w kilkuset plikach, a `client.ts` tworzy
// prawdziwy klient LENIWIE (Proxy), więc ciało brokera nie wykonało się w CI
// ANI RAZ. Kod, który rozdaje token sesji przez `postMessage`, nie miał żadnego
// dowodu zachowania.
//
// CO JEST PRZEDMIOTEM DOWODU - TRZY PREDYKATY BEZPIECZEŃSTWA. Ten plik nie
// testuje „czy storage działa"; testuje trzy reguły, których złamanie oznacza
// wyciek tokenu sesji do obcej strony:
//
//   1. ALLOWLISTA STREF PODGLĄDU (`PREVIEW_ZONES`, :8-9). Broker włącza się
//      WYŁĄCZNIE na hoście z pięciu stref Lovable, i to z granicą kropki
//      (`host === z || host.endsWith('.' + z)`). Bez granicy kropki host
//      `evil-lovableproject.com` byłby „strefą podglądu".
//
//   2. ID PROJEKTU CZYTANE TYLKO Z POZYCJI HOSTA NIEKONTROLOWANYCH PRZEZ
//      UŻYTKOWNIKA (:10-16). Komentarz w źródle mówi wprost, po co ta reguła
//      istnieje: żeby host nazwany przez użytkownika (`preview--<nazwa>`) NIE
//      PRZEMYCIŁ id CUDZEGO projektu. Regex dopuszcza `id-preview[-sufiks]--<UUIDv4>[-dev]`
//      albo `project--<UUIDv4>[-dev]` na POCZĄTKU hosta, albo `<UUIDv4>` na
//      samym początku - i nic więcej.
//
//   3. WALIDACJA ORIGINU ADRESATA (:20-29, :47, :54-55). Token wychodzi
//      `postMessage`-em z `targetOrigin` per ZAUFANY origin edytora, nigdy
//      z `"*"`; ancestor spoza allowlisty NIE staje się adresatem (spada na
//      listę domyślną), a odpowiedzi z originu spoza allowlisty są ignorowane.
//      To jest ta sama reguła z dwóch stron: nie mówimy obcemu i nie wierzymy
//      obcemu.
//
// DWIE WARSTWY DOWODU I DLACZEGO OBIE SĄ KONIECZNE. Pierwsza linia pliku
// produkcyjnego brzmi „This file is automatically generated. Do not edit it
// directly." - i to jest cała przyczyna istnienia sekcji „BRAMKA REGENERACJI"
// na końcu. Test ZACHOWANIA sprawdza regułę, która jest w pliku DZIŚ. Kolejna
// generacja może podmienić regex na słabszy (np. dopuścić `preview--<uuid>`
// albo `targetOrigin: '*'`), a testy zachowania nadal by PRZESZŁY - bo
// testowałyby wtedy nową, słabszą regułę i nazywały ją poprawną. Dlatego obok
// zachowania stoi bramka STATYCZNA na treści źródła: ona oblewa się w chwili,
// w której którykolwiek z trzech predykatów zniknie z generowanego pliku.
// Wzorzec jest w repo ustalony: `src/routes/api/public/-jobs-tick.test.ts`,
// sekcja „wierność atrapy `secretsEqual`".
//
// REGUŁA TEGO PLIKU: NIE ATRAPUJE MODUŁU, KTÓRY POKRYWA. `brokeredPreviewStorage`
// jest importowany i wołany PRAWDZIWY. Podmieniane jest wyłącznie ŚRODOWISKO
// przeglądarki, którego test nie ma jak mieć naturalnie: `location.hostname`,
// `location.ancestorOrigins`, `document.referrer` i `window.parent`. `localStorage`
// jest PRAWDZIWY (happy-dom), bo to on jest przedmiotem dowodu o „kopii lokalnej".
//
// RODO / BEZPIECZEŃSTWO DANYCH TESTOWYCH. Zero prawdziwych sekretów: tokeny to
// łańcuch „token-testowy", UUID-y są syntetyczne (wygenerowane pod sam kształt
// v4), a host napastnika mieści się w domenie dokumentacyjnej `example.com`
// (RFC 2606), więc nie należy do nikogo.
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { readFileSync } from "node:fs";

import { brokeredPreviewStorage } from "../previewAuthStorage";

// --- dane syntetyczne -------------------------------------------------------

/** UUID v4 „naszego" projektu. Syntetyczny, ale zgodny z kształtem z regexu. */
const UUID_PROJEKTU = "1a2b3c4d-5e6f-4a7b-8c9d-0e1f2a3b4c5d";
/** UUID v4 CUDZEGO projektu - to jego próbuje przemycić host napastnika. */
const UUID_OFIARY = "9f8e7d6c-5b4a-4938-b271-605f4e3d2c1b";
/** Ten sam kształt, ale wersja 1 (`1a7b` zamiast `4a7b`) - regex go odrzuca. */
const UUID_NIE_V4 = "1a2b3c4d-5e6f-1a7b-8c9d-0e1f2a3b4c5d";

const KLUCZ = "sb-projekt-testowy-auth-token";
const TOKEN = "token-testowy";
const TOKEN_LOKALNY = "token-testowy-lokalny";
const TOKEN_OBCEGO = "token-testowy-od-obcego";

// Protokół drutowy brokera. Powtórzony w teście świadomie: to KONTRAKT z
// edytorem, więc jego zmiana ma zapalić testy, a nie przejść niezauważona.
const RESULT = "lovable-preview-auth:result";
const GET = "lovable-preview-auth:get";
const SET = "lovable-preview-auth:set";
const REMOVE = "lovable-preview-auth:remove";

const LOVABLE = "https://lovable.dev";
const LOCALHOST = "http://localhost:3000";
const GPTENGINEER = "https://cokolwiek.gptengineer.app";
/** Obcy embedder - domena dokumentacyjna, nie należy do nikogo. */
const OBCY = "https://zly-embedder.example.com";

const TIMEOUT = 2000;
const RETRY_DELAY = 250;

// --- typy kontraktu ---------------------------------------------------------

/** Wiadomość, którą broker wysyła do edytora (`msg` z linii 52-53 źródła). */
type WiadomoscBrokera = {
  type: string;
  requestId: string;
  projectId: string;
  key: string;
  value?: string;
};

/** Odpowiedź edytora - celowo „luźna", żeby dać się zepsuć w testach. */
type OdpowiedzEdytora = {
  type?: string;
  requestId?: string;
  ok?: boolean;
  value?: string | null;
} | null;

type Broker = {
  getItem: (key: string) => Promise<string | null>;
  setItem: (key: string, value: string) => Promise<undefined>;
  removeItem: (key: string) => Promise<undefined>;
};

// --- instrumenty pomiarowe --------------------------------------------------

/**
 * Zapis JEDNEJ wysyłki. `kopiaLokalna` jest czytana W MOMENCIE `postMessage`,
 * bo to jedyny sposób udowodnienia KOLEJNOŚCI „najpierw localStorage, potem
 * broker" (po zakończeniu wywołania kolejność jest już nieodtwarzalna).
 */
type Wysylka = { msg: WiadomoscBrokera; targetOrigin: string; kopiaLokalna: string | null };

const wyslane: Wysylka[] = [];
/** Cele WSZYSTKICH wysyłek w całym pliku - materiał dla testu-podsumowania. */
const wszystkieCele: string[] = [];

const postMessage = vi.fn<(msg: WiadomoscBrokera, targetOrigin: string) => void>(
  (msg, targetOrigin) => {
    wyslane.push({ msg, targetOrigin, kopiaLokalna: localStorage.getItem(msg.key) });
    wszystkieCele.push(targetOrigin);
  },
);

/** Atrapa okna edytora. Musi być INNYM obiektem niż `window` - inaczej `framed` jest false. */
const rodzic = { postMessage };

const oryginalnyReferrer = Object.getOwnPropertyDescriptor(document, "referrer");

type Ramka = "w-ramce" | "top-level" | "bez-parenta";

/**
 * Ustawia środowisko przeglądarki dla JEDNEGO przypadku. `brokeredPreviewStorage`
 * czyta `location.hostname` przy KAŻDYM wywołaniu, więc nie ma tu stanu
 * modułowego do resetowania - wystarczy podmiana przed wywołaniem.
 */
function ustawSrodowisko({
  host,
  ancestorOrigins,
  referrer = "",
  ramka = "w-ramce",
}: {
  host: string;
  /** Pominięcie = `location` BEZ `ancestorOrigins` (tak jest w Firefoksie) -> kod schodzi na `document.referrer`. */
  ancestorOrigins?: readonly string[];
  referrer?: string;
  ramka?: Ramka;
}): void {
  vi.stubGlobal("location", {
    hostname: host,
    href: `https://${host}/`,
    origin: `https://${host}`,
    protocol: "https:",
    ...(ancestorOrigins === undefined ? {} : { ancestorOrigins }),
  });
  Object.defineProperty(document, "referrer", { value: referrer, configurable: true });
  const parent = ramka === "w-ramce" ? rodzic : ramka === "bez-parenta" ? undefined : window;
  Object.defineProperty(window, "parent", { value: parent, configurable: true, writable: true });
}

/** Zwraca broker albo OBLEWA test - używane tam, gdzie broker jest tezą. */
function jakoBroker(wynik: ReturnType<typeof brokeredPreviewStorage>): Broker {
  if (!wynik || "clear" in wynik) {
    throw new Error("oczekiwano brokera postMessage, a dostano localStorage/undefined");
  }
  return wynik;
}

function wysylka(nr: number): Wysylka {
  const w = wyslane[nr];
  if (!w) throw new Error(`brak wysyłki nr ${nr} - wysłano ${wyslane.length}`);
  return w;
}

/** Wstrzykuje wiadomość „od edytora" z WYBRANYM originem (to on jest przedmiotem dowodu). */
function wiadomoscOd(origin: string, dane: OdpowiedzEdytora): void {
  window.dispatchEvent(new MessageEvent("message", { data: dane, origin }));
}

/** Odpowiedź poprawnie zaadresowana do n-tej wysyłki (requestId z niej odczytany). */
function odpowiedzNa(
  nr: number,
  origin: string,
  pola: { ok?: boolean; value?: string | null; type?: string } = {},
): void {
  wiadomoscOd(origin, {
    type: pola.type ?? RESULT,
    requestId: wysylka(nr).msg.requestId,
    ok: pola.ok ?? true,
    value: pola.value,
  });
}

/** Domyka `request()`, którego nikt nie obsłużył (TIMEOUT = 2000 ms w źródle). */
async function przeczekajTimeout(): Promise<void> {
  await vi.advanceTimersByTimeAsync(TIMEOUT);
}

beforeEach(() => {
  // Zegary udawane są konieczne dla PONOWIENIA i TIMEOUT-u; w pozostałych
  // przypadkach są nieszkodliwe, bo odpowiedź edytora wstrzykujemy zdarzeniem.
  vi.useFakeTimers();
  localStorage.clear();
  wyslane.length = 0;
  postMessage.mockClear();
});

afterEach(() => {
  vi.useRealTimers();
  vi.unstubAllGlobals();
  // `window.parent` i `document.referrer` nie idą przez `stubGlobal`, więc
  // wracają ręcznie. Domyślny stan happy-dom to `window.parent === window`.
  Object.defineProperty(window, "parent", { value: window, configurable: true, writable: true });
  if (oryginalnyReferrer) Object.defineProperty(document, "referrer", oryginalnyReferrer);
  localStorage.clear();
});

// ===========================================================================
// 0. BRAK OKNA (SSR)
// ===========================================================================

describe("brak `window` (render serwerowy)", () => {
  it("zwraca `undefined`, zamiast sięgać po `location`", () => {
    // Klient Supabase powstaje także na serwerze (SSR tras). Gdyby broker
    // dotknął tu `location`, każdy render serwerowy wywracałby się wyjątkiem;
    // `undefined` oznacza „Supabase, użyj własnego magazynu pamięciowego".
    vi.stubGlobal("window", undefined);
    expect(brokeredPreviewStorage()).toBeUndefined();
  });
});

// ===========================================================================
// 1. PREDYKAT 1: ALLOWLISTA STREF PODGLĄDU
// ===========================================================================

describe("predykat 1: broker włącza się TYLKO w strefie podglądu", () => {
  it("na hoście produkcyjnym serwisu oddaje `localStorage`, a token nie rusza się z przeglądarki", () => {
    // To jest przypadek KAŻDEGO odwiedzającego neweuropeanstrategies.com:
    // broker musi być WYŁĄCZONY, bo nie ma tu żadnego edytora, a `postMessage`
    // z tokenem byłby wyciekiem do dowolnej strony, która nas oprawi w ramkę.
    ustawSrodowisko({ host: "neweuropeanstrategies.com", ancestorOrigins: [OBCY] });
    localStorage.setItem(KLUCZ, TOKEN_LOKALNY);

    const wynik = brokeredPreviewStorage();

    expect(wynik).toBe(localStorage);
    expect(wynik?.getItem(KLUCZ)).toBe(TOKEN_LOKALNY);
    expect(postMessage).not.toHaveBeenCalled();
  });

  it.each([
    ["lovableproject.com", "sama strefa, bez żadnego id w hoście"],
    ["gpt-eng.com", "sama strefa dev, bez id"],
  ])("host równy samej strefie (`%s`) oddaje `localStorage` - %s", (host) => {
    // Strefa TAK, ale id projektu nie ma skąd wziąć - broker bez `projectId`
    // nie ma o co pytać edytora.
    ustawSrodowisko({ host, ancestorOrigins: [LOVABLE] });
    expect(brokeredPreviewStorage()).toBe(localStorage);
  });

  it("w strefie podglądu, ale BEZ ramki (`window.parent === window`) oddaje `localStorage`", () => {
    // Otwarty podgląd w osobnej karcie nie ma edytora, do którego można mówić.
    // Bez tego warunku broker wołałby `postMessage` na samym sobie i każdy
    // `getItem` czekałby 2 s na odpowiedź, której nikt nie wyśle.
    ustawSrodowisko({
      host: `id-preview--${UUID_PROJEKTU}.lovableproject.com`,
      ancestorOrigins: [LOVABLE],
      ramka: "top-level",
    });
    expect(brokeredPreviewStorage()).toBe(localStorage);
  });

  it("w strefie podglądu, gdy `window.parent` jest niedostępny, oddaje `localStorage`", () => {
    ustawSrodowisko({
      host: `id-preview--${UUID_PROJEKTU}.lovableproject.com`,
      ancestorOrigins: [LOVABLE],
      ramka: "bez-parenta",
    });
    expect(brokeredPreviewStorage()).toBe(localStorage);
  });

  it.each([
    [`id-preview--${UUID_PROJEKTU}.lovableproject.com`, "kanoniczny host podglądu edytora"],
    [
      `id-preview-abc--${UUID_PROJEKTU}.lovableproject.com`,
      "host podglądu z sufiksem infrastruktury",
    ],
    [`project--${UUID_PROJEKTU}.lovableproject.com`, "host projektu"],
    [`id-preview--${UUID_PROJEKTU}-dev.lovableproject.com`, "wariant `-dev` hosta podglądu"],
    [`project--${UUID_PROJEKTU}-dev.lovableproject.com`, "wariant `-dev` hosta projektu"],
    [`${UUID_PROJEKTU}.lovableproject.com`, "id na samym początku, granica kropką"],
    [`${UUID_PROJEKTU}-preview.lovableproject.com`, "id na samym początku, granica myślnikiem"],
    [`id-preview--${UUID_PROJEKTU}.lovable.app`, "inna strefa z allowlisty"],
    [`id-preview--${UUID_PROJEKTU}.gptengineer.run`, "kolejna strefa z allowlisty"],
  ])("host `%s` włącza brokera i niesie id z hosta - %s", async (host) => {
    ustawSrodowisko({ host, ancestorOrigins: [LOVABLE] });

    const broker = jakoBroker(brokeredPreviewStorage());
    expect(typeof broker.getItem).toBe("function");
    expect(typeof broker.setItem).toBe("function");
    expect(typeof broker.removeItem).toBe("function");

    // Dowód, że `projectId` w wiadomości pochodzi z UZNANEJ pozycji hosta -
    // a nie że broker „jakoś" wystartował.
    const p = broker.removeItem(KLUCZ);
    expect(wysylka(0).msg.projectId).toBe(UUID_PROJEKTU);
    await przeczekajTimeout();
    await expect(p).resolves.toBeUndefined();
  });
});

// ===========================================================================
// 2. PREDYKAT 2: POZYCJA ID W HOŚCIE (NIEKONTROLOWANA PRZEZ UŻYTKOWNIKA)
// ===========================================================================

describe("predykat 2: id projektu tylko z pozycji hosta poza kontrolą użytkownika", () => {
  it.each([
    [
      `preview--${UUID_OFIARY}.lovableproject.com`,
      "przedrostek `preview--` NIE jest w regexie (są tylko `id-preview` i `project`) - to dokładnie ten host, o którym mówi komentarz w źródle",
    ],
    [
      `moj-projekt-${UUID_OFIARY}.lovableproject.com`,
      "UUID stoi w ŚRODKU hosta nazwanego przez użytkownika",
    ],
    [
      `podglad.id-preview--${UUID_OFIARY}.lovableproject.com`,
      "poprawny wzorzec, ale NIE na początku hosta (napastnik dokłada własną etykietę z przodu)",
    ],
    [
      `id-preview-${UUID_OFIARY}.lovableproject.com`,
      "pojedynczy myślnik zamiast `--` (sufiks infrastruktury nie jest separatorem id)",
    ],
    [
      `xid-preview--${UUID_OFIARY}.lovableproject.com`,
      "śmieć przed `id-preview` łamie zakotwiczenie `^`",
    ],
    [
      `id-preview--${UUID_OFIARY}x.lovableproject.com`,
      "brak granicy po UUID (lookahead `(?=\\.|$)`)",
    ],
    [
      `id-preview--${UUID_NIE_V4}.lovableproject.com`,
      "kształt UUID owszem, ale wersja 1 - regex wymaga v4",
    ],
    [
      `id-preview--${UUID_OFIARY}.evil-lovableproject.com`,
      "strefa jako SUFIKS bez granicy kropki - to chroni `endsWith('.' + z)`",
    ],
    [
      `id-preview--${UUID_OFIARY}.lovableproject.com.evil.example.com`,
      "strefa w ŚRODKU hosta napastnika",
    ],
  ])("host `%s` NIE dostaje brokera - %s", (host) => {
    // Cena złamania tej reguły: edytor dostałby pytanie o token PROJEKTU
    // OFIARY z hosta, którego nazwę wybrał napastnik. Dlatego asercja jest
    // podwójna - brak brokera ORAZ brak jakiejkolwiek wysyłki.
    ustawSrodowisko({ host, ancestorOrigins: [LOVABLE] });
    localStorage.setItem(KLUCZ, TOKEN_LOKALNY);

    const wynik = brokeredPreviewStorage();

    expect(wynik).toBe(localStorage);
    expect(wynik?.getItem(KLUCZ)).toBe(TOKEN_LOKALNY);
    expect(postMessage).not.toHaveBeenCalled();
  });
});

// ===========================================================================
// 3. PREDYKAT 3, STRONA WYCHODZĄCA: KOMU WOLNO WYSŁAĆ TOKEN
// ===========================================================================

describe("predykat 3 (wyjście): `targetOrigin` tylko dla zaufanego originu edytora", () => {
  const HOST_PROD = `id-preview--${UUID_PROJEKTU}.lovableproject.com`;
  const HOST_DEV = `id-preview--${UUID_PROJEKTU}.lovableproject-dev.com`;
  const HOST_GPT_DEV = `id-preview--${UUID_PROJEKTU}.gpt-eng.com`;

  /** Wysyła `setItem` (niesie TOKEN) i domyka obietnicę - zwraca zebrane cele. */
  async function wyslijTokenIZbierzCele(): Promise<string[]> {
    const broker = jakoBroker(brokeredPreviewStorage());
    const p = broker.setItem(KLUCZ, TOKEN);
    const cele = wyslane.map((w) => w.targetOrigin);
    await przeczekajTimeout();
    await expect(p).resolves.toBeUndefined();
    return cele;
  }

  it("ancestor SPOZA allowlisty NIE dostaje tokenu (adresatem zostaje domyślny lovable.dev)", async () => {
    // NAJWAŻNIEJSZY test tej sekcji. Obcy embedder oprawia podgląd w ramkę;
    // gdyby jego origin trafił do `editorOrigins`, przeglądarka DOSTARCZYŁABY
    // mu wiadomość z tokenem sesji. Asercja jest na ARGUMENTACH `postMessage`,
    // bo to one decydują o dostarczeniu.
    ustawSrodowisko({ host: HOST_PROD, ancestorOrigins: [OBCY] });

    const cele = await wyslijTokenIZbierzCele();

    expect(cele).not.toContain(OBCY);
    expect(cele).toEqual([LOVABLE]);
    expect(wysylka(0).msg.value).toBe(TOKEN);
  });

  it.each([
    [LOVABLE, "kanoniczny origin edytora"],
    ["https://app.lovable.dev", "poddomena edytora (regex dopuszcza `([a-z0-9-]+\\.)*`)"],
    [GPTENGINEER, "druga zaufana domena edytora"],
  ])("ancestor `%s` zostaje JEDYNYM adresatem - %s", async (ancestor) => {
    ustawSrodowisko({ host: HOST_PROD, ancestorOrigins: [ancestor] });
    await expect(wyslijTokenIZbierzCele()).resolves.toEqual([ancestor]);
  });

  it.each([
    [
      "https://lovable.dev.evil.example.com",
      "domena edytora jako PRZEDROSTEK hosta napastnika (regex kotwiczy `$`)",
    ],
    ["http://lovable.dev", "właściwa domena, ale bez TLS"],
    [LOCALHOST, "localhost jest dopuszczony WYŁĄCZNIE w strefach dev"],
  ])(
    "ancestor `%s` jest odrzucony i adresatem zostaje domyślny lovable.dev - %s",
    async (ancestor) => {
      ustawSrodowisko({ host: HOST_PROD, ancestorOrigins: [ancestor] });

      const cele = await wyslijTokenIZbierzCele();

      expect(cele).not.toContain(ancestor);
      expect(cele).toEqual([LOVABLE]);
    },
  );

  it("przy braku `ancestorOrigins` origin adresata bierze się z `document.referrer`", async () => {
    // Firefox nie ma `location.ancestorOrigins`; bez tej ścieżki broker w tej
    // przeglądarce zawsze mówiłby do domyślnego originu.
    ustawSrodowisko({ host: HOST_PROD, referrer: `${GPTENGINEER}/projekt/testowy` });
    await expect(wyslijTokenIZbierzCele()).resolves.toEqual([GPTENGINEER]);
  });

  it("`document.referrer` z obcego originu NIE zostaje adresatem", async () => {
    ustawSrodowisko({ host: HOST_PROD, referrer: `${OBCY}/pulapka` });

    const cele = await wyslijTokenIZbierzCele();

    expect(cele).not.toContain(OBCY);
    expect(cele).toEqual([LOVABLE]);
  });

  it("pusta lista `ancestorOrigins` schodzi na `referrer`, a jego brak - na origin domyślny", async () => {
    ustawSrodowisko({ host: HOST_PROD, ancestorOrigins: [], referrer: "" });
    await expect(wyslijTokenIZbierzCele()).resolves.toEqual([LOVABLE]);
  });

  it.each([
    ["strefa `.lovableproject-dev.com`", `id-preview--${UUID_PROJEKTU}.lovableproject-dev.com`],
    ["strefa `.gpt-eng.com`", `id-preview--${UUID_PROJEKTU}.gpt-eng.com`],
  ])("%s dokłada `http://localhost:3000` do listy domyślnej", async (_opis, host) => {
    // Wygoda pracy lokalnej JEST rozszerzeniem powierzchni ataku, więc musi
    // być zamknięta w strefach dev - stąd osobny dowód dla obu tych stref
    // i dowód negatywny dla produkcji poniżej.
    ustawSrodowisko({ host, ancestorOrigins: [OBCY] });

    const cele = await wyslijTokenIZbierzCele();

    expect(cele).toEqual([LOVABLE, LOCALHOST]);
    expect(cele).not.toContain(OBCY);
  });

  it("strefa PRODUKCYJNA nie dokłada `http://localhost:3000`", async () => {
    ustawSrodowisko({ host: HOST_PROD, ancestorOrigins: [OBCY] });
    await expect(wyslijTokenIZbierzCele()).resolves.toEqual([LOVABLE]);
  });

  it("w strefie dev ancestor `http://localhost:3000` jest UZNANY i zostaje jedynym adresatem", async () => {
    ustawSrodowisko({ host: HOST_GPT_DEV, ancestorOrigins: [LOCALHOST] });
    await expect(wyslijTokenIZbierzCele()).resolves.toEqual([LOCALHOST]);
  });

  it("żadna wysyłka nie idzie z `targetOrigin: '*'`", async () => {
    ustawSrodowisko({ host: HOST_DEV, ancestorOrigins: [OBCY] });

    const cele = await wyslijTokenIZbierzCele();

    expect(cele).not.toContain("*");
    expect(cele.length).toBeGreaterThan(0);
    for (const cel of cele)
      expect(cel).toMatch(/^https:\/\/lovable\.dev$|^http:\/\/localhost:3000$/);
  });
});

// ===========================================================================
// 4. PREDYKAT 3, STRONA WCHODZĄCA: KOMU WOLNO WIERZYĆ
// ===========================================================================

describe("predykat 3 (wejście): `onMessage` ufa tylko originom z listy edytora", () => {
  const HOST_PROD = `id-preview--${UUID_PROJEKTU}.lovableproject.com`;

  it("odpowiedź z originu SPOZA listy jest ignorowana - wartość obcego nie wchodzi do sesji", async () => {
    // Druga strona tej samej reguły: gdyby ten filtr wypadł, obcy embedder
    // (albo dowolna ramka na stronie) mógłby WSTRZYKNĄĆ własny token sesji -
    // czyli zalogować użytkownika na swoje konto (session fixation).
    ustawSrodowisko({ host: HOST_PROD, ancestorOrigins: [LOVABLE] });
    localStorage.setItem(KLUCZ, TOKEN_LOKALNY);
    const broker = jakoBroker(brokeredPreviewStorage());

    const p = broker.getItem(KLUCZ);
    // Poprawny `requestId`, poprawny `type`, poprawny kształt - tylko origin obcy.
    wiadomoscOd(OBCY, {
      type: RESULT,
      requestId: wysylka(0).msg.requestId,
      ok: true,
      value: TOKEN_OBCEGO,
    });
    await przeczekajTimeout();
    await vi.advanceTimersByTimeAsync(RETRY_DELAY);
    await przeczekajTimeout();

    // Wynik: kopia lokalna, a nie wartość obcego.
    await expect(p).resolves.toBe(TOKEN_LOKALNY);
  });

  it("odpowiedź zaufanego originu z INNYM `requestId` jest ignorowana", async () => {
    ustawSrodowisko({ host: HOST_PROD, ancestorOrigins: [LOVABLE] });
    localStorage.setItem(KLUCZ, TOKEN_LOKALNY);
    const broker = jakoBroker(brokeredPreviewStorage());

    const p = broker.getItem(KLUCZ);
    wiadomoscOd(LOVABLE, {
      type: RESULT,
      requestId: "requestId-z-innego-zapytania",
      ok: true,
      value: TOKEN_OBCEGO,
    });
    await przeczekajTimeout();
    await vi.advanceTimersByTimeAsync(RETRY_DELAY);
    await przeczekajTimeout();

    await expect(p).resolves.toBe(TOKEN_LOKALNY);
  });

  it.each([
    ["obcy `type`", { type: "inny-protokol:result" }],
    ["brak `type`", {}],
  ])(
    "odpowiedź zaufanego originu bez właściwego `type` jest ignorowana (%s)",
    async (_opis, nadpisz) => {
      ustawSrodowisko({ host: HOST_PROD, ancestorOrigins: [LOVABLE] });
      localStorage.setItem(KLUCZ, TOKEN_LOKALNY);
      const broker = jakoBroker(brokeredPreviewStorage());

      const p = broker.getItem(KLUCZ);
      wiadomoscOd(LOVABLE, {
        requestId: wysylka(0).msg.requestId,
        ok: true,
        value: TOKEN_OBCEGO,
        ...nadpisz,
      });
      await przeczekajTimeout();
      await vi.advanceTimersByTimeAsync(RETRY_DELAY);
      await przeczekajTimeout();

      await expect(p).resolves.toBe(TOKEN_LOKALNY);
    },
  );

  it("wiadomość z pustym `data` nie wywraca brokera", async () => {
    // `postMessage` z `null` przychodzi w realnym ruchu (biblioteki, devtools).
    ustawSrodowisko({ host: HOST_PROD, ancestorOrigins: [LOVABLE] });
    localStorage.setItem(KLUCZ, TOKEN_LOKALNY);
    const broker = jakoBroker(brokeredPreviewStorage());

    const p = broker.getItem(KLUCZ);
    wiadomoscOd(LOVABLE, null);
    odpowiedzNa(0, LOVABLE, { value: TOKEN });

    await expect(p).resolves.toBe(TOKEN);
  });

  it("druga odpowiedź na to samo zapytanie nie zmienia wyniku (`done` + zdjęty listener)", async () => {
    ustawSrodowisko({ host: HOST_PROD, ancestorOrigins: [LOVABLE] });
    const broker = jakoBroker(brokeredPreviewStorage());

    const p = broker.getItem(KLUCZ);
    odpowiedzNa(0, LOVABLE, { value: TOKEN });
    // Powtórka z inną wartością - nie ma jak nadpisać już rozstrzygniętego wyniku.
    odpowiedzNa(0, LOVABLE, { value: TOKEN_OBCEGO });

    await expect(p).resolves.toBe(TOKEN);
    // I nie zostaje uzbrojony zegar, który mógłby coś zrobić po fakcie.
    await przeczekajTimeout();
    expect(wyslane).toHaveLength(1);
  });

  it("odpowiedź, która wyprzedza uzbrojenie zegara, nie zostaje później nadpisana timeoutem", async () => {
    // TA JEDNA GAŁĄŹ (`if (done) return` w `finish`, :40) jest w przeglądarce
    // NIEOSIĄGALNA: `postMessage` jest tam ZAWSZE asynchroniczny, a każde
    // wyjście z `finish` zdejmuje listener i czyści zegar, więc `finish` woła
    // się raz. Osiągalna staje się przy kolejności, którą to źródło dopuszcza:
    // `timer = setTimeout(...)` jest przypisywany PO `postMessage` (:55-56),
    // więc odpowiedź otrzymana w trakcie wysyłki trafia na `clearTimeout(undefined)`
    // i zostawia uzbrojony zegar na 2 s. Ten test wymusza właśnie tę kolejność
    // i dowodzi, że strażnik `done` połyka spóźniony timeout - czyli że sesja
    // NIE zostaje po dwóch sekundach cofnięta do `null`. Gdyby strażnik
    // wypadł, `resolve` byłby wołany dwa razy (drugi raz z `null`) i przy
    // każdej kolejnej zmianie tej funkcji ryzyko wróciłoby niezauważone.
    ustawSrodowisko({ host: HOST_PROD, ancestorOrigins: [LOVABLE] });
    localStorage.setItem(KLUCZ, TOKEN_LOKALNY);
    Object.defineProperty(window, "parent", {
      configurable: true,
      writable: true,
      value: {
        postMessage: (msg: WiadomoscBrokera, targetOrigin: string) => {
          postMessage(msg, targetOrigin);
          wiadomoscOd(LOVABLE, { type: RESULT, requestId: msg.requestId, ok: true, value: TOKEN });
        },
      },
    });
    const broker = jakoBroker(brokeredPreviewStorage());

    const p = broker.getItem(KLUCZ);
    await expect(p).resolves.toBe(TOKEN);

    // Spóźniony zegar odpala się, ale nie ma już czego rozstrzygać.
    await przeczekajTimeout();
    await expect(p).resolves.toBe(TOKEN);
    expect(wyslane).toHaveLength(1);
  });
});

// ===========================================================================
// 5. `getItem`: TOMBSTONE WYLOGOWANIA, PONOWIENIE, TIMEOUT
// ===========================================================================

describe("`getItem`: odpowiedzi edytora i awaryjne wyjścia", () => {
  const HOST_PROD = `id-preview--${UUID_PROJEKTU}.lovableproject.com`;

  function broker(): Broker {
    ustawSrodowisko({ host: HOST_PROD, ancestorOrigins: [LOVABLE] });
    return jakoBroker(brokeredPreviewStorage());
  }

  it("pyta edytora wiadomością `:get` bez pola `value`", async () => {
    const b = broker();
    const p = b.getItem(KLUCZ);

    const w = wysylka(0);
    expect(w.msg.type).toBe(GET);
    expect(w.msg.key).toBe(KLUCZ);
    expect(w.msg.projectId).toBe(UUID_PROJEKTU);
    expect(w.msg.requestId).toEqual(expect.any(String));
    // Zapytanie o odczyt NIE niesie wartości - inaczej byłby to zapis.
    expect(w.msg).not.toHaveProperty("value");

    odpowiedzNa(0, LOVABLE, { value: TOKEN });
    await expect(p).resolves.toBe(TOKEN);
  });

  it("wartość od edytora WYGRYWA z nieaktualną kopią lokalną", async () => {
    // Po to broker istnieje: wszystkie powierzchnie podglądu mają widzieć
    // JEDNĄ sesję, także wtedy, gdy w `localStorage` tej ramki leży starocie.
    localStorage.setItem(KLUCZ, TOKEN_LOKALNY);
    const b = broker();

    const p = b.getItem(KLUCZ);
    odpowiedzNa(0, LOVABLE, { value: TOKEN });

    await expect(p).resolves.toBe(TOKEN);
  });

  it("TOMBSTONE WYLOGOWANIA: `value === ''` czyści kopię lokalną i zwraca `null`", async () => {
    // Najostrzejszy przypadek tej funkcji. Puste `value` to sygnał „w edytorze
    // ktoś się WYLOGOWAŁ". Gdyby broker tylko zwrócił `null`, a kopii lokalnej
    // nie ruszył, pierwszy cichy timeout brokera ZMARTWYCHWZBUDZIŁBY sesję
    // z `localStorage` - użytkownik byłby zalogowany po wylogowaniu.
    localStorage.setItem(KLUCZ, TOKEN_LOKALNY);
    const b = broker();

    const p = b.getItem(KLUCZ);
    odpowiedzNa(0, LOVABLE, { value: "" });

    await expect(p).resolves.toBeNull();
    expect(localStorage.getItem(KLUCZ)).toBeNull();
  });

  it("`value === null` (nigdy nie synchronizowane) ZOSTAWIA kopię lokalną", async () => {
    // Rozróżnienie „nigdy nie synchronizowane" (null) od „wylogowano" ('')
    // jest całą treścią tej gałęzi: pierwsze NIE MOŻE kasować sesji lokalnej.
    localStorage.setItem(KLUCZ, TOKEN_LOKALNY);
    const b = broker();

    const p = b.getItem(KLUCZ);
    odpowiedzNa(0, LOVABLE, { value: null });

    await expect(p).resolves.toBe(TOKEN_LOKALNY);
    expect(localStorage.getItem(KLUCZ)).toBe(TOKEN_LOKALNY);
  });

  it("odpowiedź `ok: false` schodzi na kopię lokalną", async () => {
    localStorage.setItem(KLUCZ, TOKEN_LOKALNY);
    const b = broker();

    const p = b.getItem(KLUCZ);
    odpowiedzNa(0, LOVABLE, { ok: false, value: TOKEN_OBCEGO });

    await expect(p).resolves.toBe(TOKEN_LOKALNY);
  });

  it("PONOWIENIE pierwszego `getItem`: druga próba dopiero po 250 ms od timeoutu", async () => {
    // Edytor może jeszcze nie nasłuchiwać, gdy ramka odpala pierwszy odczyt.
    // Test mierzy OBA zegary ze źródła: TIMEOUT 2000 i RETRY_DELAY 250.
    const b = broker();
    const p = b.getItem(KLUCZ);

    expect(wyslane).toHaveLength(1);
    await vi.advanceTimersByTimeAsync(TIMEOUT - 1);
    expect(wyslane).toHaveLength(1); // przed timeoutem nic się nie ponawia
    await vi.advanceTimersByTimeAsync(1);
    expect(wyslane).toHaveLength(1); // timeout minął, ale trwa opóźnienie 250 ms
    await vi.advanceTimersByTimeAsync(RETRY_DELAY - 1);
    expect(wyslane).toHaveLength(1);
    await vi.advanceTimersByTimeAsync(1);
    expect(wyslane).toHaveLength(2); // druga próba

    // Druga próba dostaje odpowiedź - i to ona jest wynikiem.
    expect(wysylka(1).msg.type).toBe(GET);
    odpowiedzNa(1, LOVABLE, { value: TOKEN });
    await expect(p).resolves.toBe(TOKEN);
  });

  it("gdy MILCZĄ obie próby, `getItem` oddaje kopię lokalną", async () => {
    localStorage.setItem(KLUCZ, TOKEN_LOKALNY);
    const b = broker();

    const p = b.getItem(KLUCZ);
    await vi.advanceTimersByTimeAsync(TIMEOUT + RETRY_DELAY + TIMEOUT);

    await expect(p).resolves.toBe(TOKEN_LOKALNY);
    expect(wyslane).toHaveLength(2);
  });

  it("gdy milczą obie próby, a kopii lokalnej nie ma, `getItem` oddaje `null`", async () => {
    const b = broker();

    const p = b.getItem(KLUCZ);
    await vi.advanceTimersByTimeAsync(TIMEOUT + RETRY_DELAY + TIMEOUT);

    await expect(p).resolves.toBeNull();
  });

  it("KOLEJNE `getItem` już NIE ponawia - ponowienie jest tylko dla pierwszego", async () => {
    // `firstGet` jest jednorazowy: po pierwszym odczycie edytor albo nasłuchuje,
    // albo go nie ma, a każdy dalszy odczyt nie może kosztować 4,25 s.
    localStorage.setItem(KLUCZ, TOKEN_LOKALNY);
    const b = broker();

    const pierwszy = b.getItem(KLUCZ);
    odpowiedzNa(0, LOVABLE, { value: TOKEN });
    await expect(pierwszy).resolves.toBe(TOKEN);
    expect(wyslane).toHaveLength(1);

    const drugi = b.getItem(KLUCZ);
    await vi.advanceTimersByTimeAsync(TIMEOUT + RETRY_DELAY + TIMEOUT);

    await expect(drugi).resolves.toBe(TOKEN_LOKALNY);
    expect(wyslane).toHaveLength(2); // jedna wysyłka na drugi odczyt, bez ponowienia
  });
});

// ===========================================================================
// 6. `setItem` / `removeItem`: KOLEJNOŚĆ ZAPISU
// ===========================================================================

describe("`setItem` / `removeItem`: kopia lokalna PRZED powiadomieniem brokera", () => {
  const HOST_PROD = `id-preview--${UUID_PROJEKTU}.lovableproject.com`;

  function broker(): Broker {
    ustawSrodowisko({ host: HOST_PROD, ancestorOrigins: [LOVABLE] });
    return jakoBroker(brokeredPreviewStorage());
  }

  it("`setItem` zapisuje `localStorage` NAJPIERW, potem wysyła `:set` z wartością", async () => {
    // Kolejność jest odpornością na awarię: gdyby broker padł albo edytor
    // milczał, sesja jest już zapisana lokalnie. Dowód na kolejności, a nie
    // na samym skutku: atrapa `postMessage` czyta `localStorage` w momencie
    // wywołania.
    const b = broker();

    const p = b.setItem(KLUCZ, TOKEN);

    const w = wysylka(0);
    expect(w.kopiaLokalna).toBe(TOKEN); // localStorage BYŁ już zapisany
    expect(w.msg.type).toBe(SET);
    expect(w.msg.key).toBe(KLUCZ);
    expect(w.msg.value).toBe(TOKEN);
    expect(w.msg.projectId).toBe(UUID_PROJEKTU);
    expect(w.targetOrigin).toBe(LOVABLE);

    odpowiedzNa(0, LOVABLE, { value: TOKEN });
    await expect(p).resolves.toBeUndefined();
  });

  it("`setItem` kończy się `undefined` także wtedy, gdy edytor MILCZY", async () => {
    // Supabase czeka na tę obietnicę przy każdym odświeżeniu tokenu - gdyby
    // nie kończyła się bez odpowiedzi edytora, logowanie by zawisło.
    const b = broker();

    const p = b.setItem(KLUCZ, TOKEN);
    await przeczekajTimeout();

    await expect(p).resolves.toBeUndefined();
    expect(localStorage.getItem(KLUCZ)).toBe(TOKEN);
  });

  it("`removeItem` czyści `localStorage` NAJPIERW, potem wysyła `:remove` bez pola `value`", async () => {
    localStorage.setItem(KLUCZ, TOKEN_LOKALNY);
    const b = broker();

    const p = b.removeItem(KLUCZ);

    const w = wysylka(0);
    expect(w.kopiaLokalna).toBeNull(); // kopia lokalna już usunięta
    expect(w.msg.type).toBe(REMOVE);
    expect(w.msg.key).toBe(KLUCZ);
    expect(w.msg).not.toHaveProperty("value");

    odpowiedzNa(0, LOVABLE, { value: "" });
    await expect(p).resolves.toBeUndefined();
    expect(localStorage.getItem(KLUCZ)).toBeNull();
  });

  it("każde zapytanie ma WŁASNY `requestId`", async () => {
    // Bez unikalności odpowiedź na wylogowanie mogłaby rozstrzygnąć zapytanie
    // o odczyt (i odwrotnie).
    const b = broker();

    const p1 = b.setItem(KLUCZ, TOKEN);
    const p2 = b.removeItem(KLUCZ);

    expect(wysylka(0).msg.requestId).not.toBe(wysylka(1).msg.requestId);

    await przeczekajTimeout();
    await expect(Promise.all([p1, p2])).resolves.toEqual([undefined, undefined]);
  });
});

// ===========================================================================
// 7. PODSUMOWANIE PRZEBIEGU
// ===========================================================================

describe("podsumowanie przebiegu: nic nie wyszło pod obcy origin", () => {
  it("wszystkie `targetOrigin` z tego pliku są zaufanymi originami edytora", () => {
    // Ten test jest PODSUMOWANIEM całego pliku (czyta cele zebrane przez
    // wcześniejsze przypadki), a nie osobnym scenariuszem. Wartość: jeden
    // przypadek, który zapali się, gdy KTÓRYKOLWIEK test wyśle token pod
    // origin spoza allowlisty - także test dopisany w przyszłości.
    const ZAUFANE =
      /^https:\/\/([a-z0-9-]+\.)*(lovable\.dev|gptengineer\.app)$|^http:\/\/localhost:3000$/;

    expect(wszystkieCele.length).toBeGreaterThan(0);
    expect(wszystkieCele).not.toContain("*");
    expect(wszystkieCele.filter((cel) => !ZAUFANE.test(cel))).toEqual([]);
  });
});

// ===========================================================================
// 8. BRAMKA REGENERACJI (WARSTWA STATYCZNA NA TREŚCI ŹRÓDŁA)
// ===========================================================================
//
// DLACZEGO TA SEKCJA JEST KONIECZNA OBOK TESTÓW ZACHOWANIA. `previewAuthStorage.ts`
// jest plikiem GENEROWANYM - jego pierwsza linia zabrania edycji ręcznej, więc
// jego treść może się zmienić bez żadnego przeglądu kodu, przy najbliższej
// regeneracji. Testy zachowania wyżej sprawdzają regułę, KTÓRA JEST W PLIKU:
// gdyby nowa generacja dopuściła `preview--<uuid>` albo wysłała `postMessage`
// z `'*'`, to część tych testów owszem by oblała - ale gdyby regenerator
// przepisał regex tak, że zmienia się GRANICA (np. `(?=[.-])` na `(?=.*)`,
// albo `$` w regexie edytora wypada), testy mogłyby dalej przechodzić na
// scenariuszach, które wybraliśmy, a nowa reguła byłaby SŁABSZA dla hostów,
// o których nikt nie pomyślał. Bramka statyczna nie zgaduje scenariuszy:
// stwierdza, że w pliku NADAL STOI dokładnie ten predykat, który został
// przeanalizowany. Oblanie tego testu po regeneracji jest sygnałem
// „przeczytaj ponownie te trzy reguły", a nie usterką testu.
// Wzorzec bramki: `src/routes/api/public/-jobs-tick.test.ts`.

const PLIK_ZRODLOWY = "src/integrations/supabase/previewAuthStorage.ts";

describe("bramka regeneracji: trzy predykaty bezpieczeństwa w treści źródła", () => {
  const source = readFileSync(PLIK_ZRODLOWY, "utf8");

  it("PREMISA: czytamy TEN plik i jest on nadal GENEROWANY (stąd potrzeba bramki)", () => {
    expect(source.split("\n")[0]).toContain("automatically generated");
    expect(source).toContain("export function brokeredPreviewStorage()");
  });

  it("PREDYKAT 1: allowlista stref z dopasowaniem po granicy kropki", () => {
    // Gdyby dopasowanie zeszło na `host.includes(z)`, host
    // `id-preview--<uuid>.lovableproject.com.evil.example.com` stałby się
    // „strefą podglądu" - a testu zachowania na tym haśle nikt nie musi mieć.
    expect(source).toContain("const PREVIEW_ZONES = [");
    expect(source).toContain("PREVIEW_ZONES.some((z) => host === z || host.endsWith('.' + z))");
    for (const strefa of [
      "'lovableproject.com'",
      "'lovableproject-dev.com'",
      "'lovable.app'",
      "'gpt-eng.com'",
      "'gptengineer.run'",
    ]) {
      expect(source).toContain(strefa);
    }
    expect(source).not.toMatch(/host\.includes\(/);
    expect(source).not.toMatch(/host\.indexOf\(/);
  });

  it("PREDYKAT 2: id projektu czytane wyłącznie z początku hosta", () => {
    // Dwie dopuszczone pozycje i nic więcej. Zakotwiczenie `^` jest tu całym
    // zabezpieczeniem: bez niego `moj-projekt-<uuid>` pasuje.
    expect(source).toContain("'^(?:id-preview(?:-[a-z0-9]+)?|project)--('");
    expect(source).toContain("'^(' + UUID + ')(?=[.-])'");
    expect(source).toContain(
      "const UUID = '[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}'",
    );
  });

  it("PREDYKAT 2 (reguła, nie lista): KAŻDY regex hosta w tym pliku jest zakotwiczony `^`", () => {
    // Reguła zamiast wyliczenia: dowolny NOWY wzorzec hosta, dorzucony przez
    // kolejną generację bez kotwicy, zapala ten test, nawet jeśli nikt nie
    // dopisze mu osobnego dowodu.
    const wzorce = [...source.matchAll(/new RegExp\('([^']*)'/g)].map((m) => m[1] ?? "");
    expect(wzorce.length).toBeGreaterThanOrEqual(2);
    expect(wzorce.filter((w) => !w.startsWith("^"))).toEqual([]);
  });

  it("PREDYKAT 3: regex originu edytora waliduje CAŁY origin (kotwice `^` i `$`)", () => {
    expect(source).toContain(
      "/^https:\\/\\/([a-z0-9-]+\\.)*(lovable\\.dev|gptengineer\\.app)$|^http:\\/\\/localhost:3000$/",
    );
    expect(source).toContain("/^https:\\/\\/([a-z0-9-]+\\.)*(lovable\\.dev|gptengineer\\.app)$/");
    expect(source).toContain("EDITOR.test(ancestor)");
  });

  it("PREDYKAT 3: `postMessage` idzie per zaufany origin i NIGDY z `'*'`", () => {
    // `targetOrigin: '*'` to jednolinijkowa różnica między „token trafia do
    // edytora" i „token trafia do dowolnego embeddera". Ta asercja jest
    // najtwardszą pojedynczą regułą tego pliku.
    expect(source).toContain(
      "for (const origin of editorOrigins) window.parent.postMessage(msg, origin)",
    );
    expect(source).not.toMatch(/postMessage\([^)]*['"`]\*['"`]\s*\)/);
    expect(source).not.toContain("'*'");
    expect(source).not.toContain('"*"');
  });

  it("PREDYKAT 3: odpowiedzi z originu poza listą edytora są odrzucane w `onMessage`", () => {
    expect(source).toContain("if (editorOrigins.indexOf(e.origin) < 0) return;");
  });

  it("stałe czasowe, na których stoją testy ponowienia i timeoutu, są nadal te same", () => {
    // Testy wyżej mierzą 2000 ms i 250 ms. Gdyby generacja zmieniła te liczby,
    // te testy przestałyby mierzyć zachowanie produkcji - a wyglądałyby zdrowo.
    expect(source).toContain(`const TIMEOUT = ${TIMEOUT}`);
    expect(source).toContain(`const RETRY_DELAY = ${RETRY_DELAY}`);
  });
});
