// English labels for the builder's *data-driven* editor copy.
//
// Widget definitions (`WIDGETS`), the declarative content schemas
// (`WIDGET_SCHEMAS`) and the variant catalogues (slider / section label /
// animated heading / sidebar styles) are plain data modules that carry Polish
// `label` / `hint` / `placeholder` / `group` strings. They are consumed by the
// canvas, the widget palette and the properties panel, so an English admin used
// to see a fully Polish editor.
//
// Rather than duplicating every entry in those (large) data modules, the Polish
// string doubles as the translation key and this module supplies the English
// side. `builderLabel()` falls back to the Polish source when no translation
// exists, so an untranslated label degrades to today's behaviour instead of
// rendering an empty control. `labelsEn.test.ts` fails the build when a
// Polish-looking label has no entry here.
import { useCallback } from "react";
import { useTranslation } from "react-i18next";

export type BuilderLang = "pl" | "en";

export const BUILDER_LABELS_EN: Readonly<Record<string, string>> = {
  // ------------------------------------------- social icons: colors + hover
  "Kolory platform": "Platform colors",
  "gradient marki platformy": "platform brand gradient",

  "Facebook - kolor ikony": "Facebook - icon color",
  "X - kolor ikony": "X - icon color",
  "YouTube - kolor ikony": "YouTube - icon color",
  "Instagram - kolor ikony": "Instagram - icon color",
  "LinkedIn - kolor ikony": "LinkedIn - icon color",
  "Spotify - kolor ikony": "Spotify - icon color",
  "Newsletter - kolor ikony": "Newsletter - icon color",
  // ---------------------------------------------------------------- widgets
  Nagłówek: "Heading",
  Wstęp: "Intro",
  "Etykieta przycisku wysyłki": "Submit button label",
  "Licznik kroków": "Step counter",
  "Wymagana zgoda na kontakt": "Require contact consent",
  "Animowany nagłówek": "Animated heading",
  "Rotujący tekst": "Rotating text",
  Odstępnik: "Spacer",
  "Oś czasu": "Timeline",
  "Sankey (przepływy)": "Sankey (flows)",
  "Porównywarka państw": "Country comparison",
  "Karta wskaźnika": "Indicator card",
  "Sieć powiązań": "Relationship network",
  "Biblioteka źródeł": "Source library",
  "Odsłuchaj (TTS)": "Listen (TTS)",
  "Lista wpisów": "Post list",
  "Karuzela wpisów": "Post carousel",
  "Dołącz do nas": "Join us",
  "Link menu": "Menu link",
  "Język (PL/EN)": "Language (PL/EN)",
  Zakładki: "Tabs",
  "Treść (bloki)": "Content (blocks)",
  "Interaktywne koło": "Interactive circle",
  "Spis treści (TOC)": "Table of contents (TOC)",
  "Lista z oceną": "Rated list",
  "Karta wyróżniona (dark)": "Featured card (dark)",
  "Odzyskaj hasło": "Reset password",
  "Ustaw nowe hasło": "Set a new password",
  "Tytuł wpisu (dyn.)": "Post title (dyn.)",
  "Okładka wpisu": "Post cover",
  "Tytuł archiwum": "Archive title",
  Licznik: "Counter",
  Galeria: "Gallery",
  "Mapa Google": "Google map",
  "Mapa danych": "Data map",
  "Mapa korytarzy": "Corridor map",
  // ------------------------------------------------- widget „Mapa świata"
  "Mapa świata (połączenia)": "World map (connections)",
  "Etykiety przy punktach": "Labels next to points",
  "Wyłączone: na mapie zostają same znaczniki, a nazwy niesie lista dostępności.":
    "Off: only the markers stay on the map; the names are carried by the accessibility list.",
  "Kadr mapy": "Map framing",
  "dopasuj do połączeń": "fit to the connections",
  "cały świat": "the whole world",
  "Dopasowanie przybliża mapę do punktów, żeby łuki wypełniły kadr zamiast tonąć w oceanie.":
    "Fitting zooms the map to the points so the arcs fill the frame instead of drowning in the ocean.",
  "Animacja rysowania łuków": "Arc drawing animation",
  "Czas rysowania łuku (s)": "Arc drawing time (s)",
  "Powtarzaj w pętli": "Repeat in a loop",
  "Wyłączone: łuki rysują się raz i zostają.": "Off: the arcs are drawn once and stay.",
  "Macierz ryzyka": "Risk matrix",
  "Nota metodologiczna": "Methodology note",
  Kategorie: "Categories",
  Tagi: "Tags",
  "Formularz kontaktowy": "Contact form",
  "Formularz kontaktowy (legacy)": "Contact form (legacy)",
  "Formularz wyszukiwania": "Search form",
  "Wezwanie do akcji": "Call to action",
  "Dopasuj zainteresowania": "Customize interests",
  "Mega menu": "Mega menu",
  "Ikony social": "Social icons",
  "Puste = kolor tekstu motywu (ciemny w light, jasny w dark) - jak na stronie publicznej.":
    "Empty = theme text colour (dark in light mode, light in dark mode) - just like the public site.",
  // Widget social-icons: źródło linków. Bramka labelsEn wymaga EN dla każdej
  // etykiety schematu - te przyszły z widgetem bez tłumaczeń (CI było czerwone).
  "Źródło linków": "Links source",
  "własne, a gdy puste - globalne": "own, fall back to global when empty",
  "globalne (Opcje motywu → Ikony social)": "global (Theme options → Social icons)",
  "tylko wpisane poniżej": "only the ones entered below",
  "Globalne linki do mediów społecznościowych ustawia się raz w Admin → Wygląd → Opcje motywu → „Ikony social” (/admin/theme-options). Widgety zaciągają je automatycznie.":
    "Global social media links are set once in Admin → Appearance → Theme options → “Social icons” (/admin/theme-options). Widgets pick them up automatically.",
  // Widget social-icons: podświetlenie po najechaniu (wiersz listy / kafelek).
  "Podświetlenie po najechaniu": "Hover highlight",
  // („gradient marki platformy" ma już wpis wyżej - klucz musi być unikalny.)
  "firmowy pomarańcz (jeden dla wszystkich)": "house orange (one for all)",
  "delikatne (ton marki)": "subtle (brand tint)",
  "tylko obramowanie": "outline only",
  "Działa w obu układach: w liście maluje cały wiersz, w rzędzie - kafelek ikony.":
    "Works in both layouts: it paints the whole row in the list, and the icon tile in the row layout.",
  "Własny kolor podświetlenia": "Custom highlight colour",
  "Z koloru budowany jest gradient; kolor tekstu dobiera się automatycznie do jego jasności.":
    "The gradient is built from that colour; the text colour follows its lightness automatically.",
  "Ikony po najechaniu": "Icons on hover",
  "automatycznie (jasne na ciemnym tle)": "automatic (light on a dark background)",
  // „jasne (białe)" jest już przetłumaczone niżej (opcje „Kolory ikon").
  "bez zmiany": "unchanged",
  "Na gradiencie marki i firmowym tryb automatyczny rozjaśnia ikonę także w jasnym motywie.":
    "On brand and house gradients the automatic mode lightens the icon in light mode too.",
  "Własny kolor ikony (hover)": "Custom icon colour (hover)",
  "Tonacja firmowego gradientu": "House gradient tone",
  "Bursztyn (domyślna)": "Amber (default)",
  Koniak: "Cognac",
  Żar: "Ember",
  "Zachód słońca": "Sunset",
  "Tonacja wiersza newslettera oraz całej listy w trybie „firmowy pomarańcz”. Wszystkie rampy trzymają kontrast bieli na poziomie AA.":
    "Tone of the newsletter row and of the whole list in “house orange” mode. Every ramp keeps white text at AA contrast.",
  "Tryb jasny/ciemny": "Light / dark mode",
  "Konto / Logowanie": "Account / sign in",
  Wyszukiwarka: "Search",
  Cytat: "Quote",
  Bulletpointy: "Bullet points",
  Rozdzielacz: "Divider",
  "Okruszki (breadcrumbs)": "Breadcrumbs",
  "Pasek postępu czytania": "Reading progress bar",
  "Pasek hot topic": "Hot topic bar",
  "News ticker": "News ticker",
  "Slot reklamowy": "Ad slot",
  "Podcast: najnowsze": "Podcast: latest",
  "Web Stories: karuzela": "Web Stories: carousel",
  "Darowizny / Mecenat": "Donations / patronage",
  Prelegenci: "Speakers",
  "Karta autora": "Author card",
  "Meta wpisu (data, autor, czas)": "Post meta (date, author, reading time)",
  "Kategorie wpisu (dyn.)": "Post categories (dyn.)",
  "Tagi wpisu (dyn.)": "Post tags (dyn.)",
  "Zajawka wpisu": "Post excerpt",
  "Treść wpisu (automatycznie)": "Post content (automatic)",
  "Tailored must-reads (rekomendacje z imieniem)":
    "Tailored must-reads (personalised recommendations)",
  "Karta odliczania (wydarzenie)": "Event countdown card",
  Logowanie: "Sign in",
  Rejestracja: "Sign up",
  Wydarzenia: "Events",
  Cennik: "Pricing",
  Wykres: "Chart",
  Slider: "Slider",
  Karuzela: "Carousel",
  Wideo: "Video",
  Obrazek: "Image",
  Przycisk: "Button",
  Ikona: "Icon",
  Tekst: "Text",
  Newsletter: "Newsletter",
  Copyright: "Copyright",
  Menu: "Menu",
  Accordion: "Accordion",
  "Team member": "Team member",
  "Etykieta sekcji": "Section label",
  Przepływy: "Flows",
  Korytarze: "Corridors",
  Źródła: "Sources",

  // ------------------------------------------------------------ field groups
  Treść: "Content",
  Wygląd: "Appearance",
  Układ: "Layout",
  Dane: "Data",
  "Kolory ikon": "Icon colours",
  Ikony: "Icons",
  "Kolory wariantu": "Variant colours",
  "Pola / placeholder": "Fields / placeholders",
  "Zgody / stopka": "Consents / footer",
  Kontrolki: "Controls",
  Legenda: "Legend",
  Model: "Model",
  Region: "Region",
  Numeracja: "Numbering",

  // ------------------------------------------------------------- text fields
  Tytuł: "Title",
  "Tytuł wpisu": "Post title",
  Podtytuł: "Subtitle",
  "Podtytuł (opcjonalny)": "Subtitle (optional)",
  "Podtytuł / opis": "Subtitle / description",
  Opis: "Description",
  "Opis (podtytuł)": "Description (subtitle)",
  Zajawka: "Excerpt",
  "Zajawka (opcjonalna)": "Excerpt (optional)",
  Etykieta: "Label",
  "Etykieta (PL)": "Label (PL)",
  "Etykieta (EN)": "Label (EN)",
  "Etykieta (badge)": "Label (badge)",
  "Etykieta CTA": "CTA label",
  "Etykieta archiwum": "Archive label",
  "Etykieta osi X (wpływ)": "X axis label (impact)",
  "Etykieta osi Y (prawdopodobieństwo)": "Y axis label (likelihood)",
  "Etykieta podczas wysyłki": "Label while submitting",
  "Etykieta programu (nad kartą)": "Programme label (above the card)",
  "Portret 3:4. Wgraj lub wybierz z biblioteki mediów.":
    "3:4 portrait. Upload or pick from the media library.",
  "Etykieta nad nazwiskiem": "Label above the name",
  "Opis / bio": "Description / bio",
  "Pokaż ikony social": "Show social icons",
  "Wyłączenie ukrywa całą listę odnośników.": "Turning this off hides the whole list of links.",
  "Działa po powiązaniu osoby z katalogu ekspertów.":
    "Works once a person from the experts directory is linked.",
  "Karta profilu autora": "Author profile card",
  "Etykieta przycisku": "Button label",
  "Etykieta w edytorze": "Label in the editor",
  "Etykieta wskaźnika": "Indicator label",
  "Etykieta zapisu do newslettera": "Newsletter opt-in label",
  "Etykiety pól": "Field labels",
  "Etykiety wartości": "Value labels",
  "Kicker (mały nadtytuł)": "Kicker (small overline)",
  "Nagłówek (użyj {name} dla imienia)": "Heading (use {name} for the first name)",
  "Nagłówek dla niezalogowanych": "Heading for signed-out visitors",
  "Nagłówek zainteresowań": "Interests heading",
  "Treść (HTML)": "Content (HTML)",
  "Treść zgody (RODO)": "Consent text (GDPR)",
  "Tekst zgody / stopka": "Consent text / footer",
  "Tekst linku (opcjonalny)": "Link text (optional)",
  "Własny tekst": "Custom text",
  "Własny tekst (jeśli wybrane)": "Custom text (when selected)",
  "Podpis (opcjonalny)": "Caption (optional)",
  "Komunikat po wysłaniu": "Message after submitting",
  "Komunikat po zapisaniu": "Message after signing up",
  "Komunikat sukcesu": "Success message",
  "Korzyść 1": "Benefit 1",
  "Korzyść 2": "Benefit 2",
  "Korzyść 3": "Benefit 3",
  Alt: "Alt",
  Slug: "Slug",
  Rola: "Role",
  Bio: "Bio",
  Zdjęcie: "Photo",
  Stanowisko: "Job title",
  "Pozycja / stanowisko": "Position / job title",
  "Imię i nazwisko": "Full name",
  "Firma / redakcja": "Company / newsroom",
  "Strona www": "Website",
  Telefon: "Phone",
  Waluta: "Currency",
  Prefiks: "Prefix",
  Sufiks: "Suffix",
  Separator: "Separator",
  "Separator tysięcy": "Thousands separator",
  "Wersja (np. 1.0)": "Version (e.g. 1.0)",
  "Aktualizacja (np. 2026-07)": "Updated (e.g. 2026-07)",
  "Data aktualizacji": "Update date",
  "Data publikacji": "Publication date",
  "Dzisiejsza data": "Today's date",
  "Bieżący rok": "Current year",
  "Czas czytania": "Reading time",
  Wyświetlenia: "Views",
  Autor: "Author",
  "Nazwa kategorii": "Category name",
  "Nazwa tagu": "Tag name",
  "Nazwa ikony": "Icon name",
  "Ikona (Lucide)": "Icon (Lucide)",
  "Ikona (opcjonalna)": "Icon (optional)",
  "Ikona (dla wariantu z ikoną)": "Icon (for the icon variant)",
  "Ikona nagłówka": "Heading icon",
  Ikonka: "Icon",
  Głos: "Voice",
  "Limit wyników": "Result limit",
  Sortowanie: "Sorting",
  Wariant: "Variant",
  "Wariant przycisku": "Button variant",
  Szukaj: "Search",
  Pokaż: "Show",
  Ukryj: "Hide",
  Tak: "Yes",
  Nie: "No",
  Brak: "None",
  Kolor: "Colour",
  Rozmiar: "Size",
  Szerokość: "Width",
  Wysokość: "Height",
  Odstęp: "Spacing",
  Zaokrąglenie: "Corner radius",
  Przyciemnienie: "Dimming",
  Rozjaśnienie: "Lightening",
  Ramka: "Border",
  Proporcje: "Aspect ratio",
  Dopasowanie: "Object fit",
  Wyrównanie: "Alignment",
  Kolumny: "Columns",
  Siatka: "Grid",
  Lista: "List",
  Karta: "Card",
  Pętla: "Loop",
  Świat: "World",
  Europa: "Europe",

  // --------------------------------------------------------------- structure
  "Tag (SEO)": "Tag (SEO)",
  "Rozmiar (preset)": "Size (preset)",
  "Rozmiar (px)": "Size (px)",
  // Karuzela okrężna - geometria elipsy i akcent aktywnej karty.
  "Promień poziomy (px)": "Horizontal radius (px)",
  "Promień pionowy (px)": "Vertical radius (px)",
  "Ramka aktywnej karty, licznik i kropki. Puste = kolor marki.":
    "Active card border, counter and dots. Empty = brand colour.",
  "Rozmiar tytułu (px)": "Title size (px)",
  "Rozmiar podtytułu (px)": "Subtitle size (px)",
  "Rozmiar opisu (px)": "Description size (px)",
  "Rozmiar opisu / podtytułu (px)": "Description / subtitle size (px)",
  "Rozmiar tekstu (px)": "Text size (px)",
  "Rozmiar etykiety (px)": "Label size (px)",
  "Rozmiar etykiet (px)": "Label size (px)",
  "Rozmiar etykiet pól (px)": "Field label size (px)",
  "Rozmiar ikony (px)": "Icon size (px)",
  "Rozmiar liczby (px)": "Number size (px)",
  "Rozmiar przycisku (px)": "Button size (px)",
  "Rozmiar przycisku": "Button size",
  "Rozmiar bulletpointów (px)": "Bullet point size (px)",
  "Rozmiar placeholderów / pól (px)": "Placeholder / field size (px)",
  "Rozmiar zgód / newsletter (px)": "Consent / newsletter size (px)",
  "Rozmiar zgód / stopki (px)": "Consent / footer size (px)",
  "Grubość tytułu": "Title weight",
  "Grubość podtytułu": "Subtitle weight",
  "Grubość / wysokość (px)": "Thickness / height (px)",
  "Szerokość (%)": "Width (%)",
  "Wysokość (px)": "Height (px)",
  "Wysokość - desktop (px)": "Height - desktop (px)",
  "Wysokość - tablet (px, 0 = dziedziczy)": "Height - tablet (px, 0 = inherit)",
  "Wysokość - mobile (px, 0 = dziedziczy)": "Height - mobile (px, 0 = inherit)",
  "Wysokość pola (px)": "Field height (px)",
  "Maks. szerokość karty (px)": "Max card width (px)",
  "Zaokrąglenie (px)": "Corner radius (px)",
  "Padding wewnętrzny (px)": "Inner padding (px)",
  "Odstęp między ikonami (px)": "Gap between icons (px)",
  "Kolumny (siatka)": "Columns (grid)",
  "Kolumny tekstu": "Text columns",
  Inicjał: "Drop cap",
  "Proporcje kafla": "Tile aspect ratio",
  "Czas animacji (ms)": "Animation duration (ms)",
  "Tempo (sekundy na pętlę)": "Speed (seconds per loop)",
  "Animacja wejścia": "Entrance animation",
  "Animacja ciągła": "Continuous animation",
  "Animacja obrazka (hover)": "Image animation (hover)",
  "Adaptacja dark / light": "Dark / light adaptation",
  Autoodtwarzanie: "Autoplay",
  "Pauza po najechaniu": "Pause on hover",
  // trending-now (schemas.ts) - bramka labelsEn.test wymusza komplet tłumaczeń.
  "Co ile sekund zmieniać wpis": "Seconds between rotations",
  "Autor (awatar + imię)": "Author (avatar + name)",
  Lightbox: "Lightbox",
  "Sticky (desktop)": "Sticky (desktop)",

  // ------------------------------------------------------------------ colors
  "Kolor tła": "Background colour",
  "Kolor tła (opcjonalny)": "Background colour (optional)",
  "Kolor tekstu": "Text colour",
  "Kolor obramowania": "Border colour",
  "Kolor obrysu": "Outline colour",
  "Kolor podkreślenia": "Underline colour",
  "Kolor akcentu (opcjonalny)": "Accent colour (optional)",
  "Kolor akcentu (pozycja)": "Accent colour (item)",
  "Kolor ikony": "Icon colour",
  "Kolor ikony ✓ (bulletpointy)": "✓ icon colour (bullet points)",
  "Kolor liczby (hex)": "Number colour (hex)",
  "Tło ikony": "Icon background",
  "Tło (dark mode)": "Background (dark mode)",
  "Tło (light mode)": "Background (light mode)",
  "Tło - kolor 1": "Background - colour 1",
  "Tło - kolor 2": "Background - colour 2",
  "Gradient - kolor 1": "Gradient - colour 1",
  "Gradient - kolor 2": "Gradient - colour 2",
  "Gradient - kąt (°)": "Gradient - angle (°)",
  "Przycisk - tekst": "Button - text",
  "Przycisk - tło": "Button - background",
  "Własny kolor tła": "Custom background colour",
  "Własny kolor": "Custom colour",
  "Grupy węzłów (kolory)": "Node groups (colours)",
  "Podświetlone kraje (ISO-2)": "Highlighted countries (ISO-2)",
  "Przyciemnienie obrazu tła (%)": "Background image dimming (%)",
  "Przyciemnienie dołu karty (0–1)": "Card bottom dimming (0–1)",
  "Wyróżniona kolumna (0 = pierwsza)": "Highlighted column (0 = first)",

  // ------------------------------------------------------------ media / URLs
  "Obraz tła (desktop)": "Background image (desktop)",
  "Obraz tła (mobile)": "Background image (mobile)",
  "Obrazki (po jednym URL na linię)": "Images (one URL per line)",
  "URL obrazka": "Image URL",
  "URL obrazka (dark mode)": "Image URL (dark mode)",
  "URL linku (opcjonalny)": "Link URL (optional)",
  "URL (YouTube lub MP4)": "URL (YouTube or MP4)",
  "URL logowania": "Sign-in URL",
  "URL do rejestracji": "Sign-up URL",
  "URL do odzyskiwania hasła": "Password recovery URL",
  "URL powrotu do logowania": "Back-to-sign-in URL",
  "Docelowy URL": "Target URL",
  Link: "Link",
  "Link (opcjonalny)": "Link (optional)",
  "Link (docelowy URL)": "Link (target URL)",
  "Link CTA": "CTA link",
  "Otwórz w": "Open in",
  "Otwórz link w": "Open the link in",
  "Avatar (URL)": "Avatar (URL)",
  "Adres / zapytanie": "Address / query",
  "Facebook URL": "Facebook URL",
  "Instagram URL": "Instagram URL",
  "LinkedIn URL": "LinkedIn URL",
  "YouTube URL": "YouTube URL",
  "Spotify URL": "Spotify URL",

  // --------------------------------------------------------- forms & consent
  "Pole: E-mail": "Field: Email",
  "Pole: Imię": "Field: First name",
  "Pole: Imię (rozdzielone)": "Field: First name (split)",
  "Pole: Nazwisko": "Field: Last name",
  "Pole: Firma": "Field: Company",
  "Pole: Kraj": "Field: Country",
  "Pole: Telefon": "Field: Phone",
  "Pole: Temat": "Field: Subject",
  "Pole: Wiadomość": "Field: Message",
  "Pole: Stanowisko (LinkedIn)": "Field: Job title (LinkedIn)",
  "Pole: Profil LinkedIn": "Field: LinkedIn profile",
  "Pole: Zapis do newslettera": "Field: Newsletter opt-in",
  "Pole wyszukiwania": "Search field",
  Placeholder: "Placeholder",
  "Placeholder pola email": "Email field placeholder",
  "Placeholder: E-mail": "Placeholder: Email",
  "Placeholder: Imię": "Placeholder: First name",
  "Placeholder: Imię (pojedyncze pole)": "Placeholder: First name (single field)",
  "Placeholder: Nazwisko": "Placeholder: Last name",
  "Placeholder: Firma": "Placeholder: Company",
  "Placeholder: Kraj": "Placeholder: Country",
  "Placeholder: Telefon": "Placeholder: Phone",
  "Placeholder: Stanowisko": "Placeholder: Job title",
  "Placeholder: LinkedIn URL": "Placeholder: LinkedIn URL",
  "E-mail - wymagany?": "Email - required?",
  "E-mail: wymagany?": "Email: required?",
  "E-mail odbiorcy (override)": "Recipient email (override)",
  "Imię: wymagane?": "First name: required?",
  "Nazwisko: wymagane?": "Last name: required?",
  "Firma: wymagana?": "Company: required?",
  "Kraj: wymagany?": "Country: required?",
  "Telefon: wymagany?": "Phone: required?",
  "Temat: wymagany?": "Subject: required?",
  "Wiadomość: wymagana?": "Message: required?",
  "Stanowisko: wymagane?": "Job title: required?",
  "LinkedIn: wymagany?": "LinkedIn: required?",
  "Zainteresowania: wymagane?": "Interests: required?",
  "Zainteresowania: sposób wyboru": "Interests: selection mode",
  "Wymagaj zgody (RODO)": "Require consent (GDPR)",
  "Wymagaj zgody RODO?": "Require GDPR consent?",
  "Dodatkowe pola (JSON, po jednym obiekcie na linię)": "Extra fields (JSON, one object per line)",
  "Po zalogowaniu przekieruj do": "After sign-in redirect to",
  "Po rejestracji przekieruj do": "After sign-up redirect to",
  "Po zapisaniu przekieruj do": "After subscribing redirect to",
  "Pokaż link zapomniałem hasła?": 'Show the "forgot password" link?',
  "Pokaż link załóż konto?": 'Show the "create an account" link?',
  "Pokaż przycisk pokaż hasło?": 'Show the "reveal password" button?',
  "Pokaż logowanie Google?": "Show Google sign-in?",
  "Pokaż rejestrację Google?": "Show Google sign-up?",
  "Pokaż zapis do newslettera?": "Show the newsletter opt-in?",

  // ------------------------------------------------------------- visibility
  "Widoczność (dla kogo)": "Visibility (audience)",
  "Tylko zalogowani (zalecane)": "Signed-in only (recommended)",
  "Tylko niezalogowani": "Signed-out only",
  "Wszyscy (goście widzą generyczny nagłówek)": "Everyone (guests see a generic heading)",
  "Pokaż nagłówek": "Show the heading",
  "Pokaż kicker": "Show the kicker",
  "Na telefonie zawsze jedna kolumna, od tabletu dwie, wybrana liczba od dużego ekranu.":
    "Always one column on phones, two from tablet up, the selected number on large screens.",
  "Pokaż opis (zajawkę)": "Show the description (excerpt)",
  "Pokaż odtwarzacz": "Show the player",
  "Pokaż wybór zainteresowań": "Show the interest picker",
  "Pokaż liczbę darczyńców": "Show the number of donors",
  "Pokaż sumę miesięczną": "Show the monthly total",
  "Pokaż ostatnie kwoty (anonimowo)": "Show recent amounts (anonymised)",
  "Nie powtarzaj wpisów": "Do not repeat posts",
  "Pomiń wpisy widoczne w innych widgetach": "Skip posts shown in other widgets",
  "Puste platformy": "Empty platforms",
  "Czy pokazywać ikony bez linku.": "Whether to show icons that have no link.",

  // -------------------------------------------------------------- data viz
  "Rodzaj wykresu": "Chart type",
  "Źródło danych": "Data source",
  "Źródło danych (podpis)": "Data source (caption)",
  "Źródło tekstu": "Text source",
  "Dane per kraj": "Per-country data",
  "Jednostka (np. %, mld EUR)": "Unit (e.g. %, EUR bn)",
  "Jednostka (np. %, mln)": "Unit (e.g. %, m)",
  "Jednostka (np. /100, %)": "Unit (e.g. /100, %)",
  "Jednostka (np. mld m³)": "Unit (e.g. bn m³)",
  "Wartość (np. 72,4)": "Value (e.g. 72.4)",
  "Wartość docelowa": "Target value",
  "Wartość początkowa": "Start value",
  "Zmiana (np. +5,1)": "Change (e.g. +5.1)",
  "Opis zmiany (np. r/r)": "Change description (e.g. YoY)",
  "Ton zmiany (kolor)": "Change tone (colour)",
  "Strzałka zmiany": "Change arrow",
  "Sparkline (opcjonalny)": "Sparkline (optional)",
  "Elementy ryzyka": "Risk items",
  "Powiązania (krawędzie)": "Relationships (edges)",
  "Markery (węzły)": "Markers (nodes)",
  "Paski w komórkach": "In-cell bars",
  "Skumulowany (stacked)": "Stacked",
  "Wyniki na żywo": "Live results",
  "Liczba wpisów": "Number of posts",
  "Liczba odcinków": "Number of episodes",
  "Liczba historii": "Number of stories",
  "Wyróżniony odcinek": "Featured episode",
  "Kategorie (slugi, po przecinku)": "Categories (slugs, comma separated)",
  "Pozycje (opcjonalne)": "Items (optional)",
  "Cel zbiórki (grosze)": "Fundraising goal (minor units)",
  "Ocena (0–5)": "Rating (0–5)",
  "Domyślnie rozwinięta": "Expanded by default",
  "Pozycja ikony": "Icon position",
  "Pozycja przycisku": "Button position",
  "Wyrównanie przycisku": "Button alignment",
  "Ikony w rzędzie": "Icons per row",
  "Spis treści": "Table of contents",
  CTA: "CTA",
  "CTA Facebook": "Facebook CTA",
  "CTA Instagram": "Instagram CTA",
  "CTA LinkedIn": "LinkedIn CTA",
  "CTA X": "X CTA",
  "CTA YouTube": "YouTube CTA",
  "CTA Spotify": "Spotify CTA",
  "CTA Newsletter": "Newsletter CTA",
  "Newsletter URL": "Newsletter URL",
  "Wiersz newslettera": "Newsletter row",
  "Newsletter renderuje się jak pozostałe platformy (ikona + nazwa + CTA).":
    "The newsletter renders like every other platform (icon + name + CTA).",

  "Opinia / Cytat": "Testimonial / quote",
  "Klucz menu": "Menu key",

  // ------------------------------------------------------------------ hints
  "0 = bez celu (dla wariantów progress/thermometer wymagane >0).":
    "0 = no goal (the progress / thermometer variants require > 0).",
  "0 oznacza użycie wartości z desktopu.": "0 means the desktop value is used.",
  "Bez tła, hairline dashed border, tekstowe aktywne z lewą kreską.":
    "No background, hairline dashed border, text-only active state with a left rule.",
  "Domyślnie /support (strona darowizn).": "Defaults to /support (the donations page).",
  "Domyślnie 40 px.": "Defaults to 40 px.",

  "Domyślnie widget wyświetla się wyłącznie zalogowanym użytkownikom - rekomendacje bazują na ich zainteresowaniach, obserwacjach i historii czytania.":
    "By default the widget is shown only to signed-in users - recommendations are based on their interests, follows and reading history.",
  "Działa identycznie na desktopie, tablecie i mobile.":
    "Behaves identically on desktop, tablet and mobile.",
  "Efekt po najechaniu kursorem na obrazek.": "Effect applied when hovering the image.",
  "Im większa wartość, tym wolniejsze przewijanie.": "The higher the value, the slower the scroll.",
  "Indeks kolumny do podświetlenia akcentem marki. Puste = brak.":
    "Index of the column highlighted with the brand accent. Empty = none.",
  "Jawny kolor ma pierwszeństwo przed adaptacją dark / light.":
    "An explicit color takes precedence over the dark / light adaptation.",
  "Dotyczy kolorów dziedziczonych - nie nadpisuje jawnego wyboru w polu „Kolory ikon”.":
    "Applies to inherited colors - it does not override an explicit choice in the Icon colors field.",
  "Klucz menu zdefiniowanego w Wygląd → Menu (domyślnie: main).":
    "Key of a menu defined under Appearance → Menu (default: main).",
  "Kliknięcie zdjęcia otwiera je na pełnym ekranie (Esc zamyka, strzałki przewijają).":
    "Clicking a photo opens it full screen (Esc closes, arrow keys navigate).",
  "Kody ISO-2 rozdzielone przecinkiem lub średnikiem.":
    "ISO-2 codes separated by a comma or a semicolon.",
  "Lista renderuje każdą platformę jako osobny wiersz z etykietą i CTA (Like / Follow / Subscribe).":
    "The list renders every platform as its own row with a label and a CTA (Like / Follow / Subscribe).",
  "Lista tematów do pokazania (po jednym slug na linię; puste = wszystkie z katalogu)":
    "Topics to display (one slug per line; empty = all from the catalogue)",
  "Możesz użyć składni [tekst linku](https://adres.pl) aby wstawić inline hiperłącze.":
    "You can use the [link text](https://example.com) syntax to insert an inline hyperlink.",
  "Nazwa ikony Lucide. Domyślnie: Flame.": "Lucide icon name. Defaults to: Flame.",
  "Nazwa ikony Lucide. Domyślnie: Mail.": "Lucide icon name. Defaults to: Mail.",
  "Nazwa ikony Lucide. Zostaw puste, aby ukryć.": "Lucide icon name. Leave empty to hide it.",
  "Odległość między poszczególnymi ikonami.": "Distance between individual icons.",
  "Odsunięty od krawędzi, mocno zaokrąglony, miękki cień.":
    "Detached from the edge, heavily rounded, soft shadow.",
  "Osobna grafika dla trybu ciemnego. Pozostaw puste, aby użyć tej samej.":
    "A separate image for dark mode. Leave empty to reuse the same one.",
  "Pełne tło karty, ostre rogi pozycji menu.":
    "Solid card background, square corners on menu items.",
  "Pokazywana w zwiniętym sidebarze i w stylu rail.":
    "Shown in the collapsed sidebar and in the rail style.",
  "Pokazywane w szerokim sidebarze dla admina i globalnego układu.":
    "Shown in the wide sidebar for the admin and the global layout.",
  "Podział tekstu na kolumny (CSS multi-column).":
    "Splits the text into columns (CSS multi-column).",
  "Pozostaw puste = wszystkie.": "Leave empty = all.",
  "Pozostaw puste, aby użyć koloru motywu (border).":
    "Leave empty to use the theme colour (border).",
  "Puste = kolor brand.": "Empty = brand colour.",
  "Puste = pełna szerokość kolumny. Ustaw, aby ujednolicić rozmiar karty w układach o różnej liczbie kolumn (np. 300 px = ten sam rozmiar w 3 i 4 kolumnach).":
    "Empty = full column width. Set it to keep the card the same size across layouts with a different number of columns (e.g. 300 px = identical size in 3 and 4 columns).",
  "Puste = przezroczyste. Możesz wpisać var(--card) lub dowolny kolor.":
    "Empty = transparent. You can enter var(--card) or any colour.",
  "Półprzezroczyste tło, backdrop blur, gradientowe items.":
    "Semi-transparent background, backdrop blur, gradient items.",
  "Rekomendowane 128x128 px (PNG/SVG, kwadrat)": "Recommended 128x128 px (PNG/SVG, square)",
  "Rekomendowane 1600x900 px (lub 2400x1200 dla hero)":
    "Recommended 1600x900 px (or 2400x1200 for a hero)",
  "Rekomendowane 800x1000 px (portret)": "Recommended 800x1000 px (portrait)",
  "Szerokość linii względem kontenera (10-100%).":
    "Line width relative to the container (10-100%).",
  "Token {name} jest automatycznie odmieniany do wołacza w PL (np. Igor → Igorze). Możesz też użyć {name.nominative}.":
    "The {name} token is automatically inflected into the Polish vocative (e.g. Igor → Igorze). You can also use {name.nominative}.",
  "Tylko dla wariantu „Siatka”.": "Only for the “Grid” variant.",
  "Wgraj lub wybierz z biblioteki mediów.": "Upload or pick from the media library.",
  "Wgraj plik z dysku (trafi do biblioteki mediów) albo wklej pełny URL. Puste = użyty zostanie gradient fallback.":
    "Upload a file from disk (it lands in the media library) or paste a full URL. Empty = the gradient fallback is used.",
  "Widoczny gdy odbiorca nie jest zalogowany.": "Visible when the visitor is not signed in.",
  "Wklej URL lub wgraj plik z dysku.": "Paste a URL or upload a file from disk.",
  "Wpisz dokładny rozmiar w pikselach (np. 28, 32). Nadpisuje preset i działa identycznie na każdym urządzeniu.":
    "Enter an exact pixel size (e.g. 28, 32). It overrides the preset and behaves identically on every device.",
  "Wyklucza wpisy już wyrenderowane przez wcześniejsze widgety na tej stronie.":
    "Excludes posts already rendered by earlier widgets on this page.",
  "Wymuszony ciemny kontrast w obu trybach + akcent brand.":
    "Forced dark contrast in both modes + brand accent.",
  "Wyświetla wyłącznie kwoty (bez adresów e-mail i wiadomości).":
    "Shows amounts only (no email addresses or messages).",
  "Wąski 56px pasek z samymi ikonami.": "A narrow 56 px icon-only rail.",
  "Zalecane przy układzie sidebarowym / w wąskiej kolumnie bocznej.":
    "Recommended for sidebar layouts / narrow side columns.",
  "Zostaw puste dla przezroczystego odstępu.": "Leave empty for a transparent spacer.",
  "Zostaw puste, aby TOC zaczytał się automatycznie z nagłówków H2/H3 strony. Ręcznie: jedna pozycja per linia. Format: `Tekst` (H2) lub `-- Tekst` (H3). Opcjonalny id: `#moj-id | Tekst`.":
    "Leave empty to let the TOC read the page's H2/H3 headings automatically. Manual: one item per line. Format: `Text` (H2) or `-- Text` (H3). Optional id: `#my-id | Text`.",
  "Grafika: alt (PL) - opis dla dostępności / SEO":
    "Image: alt (PL) - accessibility / SEO description",
  "Grafika: alt (EN) - accessibility / SEO description":
    "Image: alt (EN) - accessibility / SEO description",
  "Grafika: dopasowanie w kadrze (object-fit)": "Image: fit within the frame (object-fit)",
  "Grafika: focal point / object-position (np. center, top, 50% 30%)":
    "Image: focal point / object-position (e.g. center, top, 50% 30%)",
  "Grafika: gradient/kolor fallback (CSS `background`, np. linear-gradient(...))":
    "Image: gradient / colour fallback (CSS `background`, e.g. linear-gradient(...))",
  "Grafika: obraz (wgraj plik lub wklej URL)": "Image: file (upload or paste a URL)",
  "Grafika: proporcje kadru (aspect-ratio)": "Image: frame proportions (aspect-ratio)",
  "Grafika: przyciemnienie (0-100%)": "Image: dimming (0-100%)",

  // -------------------------------------------------------- option labels
  domyślny: "default",
  domyślna: "default",
  "domyślne (dziedziczone)": "default (inherited)",
  brak: "none",
  "brak (kant)": "none (sharp)",
  tak: "yes",
  nie: "no",
  "tak (min. 1)": "yes (min. 1)",
  "tak - do 5 ostatnich": "yes - up to the last 5",
  włączony: "on",
  włączona: "on",
  włączone: "on",
  "włączone (wymaga mute)": "on (requires mute)",
  wyłączony: "off",
  wyłączona: "off",
  wyłączone: "off",
  Wyłączone: "Disabled",
  widoczne: "visible",
  ukryte: "hidden",
  ukryj: "hide",
  "ukryj (tylko z linkiem)": "hide (only when linked)",
  pokaż: "show",
  "pokaż wyszarzone": "show greyed out",
  więcej: "more",
  mały: "small",
  małe: "small",
  średni: "medium",
  średnie: "medium",
  duży: "large",
  duże: "large",
  "M (domyślny)": "M (default)",
  lewo: "left",
  środek: "center",
  Środek: "Center",
  lewa: "left",
  prawa: "right",
  Lewa: "Left",
  Prawa: "Right",
  Lewo: "Left",
  Prawo: "Right",
  "do lewej": "to the left",
  "do prawej": "to the right",
  "po lewej": "on the left",
  "po prawej": "on the right",
  "obok pól (po prawej)": "next to the fields (on the right)",
  "pod formularzem": "below the form",
  wycentrowany: "centered",
  wyśrodkowane: "centered",
  "w górę": "up",
  "w dół": "down",
  "nowej karcie": "a new tab",
  "tym samym oknie": "the same window",
  "pełna szerokość": "full width",
  pełny: "full",
  "pełne (koło)": "full (circle)",
  kwadrat: "square",
  Kwadrat: "Square",
  okrąg: "circle",
  Okrąg: "Circle",
  kółko: "circle",
  pigułka: "pill",
  zaokrąglony: "rounded",
  obrysowany: "outlined",
  obrysowana: "outlined",
  wypełniony: "filled",
  podkreślony: "underlined",
  podkreślenie: "underline",
  Podkreślenie: "Underline",
  "Podwójne podkreślenie": "Double underline",
  "Odręczne podkreślenie": "Hand-drawn underline",
  Przekreślenie: "Strikethrough",
  "Podwójne przekreślenie": "Double strikethrough",
  Ukośny: "Diagonal",
  Zygzak: "Zigzag",
  Falisty: "Wavy",
  fala: "wave",
  Płaski: "Flat",
  "Lekkie przechylenie": "Slight tilt",
  linia: "line",
  "tylko odstęp (bez linii)": "spacing only (no line)",
  kropkowana: "dotted",
  przerywana: "dashed",
  podwójna: "double",
  klasyczny: "classic",
  kompaktowy: "compact",
  minimalny: "minimal",
  rozsunięte: "spaced out",
  karta: "card",
  "karta z cieniem": "card with a shadow",
  "karta z formularzem": "card with a form",
  "karta boczna (kompakt)": "side card (compact)",
  kolumny: "columns",
  siatka: "grid",
  karuzela: "carousel",
  kołowy: "pie",
  "pierścień (donut)": "ring (donut)",
  "słupki poziome": "horizontal bars",
  "pole (area)": "area",
  "termometr pionowy": "vertical thermometer",
  "pasek celu (goal bar)": "goal bar",
  "pasek statystyk (3 pola)": "stats bar (3 fields)",
  "hero (duża liczba + CTA)": "hero (large number + CTA)",
  "wąski pasek": "narrow bar",
  "wąski pasek inline": "narrow inline bar",
  "inline (email + przycisk)": "inline (email + button)",
  "split (dwa rzędy)": "split (two rows)",
  "split (lewo: korzyści, prawo: formularz)": "split (left: benefits, right: form)",
  "split z grafiką (lewo: obraz + korzyści, prawo: formularz)":
    "split with an image (left: image + benefits, right: form)",
  "z cieniem": "with a shadow",
  "z ikoną na środku": "with a centred icon",
  "z dużym cudzysłowem": "with a large quotation mark",
  "sama ikona": "icon only",
  "ikona + tekst": "icon + text",
  tekst: "text",
  obrót: "rotation",
  pulsowanie: "pulse",
  skakanie: "bounce",
  "zoom przy hover": "zoom on hover",
  "Zoom in (przybliżenie)": "Zoom in",
  "Zoom out (oddalenie)": "Zoom out",
  "kolor brand": "brand colour",
  własne: "custom",
  "własny kolor": "custom colour",
  "oficjalne (marka)": "official (brand)",
  "oficjalne kolory marek": "official brand colours",
  "kontrastowe (fg/bg)": "contrasting (fg/bg)",
  "delikatne (muted)": "subtle (muted)",
  "jasne (białe)": "light (white)",
  "ciemne (czarne)": "dark (black)",
  "wymuś jasny styl": "force the light style",
  "wymuś ciemny styl": "force the dark style",
  wersaliki: "uppercase",
  "chipsy (widoczne wszystkie)": "chips (all visible)",
  "droplist (multiselect)": "dropdown (multi-select)",
  "przycisk primary": "primary button",
  "przycisk obrysowany": "outlined button",
  polaroid: "polaroid",
  "kolejność wpisów": "post order",
  "rok malejąco": "year descending",
  "negatywny (czerwony)": "negative (red)",
  "pozytywny (zielony)": "positive (green)",
  neutralny: "neutral",
  automatyczna: "automatic",
  "automatyczna (dostosuj się)": "automatic (adapt)",
  "auto (dopasuj do kolumny obok)": "auto (match the adjacent column)",
  "contain - zmieść cały obraz (może zostać tło)":
    "contain - fit the whole image (background may show)",
  "cover - wypełnij kadr (może przyciąć)": "cover - fill the frame (may crop)",
  "opcjonalnie - pusty = używa głównej grafiki": "optional - empty = uses the main image",

  // ---------------------------------------------------------- aspect ratios
  "16:9 - baner poziomy": "16:9 - horizontal banner",
  "21:9 - ultrawide cinematic": "21:9 - ultrawide cinematic",
  "1:1 - kwadrat": "1:1 - square",
  "2:3 - plakat": "2:3 - poster",
  "3:2 - fotografia": "3:2 - photography",
  "3:4 - portret": "3:4 - portrait",
  "4:3 - klasyczny": "4:3 - classic",
  "4:5 - portret social": "4:5 - social portrait",
  "9:16 - pionowy / mobile story": "9:16 - vertical / mobile story",
  "9:16 (pion)": "9:16 (portrait)",
  "Pionowy 9:16": "Vertical 9:16",

  // -------------------------------------------------------- slider variants
  "Editorial Hero": "Editorial Hero",
  "Cinematic Overlay": "Cinematic Overlay",
  "Split Feature": "Split Feature",
  "Minimal + miniatury": "Minimal + thumbnails",
  "Karuzela kart (3-up)": "Card carousel (3-up)",
  "Karuzela logo (marquee)": "Logo carousel (marquee)",
  "Karuzela z paskiem postępu": "Progress carousel",
  "Karuzela okrężna": "Circular carousel",
  "Grid dwukolumnowy": "Two-column grid",
  "Lista pionowa (klasyczna)": "Vertical list (classic)",
  "Lista (ikona + nazwa + CTA)": "List (icon + name + CTA)",
  "Najnowsze / Latest": "Newest / Latest",

  // ------------------------------------------------- animated heading modes
  "Wyróżnione słowo": "Highlighted word",
  "Rotujące słowa": "Rotating words",
  "Hover - podkreślenie": "Hover - underline",
  "Hover - ramka (allsides)": "Hover - frame (all sides)",
  "Hover: rozwijana ze środka": "Hover: expands from the centre",
  "Hover: ze środka w 2 strony": "Hover: from the centre in both directions",
  "Hover: od krawędzi do środka": "Hover: from the edges to the centre",
  "Hover: dwa segmenty": "Hover: two segments",
  "Hover: punkt + linia": "Hover: dot + line",
  "Hover: skok w bok": "Hover: sideways hop",
  "Hover: sprężyna": "Hover: spring",
  "Hover: snap środek": "Hover: snap to centre",
  "Allsides: rogi po przekątnej": "All sides: diagonal corners",
  "Allsides: z dwóch rogów": "All sides: from two corners",
  "Allsides: ze środka boków": "All sides: from the middle of each side",
  "Allsides: skręt naprzemienny": "All sides: alternating twist",
  "Allsides: 4 rogi (krótkie)": "All sides: 4 corners (short)",
  "Allsides: dół + prawo": "All sides: bottom + right",
  "Allsides: rogi-segmenty": "All sides: corner segments",
  "Allsides: spiralnie": "All sides: spiral",
  "Squiggle (hero)": "Squiggle (hero)",
  "Caret (trójkąt wypełniony)": "Caret (filled triangle)",
  "Chevron (klasyczny V)": "Chevron (classic V)",
  "Chevron pogrubiony": "Bold chevron",
  "Podwójny chevron »": "Double chevron »",
  "Angle (cienki kąt)": "Angle (thin angle)",
  "Strzałka (z trzonem)": "Arrow (with a shaft)",
  "Strzałka długa": "Long arrow",
  "Strzałka z ogonem": "Arrow with a tail",

  // --------------------------------------------------- section label variants
  "01 - Pionowy pasek": "01 - Vertical bar",
  "02 - Lewa krawędź": "02 - Left edge",
  "04 - Narożniki": "04 - Corners",
  "05 - Tylko tekst": "05 - Text only",
  "06 - Etykieta pełna": "06 - Full label",
  "07 - Wycentrowany z linią (np. Poznaj nasze raporty)":
    "07 - Centred with a rule (e.g. Explore our reports)",
  "08 - Wycentrowany z krótkimi liniami (np. Materiały partnerów)":
    "08 - Centred with short rules (e.g. Partner materials)",
  "09 - Pełny pasek (np. Najnowszy raport)": "09 - Full bar (e.g. Latest report)",
  "10 - Wycentrowany z podkreśleniem (np. Poznaj nasze raporty)":
    "10 - Centred with an underline (e.g. Explore our reports)",
  "11 - Wstęga ze spadem i linią (np. Najnowszy raport)":
    "11 - Ribbon with a bleed and a rule (e.g. Latest report)",
  "12 - Subtelne linie (np. Wywiady | Podcasty)": "12 - Subtle rules (e.g. Interviews | Podcasts)",
  "13 - Editorial Index (numer + tytuł, styl FT Lex)":
    "13 - Editorial Index (number + title, FT Lex style)",
  "14 - Double-Deck Masthead (kategoria nad tytułem)":
    "14 - Double-Deck Masthead (category above title)",
  "15 - Bracket Label (tytuł w nawiasach + linia)": "15 - Bracket Label (title in brackets + rule)",
  "16 - Kicker Tag (tag kategorii + linia do akcji)":
    "16 - Kicker Tag (category tag + rule to the action)",
  "17 - Stacked Serif Lede (tytuł + podtytuł)": "17 - Stacked Serif Lede (title + dek)",
  "18 - Dotted Leader (kropkowana linia do akcji)":
    "18 - Dotted Leader (dotted rule to the action)",
  "19 - Numbered Rail (duża cyfra w tle)": "19 - Numbered Rail (large background numeral)",
  "20 - Split Rule Duo (dwie etykiety z kreską)": "20 - Split Rule Duo (two labels with a divider)",
  "21 - Ticker Strip (pasek z pulsującą kropką)": "21 - Ticker Strip (bar with a pulsing dot)",
  "22 - Underline Sweep (animowane podkreślenie 2px)":
    "22 - Underline Sweep (animated 2px underline)",

  // ------------------------------------------------------- sidebar styles
  "Style 1 - Solid Classic": "Style 1 - Solid Classic",
  "Style 2 - Minimal Borderless": "Style 2 - Minimal Borderless",
  "Style 3 - Floating Card": "Style 3 - Floating Card",
  "Style 4 - Compact Icon Rail": "Style 4 - Compact Icon Rail",
  "Style 5 - Glass / Frosted": "Style 5 - Glass / Frosted",
  "Style 6 - Bold Dark": "Style 6 - Bold Dark",
  "Sidebar (kompaktowy)": "Sidebar (compact)",
  "Logo sidebaru - expanded": "Sidebar logo - expanded",
  "Ikona sidebaru - compact": "Sidebar icon - compact",

  // ------------------------------------------------------------ TTS voices
  "Multilingual v2 (PL/EN, najlepsza jakość)": "Multilingual v2 (PL/EN, best quality)",
  "Turbo v2.5 (szybszy)": "Turbo v2.5 (faster)",
  "Daniel (męski, EN)": "Daniel (male, EN)",
  "George (męski, EN)": "George (male, EN)",
  "Liam (męski, EN)": "Liam (male, EN)",
  "Jessica (kobiecy, EN)": "Jessica (female, EN)",
  "Laura (kobiecy, EN)": "Laura (female, EN)",
  "Lily (kobiecy, EN)": "Lily (female, EN)",
  "Matilda (kobiecy, EN)": "Matilda (female, EN)",
  "Sarah (kobiecy, EN)": "Sarah (female, EN)",

  // ------------------------------------------------------------ currencies
  "PLN (zł)": "PLN (zł)",
  "EUR (€)": "EUR (€)",

  // ----------------------------------------------------------- placeholders
  "/o-nas lub https://…": "/about or https://…",
  "/tracker lub https://…": "/tracker or https://…",
  "/kategoria/...": "/category/...",
  "#1877F2 lub var(--brand)": "#1877F2 or var(--brand)",
  "kontakt@firma.pl": "contact@company.com",
  "osoba@domena.pl": "person@domain.com",
  "polityka, gospodarka": "politics, economy",
  "np. RADA FUNDACJI": "e.g. BOARD OF TRUSTEES",
  "Star, Heart, Mail...": "Star, Heart, Mail...",
  "Star, Sparkles, ArrowRight…": "Star, Sparkles, ArrowRight…",
  "ChevronRight, ExternalLink…": "ChevronRight, ExternalLink…",
  "Flame, Zap, AlertTriangle…": "Flame, Zap, AlertTriangle…",
  "Mail, Send, BellRing, Inbox…": "Mail, Send, BellRing, Inbox…",

  // ---------------------------------------------------------- form controls
  link: "link",
  "Pole: Imię - widoczne?": "Field: First name - visible?",
  "Pole: Nazwisko - widoczne?": "Field: Last name - visible?",
  "Pole: Firma - widoczne?": "Field: Company - visible?",
  "Pole: Stanowisko - widoczne?": "Field: Job position - visible?",
  "Pole: LinkedIn - widoczne?": "Field: LinkedIn - visible?",
  "Pole: Telefon - widoczne?": "Field: Phone - visible?",
  "Pole: Powtórz hasło - widoczne?": "Field: Repeat password - visible?",
  "Pole: Powtórz nowe hasło - widoczne?": "Field: Repeat new password - visible?",
  "Pole: Zapamiętaj mnie - widoczne?": "Field: Remember me - visible?",
  "Imię - wymagane?": "First name - required?",
  "Firma - wymagane?": "Company - required?",
  "Powtórz hasło - wymagane?": "Repeat password - required?",
  "Powtórz nowe hasło - wymagane?": "Repeat new password - required?",
  "Minimalna długość hasła": "Minimum password length",
  "Etykieta: Imię": "Label: First name",
  "Etykieta: Nazwisko": "Label: Last name",
  "Etykieta: Firma": "Label: Company",
  "Etykieta: Stanowisko": "Label: Job position",
  "Etykieta: LinkedIn": "Label: LinkedIn",
  "Etykieta: E-mail": "Label: Email",
  "Etykieta: Telefon": "Label: Phone",
  "Etykieta: Temat": "Label: Subject",
  "Etykieta: Wiadomość": "Label: Message",
  "Etykieta: Hasło": "Label: Password",
  "Etykieta: Nowe hasło": "Label: New password",
  "Etykieta: Powtórz hasło": "Label: Repeat password",
  "Etykieta: Powtórz nowe hasło": "Label: Repeat new password",
  "Etykieta: Zapamiętaj mnie": "Label: Remember me",
  "Placeholder: Wiadomość": "Placeholder: Message",
  "Placeholder: Hasło": "Placeholder: Password",
  "Placeholder: Nowe hasło": "Placeholder: New password",
  "Placeholder: Powtórz hasło": "Placeholder: Repeat password",
  "Placeholder: Powtórz nowe hasło": "Placeholder: Repeat new password",
  'Ikona Lucide „Check" - zmienia się tylko kolor, kształt pozostaje bez zmian. Puste = brand (lub biały w wariancie split-image).':
    "The Lucide “Check” icon - only the colour changes, the shape stays the same. Empty = brand (or white in the split-image variant).",
  'Przykład: {"id":"branza","type":"select","labelPl":"Branża","labelEn":"Industry","required":true,"options":[{"value":"fintech","labelPl":"Fintech","labelEn":"Fintech"}]}':
    'Example: {"id":"branza","type":"select","labelPl":"Branża","labelEn":"Industry","required":true,"options":[{"value":"fintech","labelPl":"Fintech","labelEn":"Fintech"}]}',
  'Dla wariantu „tylko odstęp" wartość określa wysokość pustej przestrzeni.':
    "For the “spacing only” variant the value sets the height of the empty space.",

  // ------------------------------------------------------ data-format hints
  "Na wykresie kołowym wartość pojawia się pod udziałem procentowym, w wycinkach od 8% wzwyż.":
    "On a pie chart the value is placed under the percentage share, in slices of 8% and above.",
  'Arkusz otwiera się w popupie z podglądem wykresu. Format tekstowy: pierwszy wiersz "; Nazwa serii; Nazwa serii", kolejne "Kategoria; wartość; wartość" (separator ";", przecinek dziesiętny dozwolony).':
    'The spreadsheet opens in a popup with a live chart preview. Text format: first row "; Series name; Series name", then "Category; value; value" (";" separator, decimal comma allowed).',
  'Jeden kraj na wiersz: "KOD; wartość" (kod ISO-2, np. PL; 12,5).':
    'One country per row: "CODE; value" (ISO-2 code, e.g. PL; 12.5).',
  'Jeden wiersz na wydarzenie: "Data; Tytuł|Title; Opis|Description; slot(1-8, opc.)". Separator ";", tłumaczenie po "|".':
    'One row per event: "Date; Tytuł|Title; Opis|Description; slot (1-8, optional)". Separator ";", translation after "|".',
  'Jeden wiersz na przepływ: "Źródło|Source; Cel|Target; wartość". Wartości > 0.':
    'One row per flow: "Źródło|Source; Cel|Target; value". Values > 0.',
  'Nagłówek: "; Kolumna1|Column1; Kolumna2|Column2". Wiersze: "Wskaźnik [jedn.]|Indicator [unit]; v1; v2". Jednostka w "[...]".':
    'Header: "; Kolumna1|Column1; Kolumna2|Column2". Rows: "Wskaźnik [jedn.]|Indicator [unit]; v1; v2". The unit goes in "[...]".',
  'Jeden wiersz na ryzyko: "Nazwa|Name; prawdopodobieństwo 1-5; wpływ 1-5; opis|desc (opc.)".':
    'One row per risk: "Nazwa|Name; likelihood 1-5; impact 1-5; opis|desc (optional)".',
  'Jeden wiersz na powiązanie: "A|A_en; B|B_en; siła 1-5 (opc.); etykieta|label (opc.)".':
    'One row per relationship: "A|A_en; B|B_en; strength 1-5 (optional); etykieta|label (optional)".',
  'Jeden wiersz na przypisanie: "Węzeł|Node; grupa|group". Grupa = wspólny kolor.':
    'One row per assignment: "Węzeł|Node; grupa|group". A group = a shared colour.',
  'Jeden wiersz na korytarz: "Nazwa|Name; slot 1-8; lat,lon > lat,lon > ...". Węzły rozdziela ">".':
    'One row per corridor: "Nazwa|Name; slot 1-8; lat,lon > lat,lon > ...". Nodes are separated by ">".',
  'Jeden wiersz na marker: "lat,lon; Etykieta|Label".':
    'One row per marker: "lat,lon; Etykieta|Label".',
  'Jeden wiersz na źródło: "Typ|Type; Rok; Tytuł|Title; Wydawca|Publisher; URL".':
    'One row per source: "Typ|Type; Year; Tytuł|Title; Wydawca|Publisher; URL".',

  // --------------------------------------------------------- global colours
  Globalne: "Globals",
  Typografia: "Typography",
  "Nagłówek i nawigacja": "Header and navigation",
  "Formularze i przyciski": "Forms and buttons",
  "Widgety treści": "Content widgets",
  "Tła motywu": "Theme backgrounds",
  "Footnotes (Przypisy [fn])": "Footnotes ([fn])",
  "Sidebar Subtitle (Nawigacja / Podsekcja)": "Sidebar Subtitle (Navigation / Subsection)",
  "Główne tło strony (light / dark).": "The main page background (light / dark).",
  "Tło dla pojedynczych wpisów. Pusto = używa Body Background.":
    "Background for single posts. Empty = uses Body Background.",
  "Tło kart, popoverów, sidebarów - delikatnie ciemniejszy odcień tła.":
    "Background for cards, popovers and sidebars - a slightly darker shade of the base background.",
  "Tło drugorzędnych powierzchni (pola, hover stany).":
    "Background for secondary surfaces (fields, hover states).",
  "Wiodący ciemny kolor - tła sekcji nagłówkowych, gradienty, ORAZ kolor tekstu (nagłówki, akapity, tytuły kart) w trybie jasnym.":
    "The leading dark colour - header section backgrounds, gradients, AND the text colour (headings, paragraphs, card titles) in light mode.",
  "Linki, menu, akcenty kategorii, główne elementy interaktywne.":
    "Links, menus, category accents and the main interactive elements.",
  "Kolor highlight po najechaniu kursorem.": "Highlight colour on hover.",
  "Kolor ikon (search, theme, social, account) oraz linków menu w nagłówku.":
    "Colour of the header icons (search, theme, social, account) and menu links.",
  "Kolor ikon i linków menu po najechaniu.": "Colour of the icons and menu links on hover.",
  "Domyślny kolor ikon SVG (stan nieaktywny). Stosowany w treści strony.":
    "Default SVG icon colour (inactive state). Used inside page content.",
  "Kolor ikon SVG po najechaniu kursorem (bez kliknięcia).":
    "SVG icon colour on hover (without a click).",
  "Kolor ikon po najechaniu (bez kliknięcia) na nieaktywny element.":
    "Icon colour when hovering (without a click) an inactive element.",
  "Kolor wybranej ikony - po najechaniu i kliknięciu (zaznaczona/aktywna pozycja, np. bieżąca zakładka, włączony toggle).":
    "Colour of the selected icon - after hovering and clicking (a selected / active item, e.g. the current tab or an enabled toggle).",
  "Kolor podstawowego tekstu (akapity, listy).": "Colour of the body text (paragraphs, lists).",
  "Kolor tekstu drugorzędnego (podpisy, meta).": "Colour of secondary text (captions, meta).",
  "Kolor linków w treści.": "Colour of in-content links.",
  "Kolor linków po najechaniu.": "Link colour on hover.",
  "Kolor aktywnych linków (np. zaznaczona pozycja menu, bieżąca strona).":
    "Colour of active links (e.g. the selected menu item, the current page).",
  "Kolor nagłówków H1.": "Colour of H1 headings.",
  "Kolor nagłówków H2.": "Colour of H2 headings.",
  "Kolor nagłówków H3.": "Colour of H3 headings.",
  "Kolor nagłówków H4.": "Colour of H4 headings.",
  "Kolor nagłówków H5.": "Colour of H5 headings.",
  "Kolor nagłówków H6.": "Colour of H6 headings.",
  "Tło pól tekstowych.": "Background of text fields.",
  "Kolor obramowania.": "Border colour.",
  "Kolor wpisywanego tekstu.": "Colour of the text being typed.",
  "Kolor placeholdera.": "Placeholder colour.",
  "Tło pola po najechaniu.": "Field background on hover.",
  "Obramowanie pola po najechaniu.": "Field border on hover.",
  "Obramowanie i ring po fokusie.": "Border and focus ring.",
  "Tło przycisków.": "Button background.",
  "Kolor tekstu przycisków.": "Button text colour.",
  "Tło przycisków po najechaniu.": "Button background on hover.",
  "Tekst przycisków po najechaniu.": "Button text on hover.",
  "Tło sidebaru (panel boczny).": "Sidebar background (side panel).",
  "Kolor obramowania sidebaru i separatorów.": "Colour of the sidebar border and separators.",
  "Kolor tekstu/linków w sidebarze.": "Colour of sidebar text and links.",
  "Kolor ikon w sidebarze (stan nieaktywny / domyślny).":
    "Colour of the sidebar icons (inactive / default state).",
  "Kolor ikony aktualnie aktywnego elementu sidebaru.":
    "Colour of the icon on the currently active sidebar item.",
  "Tło przycisków / aktywnych elementów w sidebarze.":
    "Background of buttons / active items in the sidebar.",
  "Kolor tekstu przycisków / aktywnych elementów w sidebarze.":
    "Text colour of buttons / active items in the sidebar.",
  "Tło przycisków sidebaru po najechaniu.": "Sidebar button background on hover.",
  "Tekst przycisków sidebaru po najechaniu.": "Sidebar button text on hover.",
  "Tytuł sekcji w sidebarze (np. Menu, Ustawienia) - z osobnym kolorem dla trybu jasnego i ciemnego.":
    "Section title in the sidebar (e.g. Menu, Settings) - with a separate colour for light and dark mode.",
  "Podtytuł / nagłówek podsekcji w sidebarze (np. Nawigacja) - z osobnym kolorem dla trybu jasnego i ciemnego.":
    "Subtitle / subsection heading in the sidebar (e.g. Navigation) - with a separate colour for light and dark mode.",
  "Kolor ikony słońca.": "Sun icon colour.",
  "Tło ikony słońca.": "Sun icon background.",
  "Kolor ikony księżyca.": "Moon icon colour.",
  "Tło ikony księżyca.": "Moon icon background.",
  "Kolor ikony gwiazdki.": "Star icon colour.",
  "Tło dla gwiazdek recenzji.": "Background for review stars.",
  "Kolor zakładki po najechaniu.": "Bookmark colour on hover.",
  "Kolor licznika popularnych wpisów.": "Colour of the popular-posts counter.",
  "Kolor etykiety „sponsored”.": "Colour of the “sponsored” label.",
  "Kolor odznaki „zweryfikowany autor”.": "Colour of the “verified author” badge.",
  "Kolor ikon live-blogging.": "Colour of the live-blogging icons.",
  "Tło table-of-contents i share-bara.": "Background of the table of contents and the share bar.",
  "Kolor i typografia oznacznika przypisu w treści, np. [1].":
    "Colour and typography of the in-content footnote marker, e.g. [1].",
  'Nagłówek listy „Przypisy źródłowe:".': "The “Source notes:” list heading.",
  "Numerek [N] na początku każdego przypisu w liście.":
    "The [N] number at the start of every footnote in the list.",
  "Kolor i typografia tekstu poszczególnych przypisów.":
    "Colour and typography of each footnote's text.",
  "Kolor strzałki powrotu do odsyłacza.": "Colour of the arrow returning to the reference.",
  "Tło tooltipa pokazywanego po najechaniu na [N].":
    "Background of the tooltip shown when hovering [N].",
  "Kolor i typografia tekstu w tooltipie przypisu.":
    "Colour and typography of the text inside the footnote tooltip.",
  // ------------------------------------------- post-list / donations / events
  // Etykiety wyswietlania i autora dla post-listy zyja w `i18n-builder.ts`
  // (klucze `builder.postListEditor.*`), bo obsluguje je dedykowany
  // `PostListEditor`, a nie schemat sterowany danymi.
  "Tryb akcji": "Action mode",
  "bezpośredni link do zbiórki (zrzutka.pl)": "direct link to the fundraiser (zrzutka.pl)",
  "Wpłaty obsługuje zewnętrzna zbiórka (zrzutka.pl) - CTA nigdy nie otwiera checkoutu operatora płatności.":
    "Payments are handled by an external fundraiser (zrzutka.pl) - the CTA never opens the payment provider checkout.",
  "Dziękujemy za zakup": "Thank you for your purchase",
  "Dostęp jest już aktywny na Twoim koncie.": "Access is already active on your account.",
  "Data końca dostępu": "Access end date",
  "Dla subskrypcji pokazuje datę odnowienia, dla zakupu jednorazowego - datę wygaśnięcia.":
    "For subscriptions it shows the renewal date, for one-off purchases the expiry date.",
  "Przycisk otwiera portal operatora płatności (faktury, metoda płatności, anulowanie).":
    "The button opens the payment provider portal (invoices, payment method, cancellation).",
  "Link do historii zamówień": "Order history link",
  "Nota o bezpieczeństwie płatności": "Payment security note",
  "Kolor akcentu": "Accent colour",
  "Dodatkowy przycisk - adres": "Extra button - URL",
  "Dodatkowy przycisk - etykieta": "Extra button - label",
  "Nadchodzące wydarzenia": "Upcoming events",
  Nadchodzące: "Upcoming",
  "Okrągły stół": "Roundtable",
  "Liczba wydarzeń": "Number of events",
  "Kolumny (karty)": "Columns (cards)",
  "Tekst pustej listy": "Empty-state text",
  "Brak zaplanowanych wydarzeń.": "No scheduled events.",
  "Lista wydarzeń": "Event list",
  // Kluby dyskusyjne (spec §5.5)
  "Klub: karta": "Club: card",
  "Kluby: dyskusje": "Clubs: discussions",
  "Adres klubu": "Club address",
  "Fragment adresu po /club/. Pusty = widget nic nie pokazuje (i nie pyta bazy).":
    "The part of the address after /club/. Empty = the widget renders nothing (and does not query the database).",
  "Pokaż liczniki": "Show counters",
  "Liczba członków i wątków. Obie pochodzą z denormalizacji, więc nie kosztują dodatkowego zapytania.":
    "Member and topic counts. Both come from denormalised columns, so they cost no extra query.",
  Porządek: "Order",
  Gorące: "Hot",
  Najnowsze: "Newest",
  "Obszar polityki": "Policy area",
  "Zawężenie do jednego obszaru. Puste = wszystkie kluby, do których wołający ma dostęp.":
    "Narrow to one area. Empty = every club the reader has access to.",
  "Liczba wątków": "Number of topics",
  // ---------------------------------------- widgety dynamiczne (post-* / archiwum)
  "Widget czyta dane bieżącego wpisu. Poza stroną wpisu (np. w nagłówku lub stopce) pozostaje ukryty - nigdy nie pokazuje danych przykładowych.":
    "The widget reads the current post. Outside a post page (for example in the header or the footer) it stays hidden - it never shows sample data.",
  "Widget czyta dane archiwum (kategoria / tag). Poza stroną archiwum pozostaje ukryty.":
    "The widget reads archive data (category / tag). Outside an archive page it stays hidden.",
  "Linkuj do wpisu": "Link to the post",
  "Tekst zastępczy (gdy brak tytułu)": "Fallback text (when there is no title)",
  "Pokaż kategorię": "Show category",
  "Pokaż datę": "Show date",
  "Format daty": "Date format",
  skrócony: "short",
  względny: "relative",
  "Pokaż czas czytania": "Show reading time",
  "Pokaż liczbę odsłon": "Show view count",
  "Realna liczba odsłon wpisu, liczona po stronie serwera w obrębie tenanta. Kanwa buildera pokazuje wartość przykładową.":
    "The real number of post views, counted server-side within the tenant. The builder canvas shows a sample value.",
  pigułki: "pills",
  obrys: "outline",
  "Pokaż etykietę": "Show label",
  "Limit (0 = bez limitu)": "Limit (0 = no limit)",
  "w linii": "inline",
  wyśrodkowany: "centred",
  "Pokaż biogram": "Show bio",
  "Pokaż linki społecznościowe": "Show social links",
  "Pokaż stronę główną": "Show the home crumb",
  "Etykieta strony głównej": "Home crumb label",
  ukośnik: "slash",
  strzałka: "arrow",
  "Zaokrąglone rogi": "Rounded corners",
  "Pokaż podpis": "Show caption",
  "Podpis pod okładką": "Caption under the cover",
  "Maksymalna liczba znaków (0 = bez limitu)": "Maximum characters (0 = no limit)",
  "Pokaż opis": "Show description",
  "Pokaż liczbę wpisów": "Show post count",
  // ------------------------------- chrome: copyright / lang-switcher / search
  "Nazwa marki": "Brand name",
  "Wszelkie prawa zastrzeżone": "All rights reserved",
  "Pokaż rok": "Show the year",
  "Dopisuje znak © i bieżący rok przed nazwą marki.":
    "Prefixes the line with © and the current year, before the brand name.",
  "Zmień język": "Change language",
  "Opis dla czytników ekranu (aria-label). Na stronie widoczne są wyłącznie flagi PL/EN.":
    "Description for screen readers (aria-label). Only the PL/EN flags are visible on the page.",

  "Adres wyników wyszukiwania": "Search results URL",
  "Formularz wysyła metodą GET parametr q pod ten adres.":
    "The form submits the q parameter to this URL with GET.",
  "Szukaj...": "Search...",
  // --------------------------------------------------------- progress carousel
  "Proporcje kadru slajdu na mobile i tablecie.": "Slide frame aspect ratio on mobile and tablet.",
  "Kolor paska postępu. Puste = kolor marki.": "Progress bar colour. Empty = the brand colour.",
  // ------------------------------------- wierność ustawień (bramka M3, 03.08)
  // Pola odsłonięte po tym, jak bramka panel⇄renderer pokazała, że renderer je
  // czytał, a panel nie dawał na nie kontrolki.
  // (klucze „Źródło linków” / social fallback są już wyżej - patrz linie 73-77)
  "Użyj logo witryny": "Use the site logo",
  "Bierze logo z Wygląd → Opcje motywu (wraz z wersją dark). Wtedy pola URL poniżej są ignorowane.":
    "Takes the logo from Appearance → Theme options (including its dark variant). The URL fields below are then ignored.",
  "nie - własna grafika poniżej": "no - custom image below",
  "logo główne": "main logo",
  "logo mobilne": "mobile logo",
  "logo na przezroczystym tle": "logo on a transparent background",
  "Tryb wyszukiwania": "Search mode",
  "rozwijany panel pod polem": "dropdown panel under the field",
  "samo pole (wyniki na stronie)": "field only (results on the page)",
  "pełny ekran": "full screen",
  "Nagłówek panelu wyników": "Results panel heading",
  "Puste = bez nagłówka. Gdy placeholder jest pusty, nagłówek staje się jego zamiennikiem.":
    "Empty = no heading. When the placeholder is empty, the heading stands in for it.",
  "Widoczny po udanym wysłaniu formularza. Puste = tekst domyślny.":
    "Shown after the form is submitted successfully. Empty = the default text.",
  "Wysłano!": "Sent!",
  "Rozmiar ikony ✓ (px)": "Check icon size (px)",
  "Puste = rozmiar dobierany do tekstu bulletpointu.":
    "Empty = sized to match the bullet point text.",
  "Adres w linku z maila": "URL in the emailed link",
  "Strona, na którą prowadzi link resetu hasła. Musi renderować widget „Ustaw nowe hasło”.":
    "The page the password-reset link points at. It must render the “Set a new password” widget.",

  // ------------------------------------------------- author profile card
  Prezentacja: "Presentation",
  "Bok zdjęcia (px)": "Photo side (px)",
  "Kwadratowy portret na desktopie. Na węższych ekranach zdjęcie kurczy się proporcjonalnie.":
    "A square portrait on desktop. On narrower screens the photo scales down proportionally.",
  "Nałożenie karty na zdjęcie (px)": "Card overlap over the photo (px)",
  "0 = karta styka się ze zdjęciem bez nakładki.":
    "0 = the card sits next to the photo with no overlap.",
  "Maks. szerokość układu (px)": "Max layout width (px)",
  "Cień karty": "Card shadow",
  delikatny: "subtle",
  mocny: "strong",
  "bardzo mocny": "very strong",
  "Styl przycisków social": "Social button style",
  "wypełnione (ikona w kontrze)": "filled (knocked-out icon)",
  "Bok przycisku social (px)": "Social button side (px)",
  "Wyrównanie treści (mobile)": "Content alignment (mobile)",
  "Na desktopie karta zawsze wyrównuje treść do lewej.":
    "On desktop the card always aligns its content to the left.",
  "Animuj wejście karty": "Animate the card entrance",
  "Wyłączane automatycznie przy systemowym „ogranicz ruch” (prefers-reduced-motion).":
    "Switched off automatically under the system “reduce motion” setting (prefers-reduced-motion).",
  "Droplista tematów (zainteresowania)?": "Topics droplist (interests)?",
  // --------------------------------------------- widget „Karta z okładką"
  "Karta z okładką": "Cover card",
  "Okładka (tło karty)": "Cover (card background)",
  "Kadr pionowy lub kwadratowy. Puste = sama płaszczyzna w kolorze nakładki.":
    "Portrait or square crop. Empty = just a plane in the overlay colour.",
  "Tekst alternatywny okładki": "Cover alt text",
  "Puste = okładka jest dekoracją i znika z drzewa dostępności. Wypełnij, jeśli obraz niesie własną informację.":
    "Empty = the cover is decorative and leaves the accessibility tree. Fill it in when the image carries information of its own.",
  "Tytuł karty": "Card title",
  Zajawka: "Excerpt",
  "Data (RRRR-MM-DD)": "Date (YYYY-MM-DD)",
  "np. 2022-10-10": "e.g. 2022-10-10",
  "Jedna data dla obu języków - napis dla czytelnika powstaje w języku widoku.":
    "One date for both languages - the human-readable label is produced in the view language.",
  "Pokaż datę": "Show the date",
  "Adres tytułu": "Title link",
  "Puste = tytuł nie jest odnośnikiem.": "Empty = the title is not a link.",
  "Wiersze zajawki": "Excerpt lines",
  "Puste = grafit wzorca. Nakładka daje kontrast dla białego tekstu nad zdjęciem.":
    "Empty = the graphite of the reference. The overlay gives contrast to white text over the photo.",
  "Krycie nakładki u góry (0-1)": "Overlay opacity at the top (0-1)",
  "Krycie nakładki u dołu (0-1)": "Overlay opacity at the bottom (0-1)",
  "Wysokość kadru nad treścią (px)": "Media height above the content (px)",
  "Podświetl cień na hoverze": "Deepen the shadow on hover",
  // ------------------------------------------------- widget „Karta trasy"
  "Karta trasy": "Route card",
  "Mapa / zdjęcie w tle": "Background map / photo",
  "Kadr poziomy. Puste = sama płaszczyzna w kolorze nakładki.":
    "Landscape crop. Empty = just a plane in the overlay colour.",
  "Tekst alternatywny tła": "Background alt text",
  "Puste = mapa jest dekoracją i znika z drzewa dostępności. Wypełnij, jeśli obraz niesie własną informację.":
    "Empty = the map is decorative and leaves the accessibility tree. Fill it in when the image carries information of its own.",
  "Tytuł trasy": "Route title",
  "Autor / podpis": "Author / byline",
  "np. Trasa Pawła": "e.g. Paul's route",
  "Dystans (duża liczba)": "Distance (the big number)",
  "Bez jednostki - jednostkę wpisz w podpisie poniżej, żeby nie tłumaczyć jej razem z liczbą.":
    "No unit here - put the unit in the caption below, so it is translated separately from the number.",
  "Podpis pod liczbą": "Caption under the number",
  "Puste = karta nie jest linkiem. Przycisk polubienia działa niezależnie od odnośnika.":
    "Empty = the card is not a link. The like button works independently of the link.",
  "Pokaż polubienia": "Show likes",
  "Polubienie zapisuje się TYLKO w przeglądarce odwiedzającego - nie sumuje się między osobami.":
    "A like is stored ONLY in the visitor's browser - it is not summed across people.",
  "Liczba polubień na starcie": "Starting like count",
  "Powyżej tysiąca licznik skraca się do K/M (1527 -> 1.5K).":
    "Above a thousand the counter shortens to K/M (1527 -> 1.5K).",
  "Kolor po polubieniu": "Liked colour",
  "Puste = czerwień domyślna.": "Empty = the default red.",
  "Kolor nakładki": "Overlay colour",
  "Puste = kolor marki. Nakładka daje kontrast dla białego tekstu nad zdjęciem.":
    "Empty = the brand colour. The overlay gives the white text contrast over the photo.",
  "Krycie nakładki (0-1)": "Overlay opacity (0-1)",
  "Wysokość karty (px)": "Card height (px)",
  "0 = pełna szerokość kolumny.": "0 = the full column width.",
  "Zaokrąglenie rogów (px)": "Corner radius (px)",
  "6 px to zaokrąglenie platformy. Wzorzec karty używał 16 px.":
    "6 px is the platform radius. The source card pattern used 16 px.",
  "Rozmiar liczby dystansu (px)": "Distance number size (px)",
  "Liczba jest wyłączona z globalnej typografii widgetu - rozmiar tytułu i opisu ustawiasz w zakładce Styl.":
    "The number is exempt from the widget's global typography - set the title and description sizes on the Style tab.",
  "Wyłączone również przy systemowym ograniczeniu animacji.":
    "Also off when the system asks for reduced motion.",
  "Powiększ kartę pod kursorem": "Scale the card on hover",
};

/**
 * English rendering of a builder data-module label. Returns the source string
 * unchanged for Polish, and falls back to it when no translation is registered
 * (so an untranslated label still renders rather than disappearing).
 */
export function builderLabel<T extends string | undefined>(pl: T, lang: BuilderLang): T {
  if (lang !== "en" || !pl) return pl;
  return (BUILDER_LABELS_EN[pl] ?? pl) as T;
}

/** The admin UI language (i18next), independent of the canvas content language. */
export function useAdminLang(): BuilderLang {
  const { i18n } = useTranslation();
  return (i18n.language ?? "pl").startsWith("en") ? "en" : "pl";
}

/**
 * Hook returning a translator for builder data-module labels. Keyed off the
 * admin UI language, so switching the admin to EN localises the widget palette
 * and the whole properties panel regardless of which content language the
 * canvas is currently editing.
 */
export function useBuilderLabel(): <T extends string | undefined>(pl: T) => T {
  const lang = useAdminLang();
  return useCallback(<T extends string | undefined>(pl: T) => builderLabel(pl, lang), [lang]);
}
