// Widget registry - defaults + renderer. Used both inside the canvas and on
// the public site.
import type { WidgetNode, WidgetType, Json } from "./types";
import { newId } from "./types";
import {
  Heading1,
  Type as TypeIcon,
  Image as ImageIcon,
  MousePointerClick,
  Minus,
  MoveVertical,
  Video,
  GalleryHorizontal,
  Star,
  MapPin,
  Newspaper,
  Rows,
  FolderTree,
  Tags,
  Mail,
  Send,
  Megaphone,
  List,
  PanelLeft,
  Quote,
  Check,
  Link as LinkIcon,
  Globe,
  Sun,
  Search,
  User,
  Facebook,
  Flame,
  Bookmark,
  Megaphone as AdIcon,
  LayoutGrid,
  LogIn,
  ShieldCheck,
  Lock,
  ChevronRight,
  Clock,
  BookOpen,
  Image as CoverIcon,
  FileText,
  SlidersHorizontal,
  UserPlus,
  LineChart,
  Globe2,
  HandHeart,
  Gauge,
  Share2,
  Columns2,
  Shapes,
  FlaskConical,
  Layers,
  Target as TargetIcon,
} from "@/lib/lucide-shim";
import type { LucideIcon } from "@/lib/lucide-shim";

export interface WidgetDef {
  type: WidgetType;
  label: string;
  category: "basic" | "media" | "dynamic" | "form" | "navigation" | "blocks" | "features";
  icon: LucideIcon;
  defaults: () => WidgetNode["content"];
  /** Hide from the "Add widget" palette; the type stays valid for already-saved nodes. */
  hiddenInPalette?: boolean;
}

export const WIDGETS: WidgetDef[] = [
  // Basic
  {
    type: "heading",
    label: "Nagłówek",
    category: "basic",
    icon: Heading1,
    defaults: () => ({ text_pl: "Nowy nagłówek", text_en: "New heading", tag: "h2" }),
  },
  {
    type: "animated-heading",
    label: "Animowany nagłówek",
    category: "basic",
    icon: Heading1,
    defaults: () => ({
      mode: "highlight",
      shape: "underline",
      tag: "h2",
      align: "left",
      textBefore_pl: "Dołącz",
      textBefore_en: "Join",
      highlight_pl: "do nas",
      highlight_en: "us",
      textAfter_pl: "",
      textAfter_en: "",
      rotateWords_pl: ["szybko", "łatwo", "skutecznie"],
      rotateWords_en: ["fast", "easy", "effective"],
      color: "",
      accentColor: "#f97316",
      durationMs: 1600,
      delayMs: 200,
      loop: true,
    }),
  },
  {
    type: "text",
    label: "Tekst",
    category: "basic",
    icon: TypeIcon,
    defaults: () => ({ html_pl: "<p>Wpisz treść...</p>", html_en: "<p>Type content...</p>" }),
  },
  {
    type: "image",
    label: "Obrazek",
    category: "basic",
    icon: ImageIcon,
    defaults: () => ({ src: "", alt_pl: "", alt_en: "" }),
  },
  {
    type: "button",
    label: "Przycisk",
    category: "basic",
    icon: MousePointerClick,
    defaults: () => ({ label_pl: "Przycisk", label_en: "Button", href: "#", variant: "primary" }),
  },
  { type: "divider", label: "Rozdzielacz", category: "basic", icon: Minus, defaults: () => ({}) },
  {
    type: "spacer",
    label: "Odstępnik",
    category: "basic",
    icon: MoveVertical,
    defaults: () => ({ height: 32 }),
  },
  // Media
  { type: "video", label: "Wideo", category: "media", icon: Video, defaults: () => ({ url: "" }) },
  {
    type: "gallery",
    label: "Galeria",
    category: "media",
    icon: GalleryHorizontal,
    defaults: () => ({ images: [] as string[], columns: 3 }),
  },
  {
    type: "icon",
    label: "Ikonka",
    category: "media",
    icon: Star,
    defaults: () => ({ name: "Star", size: 32 }),
  },
  {
    type: "map",
    label: "Mapa Google",
    category: "media",
    icon: MapPin,
    defaults: () => ({ query: "Warszawa" }),
  },
  {
    type: "chart",
    label: "Wykres",
    category: "dynamic",
    icon: LineChart,
    defaults: () => ({
      kind: "bar",
      title_pl: "",
      title_en: "",
      description_pl: "",
      description_en: "",
      unit: "",
      // Format: pierwszy wiersz = nazwy serii, kolejne = kategoria; wartości.
      data: "; Seria A; Seria B\n2021; 12; 8\n2022; 19; 11\n2023; 14; 13\n2024; 24; 17",
      stacked: "off",
      height: 320,
      showLegend: "on",
      showGrid: "on",
      showValues: "off",
      animate: "on",
      source_pl: "",
      source_en: "",
    }),
  },
  {
    type: "data-map",
    label: "Mapa danych",
    category: "dynamic",
    icon: Globe2,
    defaults: () => ({
      region: "europe",
      title_pl: "",
      title_en: "",
      description_pl: "",
      description_en: "",
      unit: "",
      // Format: "KOD_ISO2; wartość" - jeden kraj na wiersz.
      data: "PL; 38\nDE; 84\nFR; 68\nIT; 59\nES; 48\nUA; 37",
      showLegend: "on",
      animate: "on",
      source_pl: "",
      source_en: "",
    }),
  },
  // ---- NES Digital Features (silnik: src/components/features) ----
  {
    type: "feature-timeline",
    label: "Oś czasu",
    category: "features",
    icon: Clock,
    defaults: () => ({
      title_pl: "Kalendarium EDIP / EDIS",
      title_en: "EDIP / EDIS timeline",
      description_pl: "Kluczowe kroki europejskiego programu przemysłu obronnego.",
      description_en: "Key milestones of the European defence industry programme.",
      // Format: "Data; Tytuł|Title; Opis|Description; slot(1-8, opc.)"
      data: [
        "2024-03; Prezentacja EDIS|EDIS unveiled; Pierwsza strategia przemysłu obronnego UE|The EU's first defence industrial strategy; 1",
        "2024-07; Wniosek EDIP|EDIP proposal; Program wart 1,5 mld EUR do 2027|A EUR 1.5bn programme through 2027; 3",
        "2025-Q4; Negocjacje trilogu|Trilogue negotiations; Uzgodnienia PE i Rady|Parliament–Council reconciliation; 5",
        "2026-Q2; Wejście w życie|Entry into force; Pierwsze zaproszenia do składania wniosków|First calls for proposals; 4",
      ].join("\n"),
      animate: "on",
      source_pl: "Źródło: Komisja Europejska, DG DEFIS",
      source_en: "Source: European Commission, DG DEFIS",
    }),
  },
  {
    type: "feature-sankey",
    label: "Sankey (przepływy)",
    category: "features",
    icon: Share2,
    defaults: () => ({
      title_pl: "Przepływy dostaw LNG do UE",
      title_en: "LNG supply flows to the EU",
      description_pl: "Kierunki importu skroplonego gazu ziemnego (mld m³).",
      description_en: "Liquefied natural gas import routes (bcm).",
      unit: " mld m³",
      height: 340,
      // Format: "Źródło|Source; Cel|Target; wartość"
      data: [
        "USA|USA; Terminale UE|EU terminals; 56",
        "Katar|Qatar; Terminale UE|EU terminals; 18",
        "Rosja|Russia; Terminale UE|EU terminals; 15",
        "Terminale UE|EU terminals; Europa Śr.-Wsch.|CEE; 34",
        "Terminale UE|EU terminals; Europa Zach.|Western Europe; 55",
      ].join("\n"),
      animate: "on",
      source_pl: "Źródło: dane ilustracyjne",
      source_en: "Source: illustrative data",
    }),
  },
  {
    type: "feature-compare",
    label: "Porównywarka państw",
    category: "features",
    icon: Columns2,
    defaults: () => ({
      title_pl: "Porównanie państw członkowskich",
      title_en: "Member state comparison",
      description_pl: "Wybrane wskaźniki bezpieczeństwa i gospodarki.",
      description_en: "Selected security and economic indicators.",
      // Nagłówek: "; Kol1; Kol2; ...", wiersze: "Wskaźnik [jedn.]|Indicator [unit]; v1; v2; ..."
      data: [
        "; Polska|Poland; Niemcy|Germany; Francja|France",
        "Wydatki obronne [% PKB]|Defence spending [% GDP]; 4,1; 2,1; 2,0",
        "Zależność od gazu [%]|Gas dependency [%]; 62; 49; 24",
        "Wsparcie dla Ukrainy [mld EUR]|Aid to Ukraine [EUR bn]; 4,9; 17,7; 3,8",
      ].join("\n"),
      highlight: 0,
      showBars: "on",
      source_pl: "Źródło: dane ilustracyjne",
      source_en: "Source: illustrative data",
    }),
  },
  {
    type: "feature-risk-matrix",
    label: "Macierz ryzyka",
    category: "features",
    icon: Shapes,
    defaults: () => ({
      title_pl: "Macierz ryzyka bezpieczeństwa",
      title_en: "Security risk matrix",
      description_pl: "Prawdopodobieństwo względem wpływu (skala 1–5).",
      description_en: "Likelihood versus impact (1–5 scale).",
      axisXLabel_pl: "Wpływ →",
      axisXLabel_en: "Impact →",
      axisYLabel_pl: "Prawdopodobieństwo →",
      axisYLabel_en: "Likelihood →",
      // Format: "Nazwa|Name; prawdopodobieństwo 1-5; wpływ 1-5; opis|desc (opc.)"
      data: [
        "Przerwanie dostaw energii|Energy supply disruption; 3; 5; Zima 2026|Winter 2026",
        "Atak hybrydowy|Hybrid attack; 4; 3; Infrastruktura krytyczna|Critical infrastructure",
        "Obchodzenie sankcji|Sanctions circumvention; 4; 2; Państwa trzecie|Third countries",
        "Zakłócenie łańcucha dostaw|Supply chain shock; 2; 4; Komponenty obronne|Defence components",
      ].join("\n"),
      animate: "on",
      source_pl: "Źródło: ocena własna",
      source_en: "Source: own assessment",
    }),
  },
  {
    type: "feature-indicator",
    label: "Karta wskaźnika",
    category: "features",
    icon: Gauge,
    defaults: () => ({
      label_pl: "Indeks bezpieczeństwa energetycznego",
      label_en: "Energy security index",
      value: "72,4",
      unit: "/100",
      delta: "+5,1",
      deltaLabel_pl: "r/r",
      deltaLabel_en: "YoY",
      deltaArrow: "up",
      deltaTone: "positive",
      // Sparkline: liczby rozdzielone ";" lub nowymi liniami.
      spark: "58; 61; 60; 64; 67; 69; 72,4",
      source_pl: "Źródło: NES",
      source_en: "Source: NES",
      href: "",
    }),
  },
  {
    type: "feature-network",
    label: "Sieć powiązań",
    category: "features",
    icon: Layers,
    defaults: () => ({
      title_pl: "Sieć powiązań instytucjonalnych",
      title_en: "Institutional relations network",
      description_pl: "Powiązania między aktorami w danym dossier.",
      description_en: "Links between actors in a given dossier.",
      // Krawędzie: "A|A_en; B|B_en; siła 1-5 (opc.); etykieta|label (opc.)"
      edges: [
        "Komisja|Commission; Rada|Council; 4; współdecydowanie|co-decision",
        "Komisja|Commission; Parlament|Parliament; 3; opinia|opinion",
        "Rada|Council; Państwa czł.|Member states; 5; głosowanie|voting",
        "Parlament|Parliament; Komisje|Committees; 3; sprawozdanie|report",
        "Państwa czł.|Member states; Grupy robocze|Working groups; 2; ",
      ].join("\n"),
      // Grupy: "Węzeł|Node; grupa|group"
      groups: [
        "Komisja|Commission; Instytucje UE|EU institutions",
        "Rada|Council; Instytucje UE|EU institutions",
        "Parlament|Parliament; Instytucje UE|EU institutions",
        "Państwa czł.|Member states; Krajowe|National",
      ].join("\n"),
      height: 420,
      animate: "on",
      source_pl: "Źródło: opracowanie NES",
      source_en: "Source: NES analysis",
    }),
  },
  {
    type: "feature-corridor-map",
    label: "Mapa korytarzy",
    category: "features",
    icon: MapPin,
    defaults: () => ({
      title_pl: "Europejskie korytarze transportowe",
      title_en: "European transport corridors",
      description_pl: "Wybrane korytarze TEN-T i węzły logistyczne.",
      description_en: "Selected TEN-T corridors and logistics hubs.",
      region: "europe",
      // Korytarz: "Nazwa|Name; slot 1-8; lat,lon > lat,lon > ..."
      corridors: [
        "Bałtyk–Adriatyk|Baltic–Adriatic; 1; 54.35,18.65 > 52.23,21.01 > 50.06,19.94 > 48.21,16.37 > 45.44,12.32",
        "Morze Północne–Bałtyk|North Sea–Baltic; 3; 51.51,-0.13 > 52.52,13.40 > 52.23,21.01 > 54.69,25.28",
        "Ren–Dunaj|Rhine–Danube; 5; 48.86,2.35 > 48.14,11.58 > 48.21,16.37 > 44.43,26.10",
      ].join("\n"),
      // Marker: "lat,lon; Etykieta|Label"
      markers: [
        "54.35,18.65; Gdańsk",
        "45.44,12.32; Wenecja|Venice",
        "51.96,4.13; Rotterdam",
        "44.43,26.10; Bukareszt|Bucharest",
      ].join("\n"),
      // Kody ISO-2 do podświetlenia (rozdzielone ";" lub ",").
      highlightCountries: "PL; DE; AT; IT; NL; RO",
      animate: "on",
      source_pl: "Źródło: TEN-T (ilustracyjne)",
      source_en: "Source: TEN-T (illustrative)",
    }),
  },
  {
    type: "feature-sources",
    label: "Biblioteka źródeł",
    category: "features",
    icon: BookOpen,
    defaults: () => ({
      title_pl: "Biblioteka źródeł",
      title_en: "Source library",
      description_pl: "Dokumenty i dane wykorzystane w analizie.",
      description_en: "Documents and data used in the analysis.",
      // Format: "Typ|Type; Rok; Tytuł|Title; Wydawca|Publisher; URL"
      entries: [
        "Raport|Report; 2024; Europejska strategia przemysłu obronnego|European Defence Industrial Strategy; Komisja Europejska|European Commission; https://defence-industry-space.ec.europa.eu",
        "Dane|Data; 2025; Statystyki energetyczne|Energy statistics; Eurostat; https://ec.europa.eu/eurostat",
        "Traktat|Treaty; 2007; Traktat z Lizbony|Treaty of Lisbon; UE|EU; https://eur-lex.europa.eu",
      ].join("\n"),
      sort: "year-desc",
      showSearch: "on",
      source_pl: "",
      source_en: "",
    }),
  },
  {
    type: "feature-methodology",
    label: "Nota metodologiczna",
    category: "features",
    icon: FlaskConical,
    defaults: () => ({
      title_pl: "Nota metodologiczna",
      title_en: "Methodology note",
      version: "1.0",
      updated: "2026-07",
      defaultOpen: "0",
      html_pl:
        "<p>Dane pochodzą ze źródeł oficjalnych (Eurostat, Komisja Europejska). Wartości za rok bieżący są szacunkami. Indeks normalizowany do skali 0–100.</p>",
      html_en:
        "<p>Data are drawn from official sources (Eurostat, European Commission). Current-year figures are estimates. The index is normalised to a 0–100 scale.</p>",
    }),
  },
  {
    type: "tts",
    label: "Odsłuchaj (TTS)",
    category: "media",
    icon: Megaphone,
    defaults: () => ({
      source: "post",
      text_pl: "",
      text_en: "",
      voiceId: "JBFqnCBsd6RMkjVDRZzb",
      model: "eleven_multilingual_v2",
      label_pl: "Odsłuchaj artykuł",
      label_en: "Listen to article",
    }),
  },
  // Dynamic
  {
    type: "post-list",
    label: "Lista wpisów",
    category: "dynamic",
    icon: Newspaper,
    defaults: () => ({ limit: 6, columns: 3, category: null as string | null }),
  },
  {
    type: "carousel",
    label: "Karuzela wpisów",
    category: "dynamic",
    icon: Rows,
    defaults: () => ({ limit: 8, category: null as string | null }),
  },
  {
    type: "categories",
    label: "Kategorie",
    category: "dynamic",
    icon: FolderTree,
    defaults: () => ({}),
  },
  { type: "tags", label: "Tagi", category: "dynamic", icon: Tags, defaults: () => ({}) },
  // Forms
  {
    type: "newsletter",
    label: "Newsletter",
    category: "form",
    icon: Mail,
    defaults: () => ({
      title_pl: "Zapisz się",
      title_en: "Subscribe",
      requireEmail: "1",
      showFirstName: "0",
      showLastName: "0",
      showCompany: "0",
      requireFirstName: "0",
      requireLastName: "0",
      requireCompany: "0",
      customFields: [] as unknown as Json,
    }),
  },
  // Legacy "contact" widget kept for backward compatibility with already-saved
  // pages. New panels should use "contact-form" (richer config). Defaults are
  // intentionally aligned with contact-form so the property panel behaves the
  // same for both types.
  {
    type: "contact",
    label: "Formularz kontaktowy (legacy)",
    category: "form",
    icon: Send,
    hiddenInPalette: true,
    defaults: () => ({
      variant: "card",
      title_pl: "Skontaktuj się z nami",
      title_en: "Contact us",
      submitLabel_pl: "Wyślij wiadomość",
      submitLabel_en: "Send message",
      successMsg_pl: "Dziękujemy!",
      successMsg_en: "Thanks!",
      requireConsent: true,
      showFirstName: true,
      showLastName: true,
      showEmail: true,
      showMessage: true,
      requireFirstName: true,
      requireLastName: false,
      requireEmail: true,
      requirePhone: false,
      requireCompany: false,
      requireSubject: false,
      requireMessage: true,

      consentText_pl:
        "Wyrażam zgodę na przetwarzanie moich danych osobowych zgodnie z [Polityką prywatności](/polityka-prywatnosci).",
      consentText_en:
        "I consent to processing of my personal data in accordance with the [Privacy Policy](/privacy-policy).",
      columns: 2,
      buttonAlign: "left",
      buttonPosition: "bottom",
      buttonVariant: "solid",
      buttonSize: "md",
      radiusPx: 12,
      paddingPx: 32,
      bgOverlay: 0,
    }),
  },
  {
    type: "cta",
    label: "Wezwanie do akcji",
    category: "form",
    icon: Megaphone,
    defaults: () => ({
      title_pl: "Działajmy razem",
      title_en: "Let's act together",
      href: "#",
      cta_pl: "Skontaktuj się",
      cta_en: "Contact us",
    }),
  },
  {
    type: "join-us",
    label: "Dołącz do nas",
    category: "form",
    icon: UserPlus,
    defaults: () => ({
      variant: "split",
      bgLight: "",
      bgDark: "",
      perkIconColor: "",
      showInterests: "1",
      title_pl: "",
      title_en: "",
      subtitle_pl: "",
      subtitle_en: "",
      showFirstName: "1",
      showLastName: "1",
      showPosition: "0",
      showLinkedin: "0",
      showPhone: "0",
      showCompany: "0",
      showCountry: "0",
      // per-field required (e-mail wymagany domyślnie)
      requireFirstName: "1",
      requireLastName: "1",
      requireEmail: "1",
      requirePosition: "0",
      requireLinkedin: "0",
      requirePhone: "0",
      requireCompany: "0",
      requireCountry: "0",
      requireInterests: "0",
      interestSlugs: [],
    }),
  },
  {
    type: "customize-interests",
    label: "Dopasuj zainteresowania",
    category: "form",
    icon: SlidersHorizontal,
    defaults: () => ({ variant: "full", showHeader: "1" }),
  },

  // Navigation
  {
    type: "nav-link",
    label: "Link menu",
    category: "navigation",
    icon: LinkIcon,
    defaults: () => ({
      label_pl: "Nowy link",
      label_en: "New link",
      href: "/",
      target: "self",
      variant: "text",
    }),
  },
  {
    type: "mega-menu",
    label: "Mega menu",
    category: "navigation",
    icon: LayoutGrid,
    defaults: () => ({
      trigger_pl: "Produkty",
      trigger_en: "Products",
      href: "",
      triggerOn: "hover",
      width: "container",
      widthPx: 1140,
      columns: [
        {
          title_pl: "Kategorie",
          title_en: "Categories",
          links: [
            { label_pl: "Analizy", label_en: "Analyses", href: "#" },
            { label_pl: "Wywiady", label_en: "Interviews", href: "#" },
          ],
          featured: null,
        },
        {
          title_pl: "Zasoby",
          title_en: "Resources",
          links: [
            { label_pl: "Raporty", label_en: "Reports", href: "#" },
            { label_pl: "Newsletter", label_en: "Newsletter", href: "#" },
          ],
          featured: null,
        },
        {
          title_pl: "Wyróżnione",
          title_en: "Featured",
          links: [],
          featured: {
            image: "",
            title_pl: "Najnowszy raport",
            title_en: "Latest report",
            excerpt_pl: "Krótki opis wyróżnionej treści.",
            excerpt_en: "Short summary of featured content.",
            href: "#",
            cta_pl: "Czytaj",
            cta_en: "Read",
          },
        },
      ],
    }),
  },
  {
    type: "menu",
    label: "Menu",
    category: "navigation",
    icon: List,
    defaults: () => ({
      menu_key: "main",
    }),
  },
  // Site chrome (header / footer / menu)
  {
    type: "social-icons",
    label: "Ikony social",
    category: "navigation",
    icon: Facebook,
    defaults: () => ({
      facebook: "",
      twitter: "",
      youtube: "",
      instagram: "",
      linkedin: "",
      email: "",
      size: 16,
    }),
  },
  {
    type: "lang-switcher",
    label: "Język (PL/EN)",
    category: "navigation",
    icon: Globe,
    defaults: () => ({ showLabel: true, label_pl: "Zmień język", label_en: "Switch language" }),
  },
  {
    type: "theme-toggle",
    label: "Tryb jasny/ciemny",
    category: "navigation",
    icon: Sun,
    defaults: () => ({}),
  },
  {
    type: "account-link",
    label: "Konto / Logowanie",
    category: "navigation",
    icon: User,
    defaults: () => ({
      signin_pl: "Zaloguj",
      signin_en: "Sign in",
      signup_pl: "Zarejestruj",
      signup_en: "Sign up",
      panel_pl: "Panel",
      panel_en: "Dashboard",
      logout_pl: "Wyloguj",
      logout_en: "Sign out",
      signinHref: "/login",
      signupHref: "/login?mode=signup",
      panelRadius: 12,
      panelWidth: 280,
      items: [
        {
          id: "g1",
          section: "guest",
          kind: "custom",
          icon: "LogIn",
          label_pl: "Zaloguj",
          label_en: "Sign in",
          customHref: "/login",
          desc_pl: "Dostęp do Twojego konta",
          desc_en: "Access your account",
        },
        {
          id: "g2",
          section: "guest",
          kind: "custom",
          icon: "UserPlus",
          label_pl: "Załóż konto",
          label_en: "Create account",
          customHref: "/login?mode=signup",
          desc_pl: "Bezpłatna rejestracja",
          desc_en: "Free registration",
        },
        {
          id: "a1",
          section: "auth",
          kind: "preset",
          presetKey: "profile",
          icon: "User",
          label_pl: "Mój profil",
          label_en: "My profile",
        },
        {
          id: "a2",
          section: "auth",
          kind: "preset",
          presetKey: "bookmarks",
          icon: "Bookmark",
          label_pl: "Zapisane materiały",
          label_en: "Saved items",
        },
        {
          id: "a3",
          section: "auth",
          kind: "preset",
          presetKey: "follows",
          icon: "Heart",
          label_pl: "Obserwowane",
          label_en: "Following",
        },
        {
          id: "a4",
          section: "auth",
          kind: "preset",
          presetKey: "subscription",
          icon: "Crown",
          label_pl: "Subskrypcja",
          label_en: "Subscription",
        },
        { id: "a5", section: "auth", kind: "separator" },
        {
          id: "a6",
          section: "auth",
          kind: "preset",
          presetKey: "account",
          icon: "Settings",
          label_pl: "Ustawienia konta",
          label_en: "Account settings",
        },
        {
          id: "a7",
          section: "auth",
          kind: "logout",
          icon: "LogOut",
          label_pl: "Wyloguj",
          label_en: "Sign out",
        },
        {
          id: "s1",
          section: "staff",
          kind: "preset",
          presetKey: "admin",
          icon: "LayoutDashboard",
          label_pl: "Panel admina",
          label_en: "Admin panel",
        },
      ] as unknown as Json,
    }),
  },
  {
    type: "search-button",
    label: "Wyszukiwarka",
    category: "navigation",
    icon: Search,
    defaults: () => ({
      label_pl: "Szukaj",
      label_en: "Search",
      height: 40,
      radius: 8,
      fontSize: 14,
      limit: 8,
      liveResults: "on",
    }),
  },
  {
    type: "copyright",
    label: "Copyright",
    category: "navigation",
    icon: TypeIcon,
    defaults: () => ({
      text_pl: "Wszelkie prawa zastrzeżone",
      text_en: "All rights reserved",
      showYear: true,
      brand: "New European Strategies",
    }),
  },
  // Rich blocks
  {
    type: "accordion",
    label: "Accordion",
    category: "blocks",
    icon: List,
    defaults: () => ({
      items: [
        { q_pl: "Pytanie 1", q_en: "Question 1", a_pl: "Odpowiedź…", a_en: "Answer…" },
        { q_pl: "Pytanie 2", q_en: "Question 2", a_pl: "Odpowiedź…", a_en: "Answer…" },
      ],
    }),
  },
  {
    type: "tabs",
    label: "Zakładki",
    category: "blocks",
    icon: PanelLeft,
    defaults: () => ({
      tabs: [
        {
          label_pl: "Tab 1",
          label_en: "Tab 1",
          html_pl: "<p>Treść 1</p>",
          html_en: "<p>Content 1</p>",
        },
        {
          label_pl: "Tab 2",
          label_en: "Tab 2",
          html_pl: "<p>Treść 2</p>",
          html_en: "<p>Content 2</p>",
        },
      ],
    }),
  },
  {
    type: "testimonial",
    label: "Opinia / Cytat",
    category: "blocks",
    icon: Quote,
    defaults: () => ({
      quote_pl: "To rozwiązanie zmieniło sposób, w jaki pracujemy.",
      quote_en: "This product changed the way we work.",
      author: "Anna Kowalska",
      role_pl: "CEO, ACME",
      role_en: "CEO, ACME",
      avatar: "",
    }),
  },
  {
    type: "team-member",
    label: "Team member",
    category: "blocks",
    icon: User,
    defaults: () => ({
      // Brak placeholderów: dopóki pole nie zostanie wypełnione, widget nie
      // renderuje danego elementu ani ikony (patrz warunki {name && ...},
      // {position && ...}, {socials.length > 0 && ...} w TeamMemberWidget).
      name: "",
      position_pl: "",
      position_en: "",
      programLabel_pl: "",
      programLabel_en: "",
      bio_pl: "",
      bio_en: "",
      email: "",
      phone: "",
      photo: "",
      x: "",
      facebook: "",
      linkedin: "",
      instagram: "",
      youtube: "",
      website: "",
      accentColor: "",
      overlayAlpha: 0.55,
    }),
  },
  {
    type: "rich-text",
    label: "Treść (bloki)",
    category: "blocks",
    icon: FileText,
    defaults: () => ({
      // Localized blocks document, authored with the same block editor used for
      // article bodies. Lets the builder host full rich content (callouts, FAQ,
      // pros/cons, TOC, embeds, …) so it is the one page-composition engine.
      doc: { pl: { version: 1, blocks: [] }, en: { version: 1, blocks: [] } },
    }),
  },
  {
    type: "pricing",
    label: "Cennik",
    category: "blocks",
    icon: Check,
    defaults: () => ({
      plans: [
        {
          name_pl: "Start",
          name_en: "Starter",
          price: "0",
          currency: "PLN",
          period_pl: "/mies.",
          period_en: "/mo",
          features_pl: ["1 użytkownik", "Podstawowe funkcje"],
          features_en: ["1 user", "Core features"],
          cta_pl: "Wybierz",
          cta_en: "Choose",
          href: "#",
          featured: false,
        },
        {
          name_pl: "Pro",
          name_en: "Pro",
          price: "49",
          currency: "PLN",
          period_pl: "/mies.",
          period_en: "/mo",
          features_pl: ["Wszystko ze Start", "Wsparcie 24/7"],
          features_en: ["Everything in Starter", "24/7 support"],
          cta_pl: "Wybierz",
          cta_en: "Choose",
          href: "#",
          featured: true,
        },
      ],
    }),
  },
  // Interaktywne koło - do 8 pozycji rozłożonych na okręgu / półokręgu.
  // Kliknięcie / hover na pozycję przenosi treść (tytuł + opis) do środka.
  {
    type: "interactive-circle",
    label: "Interaktywne koło",
    category: "blocks",
    icon: TargetIcon,
    defaults: () => ({
      layout: "semi",
      trigger: "hover",
      size: 480,
      itemSize: 72,
      circleColor: "",
      circleThickness: 2,
      itemBg: "",
      itemColor: "",
      activeBg: "",
      activeColor: "",
      title_pl: "Wyświetl treści w półokrągłym układzie",
      title_en: "Display content in a semi-circular layout",
      desc_pl: "Zaprezentuj treść w atrakcyjnym układzie kołowym. Możesz wyróżnić kluczowe informacje efektami hover lub kliknięcia i dostosować styl do swoich preferencji.",
      desc_en: "Present your content in an attractive circle layout. You can highlight key information with click or hover effects and style it as per your preference.",
      items: [
        { icon: "Leaf",   label_pl: "Pozycja 1", label_en: "Item 1", title_pl: "Pozycja 1", title_en: "Item 1", desc_pl: "", desc_en: "", href: "" },
        { icon: "MessageCircle", label_pl: "Pozycja 2", label_en: "Item 2", title_pl: "Pozycja 2", title_en: "Item 2", desc_pl: "", desc_en: "", href: "" },
        { icon: "MapPin", label_pl: "Pozycja 3", label_en: "Item 3", title_pl: "Pozycja 3", title_en: "Item 3", desc_pl: "", desc_en: "", href: "" },
        { icon: "Rocket", label_pl: "Pozycja 4", label_en: "Item 4", title_pl: "Pozycja 4", title_en: "Item 4", desc_pl: "", desc_en: "", href: "" },
        { icon: "Hourglass", label_pl: "Pozycja 5", label_en: "Item 5", title_pl: "Pozycja 5", title_en: "Item 5", desc_pl: "", desc_en: "", href: "" },
        { icon: "Tag",    label_pl: "Pozycja 6", label_en: "Item 6", title_pl: "Pozycja 6", title_en: "Item 6", desc_pl: "", desc_en: "", href: "" },
      ],
    }),
  },
  // Home-page building blocks
  {
    type: "section-label",
    label: "Etykieta sekcji",
    category: "basic",
    icon: Bookmark,
    defaults: () => ({
      label_pl: "Najnowsze",
      label_en: "Latest",
      color: "brand",
      action_pl: "więcej",
      action_en: "more",
      href: "",
    }),
  },
  {
    type: "hot-topic-bar",
    label: "Pasek hot topic",
    category: "blocks",
    icon: Flame,
    defaults: () => ({
      badge_pl: "Hot topic",
      badge_en: "Hot topic",
      title_pl: "Najważniejszy temat dnia",
      title_en: "Today's top story",
      href: "",
      iconName: "Flame",
    }),
  },
  {
    type: "rated-list",
    label: "Lista z oceną",
    category: "blocks",
    icon: Star,
    defaults: () => ({
      items: [
        {
          title_pl: "Pierwszy temat",
          title_en: "First topic",
          excerpt_pl: "",
          excerpt_en: "",
          author: "",
          rating: 8.3,
        },
        {
          title_pl: "Drugi temat",
          title_en: "Second topic",
          excerpt_pl: "",
          excerpt_en: "",
          author: "",
          rating: 0,
        },
        {
          title_pl: "Trzeci temat",
          title_en: "Third topic",
          excerpt_pl: "",
          excerpt_en: "",
          author: "",
          rating: 0,
        },
      ],
    }),
  },
  {
    type: "dark-featured-card",
    label: "Karta wyróżniona (dark)",
    category: "blocks",
    icon: Newspaper,
    defaults: () => ({
      badge_pl: "WYRÓŻNIONE",
      badge_en: "FEATURED",
      title_pl: "Tytuł wyróżnionego artykułu",
      title_en: "Featured article title",
      excerpt_pl: "",
      excerpt_en: "",
      image: "",
      href: "",
    }),
  },
  {
    type: "slider",
    label: "Slider",
    category: "media",
    icon: GalleryHorizontal,
    defaults: () => ({
      variant: "editorial-hero",
      source: "posts",
      limit: 5,
      orderBy: "newest",
      showExcerpt: true,
      ratio: "16/9",
      autoplay: true,
      intervalMs: 4500,
      rounded: "md",
      overlayOpacity: 0.45,
      columns: 3,
      items: [],
    }),
  },

  // Advertising
  {
    type: "ad-slot",
    label: "Slot reklamowy",
    category: "blocks",
    icon: AdIcon,
    defaults: () => ({ slotId: "" }),
  },
  // Donations / patronage
  {
    type: "donations",
    label: "Darowizny / Mecenat",
    category: "form",
    icon: HandHeart,
    defaults: () => ({
      variant: "hero",
      title_pl: "Mecenat obywatelski",
      title_en: "Citizen patronage",
      subtitle_pl:
        "Twoja darowizna finansuje niezależną analizę - tracker legislacyjny UE, raporty i debaty.",
      subtitle_en:
        "Your donation funds independent analysis - the EU legislative tracker, reports and debates.",
      cta_pl: "Przekaż darowiznę",
      cta_en: "Donate",
      href: "/support",
      showMonth: true,
      showCount: true,
      showRecent: false,
      goalCents: 0,
      accent: "",
      currency: "PLN",
    }),
  },
  // News ticker (horizontal scrolling latest posts)
  {
    type: "news-ticker",
    label: "News ticker",
    category: "dynamic",
    icon: Flame,
    defaults: () => ({
      badge_pl: "Najnowsze",
      badge_en: "Latest",
      limit: 10,
      speedSeconds: 40,
      pauseOnHover: true,
      separator: "•",
      categoriesCsv: "",
      uniqueOnPage: false,
    }),
  },
  // Podcast
  {
    type: "podcast-latest",
    label: "Podcast: najnowsze",
    category: "dynamic",
    icon: Megaphone,
    defaults: () => ({
      limit: 4,
      columns: 2,
      variant: "grid", // grid | list | featured
      showPlayer: "true",
    }),
  },
  // Web Stories
  {
    type: "web-stories-carousel",
    label: "Web Stories: karuzela",
    category: "dynamic",
    icon: GalleryHorizontal,
    defaults: () => ({
      limit: 8,
      variant: "carousel", // carousel | grid
      aspect: "9/16",
    }),
  },
  // Auth forms - structural widgets, never raw HTML
  {
    type: "login-form",
    label: "Logowanie",
    category: "form",
    icon: LogIn,
    defaults: () => ({
      variant: "card",
      title_pl: "Zaloguj się",
      title_en: "Sign in",
      subtitle_pl: "Witaj ponownie",
      subtitle_en: "Welcome back",
      submitLabel_pl: "Zaloguj",
      submitLabel_en: "Sign in",
      showRemember: true,
      showShowPassword: true,
      showForgot: true,
      showRegister: true,
      showOAuthGoogle: true,
      redirectTo: "/",
      registerHref: "/register",
      forgotHref: "/lost-password",
      customFields: [] as unknown as Json,
    }),
  },
  {
    type: "register-form",
    label: "Rejestracja",
    category: "form",
    icon: User,
    defaults: () => ({
      variant: "card",
      title_pl: "Załóż konto",
      title_en: "Create account",
      subtitle_pl: "",
      subtitle_en: "",
      submitLabel_pl: "Zarejestruj",
      submitLabel_en: "Register",
      requireConsent: true,
      newsletterOptIn: true,
      showOAuthGoogle: true,
      showPasswordConfirm: "0",
      requirePasswordConfirm: "0",
      showPhone: "0",
      requirePhone: "0",
      showCompany: "0",
      requireCompany: "0",
      consentText_pl:
        "Wyrażam zgodę na przetwarzanie moich danych osobowych zgodnie z [Polityką prywatności](/polityka-prywatnosci).",
      consentText_en:
        "I consent to processing of my personal data in accordance with the [Privacy Policy](/privacy-policy).",
      redirectTo: "/",
      loginHref: "/login",
      customFields: [] as unknown as Json,
    }),
  },
  {
    type: "lost-password-form",
    label: "Odzyskaj hasło",
    category: "form",
    icon: Lock,
    defaults: () => ({
      variant: "card",
      title_pl: "Zapomniałeś hasła?",
      title_en: "Forgot password?",
      subtitle_pl: "Wyślemy link do resetu na podany e-mail.",
      subtitle_en: "We'll send a reset link to your email.",
      submitLabel_pl: "Wyślij link",
      submitLabel_en: "Send reset link",
      loginHref: "/login",
    }),
  },
  {
    type: "reset-password-form",
    label: "Ustaw nowe hasło",
    category: "form",
    icon: ShieldCheck,
    defaults: () => ({
      variant: "card",
      title_pl: "Ustaw nowe hasło",
      title_en: "Set new password",
      subtitle_pl: "",
      subtitle_en: "",
      submitLabel_pl: "Zapisz",
      submitLabel_en: "Save",
      redirectTo: "/login",
    }),
  },

  // Dynamic tag widgets - render current post / archive context
  {
    type: "post-title",
    label: "Tytuł wpisu (dyn.)",
    category: "dynamic",
    icon: Heading1,
    defaults: () => ({
      tag: "h1",
      linkToPost: false,
      fallback_pl: "Tytuł wpisu",
      fallback_en: "Post title",
    }),
  },
  {
    type: "post-meta",
    label: "Meta wpisu (data, autor, czas)",
    category: "dynamic",
    icon: Clock,
    defaults: () => ({
      showAuthor: true,
      showDate: true,
      showReadingTime: true,
      showViews: false,
      showCategory: true,
      separator: " · ",
      dateFormat: "long",
    }),
  },
  {
    type: "post-tags-dyn",
    label: "Tagi wpisu (dyn.)",
    category: "dynamic",
    icon: Tags,
    defaults: () => ({ variant: "pill", showLabel: true, label_pl: "Tagi:", label_en: "Tags:" }),
  },
  {
    type: "post-categories-dyn",
    label: "Kategorie wpisu (dyn.)",
    category: "dynamic",
    icon: FolderTree,
    defaults: () => ({ variant: "pill", limit: 0 }),
  },
  {
    type: "post-author-card",
    label: "Karta autora",
    category: "dynamic",
    icon: User,
    defaults: () => ({ showAvatar: true, showBio: true, showSocial: true, variant: "card" }),
  },
  {
    type: "post-breadcrumbs",
    label: "Okruszki (breadcrumbs)",
    category: "dynamic",
    icon: ChevronRight,
    defaults: () => ({ separator: "/", showHome: true, home_pl: "Start", home_en: "Home" }),
  },
  {
    type: "post-cover",
    label: "Okładka wpisu",
    category: "dynamic",
    icon: CoverIcon,
    defaults: () => ({ aspect: "16/9", rounded: true, showCaption: false }),
  },
  {
    type: "post-excerpt",
    label: "Zajawka wpisu",
    category: "dynamic",
    icon: FileText,
    defaults: () => ({ maxChars: 240 }),
  },
  {
    type: "archive-title",
    label: "Tytuł archiwum",
    category: "dynamic",
    icon: BookOpen,
    defaults: () => ({ showCount: true, showDescription: true }),
  },
  {
    type: "search-form",
    label: "Formularz wyszukiwania",
    category: "form",
    icon: Search,
    defaults: () => ({
      action: "/search",
      placeholder_pl: "Szukaj...",
      placeholder_en: "Search...",
      button_pl: "Szukaj",
      button_en: "Search",
      variant: "default",
    }),
  },
  {
    type: "contact-form",
    label: "Formularz kontaktowy",
    category: "form",
    icon: Send,
    defaults: () => ({
      variant: "card",
      title_pl: "Skontaktuj się z nami",
      title_en: "Contact us",
      subtitle_pl: "Odpowiemy w ciągu 24h.",
      subtitle_en: "We'll reply within 24h.",
      submitLabel_pl: "Wyślij wiadomość",
      submitLabel_en: "Send message",
      successMsg_pl: "Dziękujemy! Wiadomość została wysłana.",
      successMsg_en: "Thanks! Your message has been sent.",
      requireConsent: true,
      consentText_pl:
        "Wyrażam zgodę na przetwarzanie moich danych osobowych zgodnie z [Polityką prywatności](/polityka-prywatnosci).",
      consentText_en:
        "I consent to processing of my personal data in accordance with the [Privacy Policy](/privacy-policy).",
      showFirstName: true,
      showLastName: true,
      showEmail: true,
      showPhone: false,
      showCompany: false,
      showSubject: true,
      showMessage: true,
      // per-field "wymagane" — spójne z polityką w bazie
      requireFirstName: true,
      requireLastName: false,
      requireEmail: true,
      requirePhone: false,
      requireCompany: false,
      requireSubject: false,
      requireMessage: true,

      showNewsletterOptIn: false,
      newsletterLabel_pl: "Zapisz mnie do newslettera",
      newsletterLabel_en: "Subscribe me to the newsletter",
      columns: 2, // 1 | 2 | 3
      buttonAlign: "left", // left | center | right | full
      buttonPosition: "bottom", // bottom | inline-right
      buttonVariant: "solid", // solid | outline | ghost | gradient
      buttonSize: "md", // sm | md | lg
      // appearance
      bgLight: "", // hex or token; "" = card default
      bgDark: "", // hex; "" = card default
      textColor: "",
      borderColor: "",
      radiusPx: 12,
      paddingPx: 32,
      bgImage: "", // recommended 1600x900 px (hero 2400x1200)
      bgImageMobile: "", // recommended 800x1000 px
      bgOverlay: 0, // 0-100

      iconUrl: "", // recommended 128x128 px
      recipient: "",
    }),
  },
];

export const WIDGET_MAP: Record<WidgetType, WidgetDef> = WIDGETS.reduce(
  (acc, w) => {
    acc[w.type] = w;
    return acc;
  },
  {} as Record<WidgetType, WidgetDef>,
);

export const makeWidget = (type: WidgetType): WidgetNode => ({
  id: newId(),
  kind: "widget",
  type,
  content: WIDGET_MAP[type].defaults(),
});
