// ZAMROŻONY DŁUG: testy z literałem daty, które NIE zamrażają zegara - per plik.
//
// Stan ZMIERZONY, nie przepisany (`bun run check:clock-freeze --print-baseline`)
// na HEAD c239ab891, 2026-09-06. Liczba przy pliku to liczba literałów daty
// POZA komentarzami.
//
// Lista jest RATCHETEM: liczba w pliku może tylko maleć, plik nieobecny na
// liście musi mieć ZERO, a wpis o pliku, którego nie ma, jest błędem.
// Uzasadnienie inwariantu, definicja bomby i to, czego ta bramka świadomie NIE
// rozstrzyga: `src/lib/ci/clockFreeze.ts`.
//
// CZYM TA LISTA NIE JEST. Nie jest listą testów, które padną. Jest listą
// testów, o których BRAMKA NIE POTRAFI POWIEDZIEĆ, że nie padną - bo niosą
// datę i sięgają po kod czytający zegar. Zmierzone na tym repozytorium
// (pełna suita, CLOCK_SHIFT=1y): z ponad dwustu plików na tej liście przy
// przesunięciu o rok pada garstka. Reszta to pliki, w których literał jest
// jawnym argumentem produkcji albo wejściem konwersji - czyli dług RYZYKA,
// a nie dług DEFEKTU. Dlatego triage („bomba" czy „niegroźne") wymaga
// przeczytania produkcji i należy do człowieka; bramka pilnuje tylko tego,
// żeby lista nie rosła.
//
// Lista mieszka osobno, żeby rozbrojenie kolejnego modułu było diffem
// w JEDNYM miejscu, a nie edycją runnera bramki.
//
// PRZELICZONA PO SCALENIU `main` (20 commitów ponad bazę, 67 zmienionych plików
// testowych). Baseline musi opisywać drzewo, na którym bramka faktycznie
// stanie, a nie bazę sprzed scalenia - inaczej pierwszy przebieg na CI jest
// czerwony na cudzym długu. Zmiana wobec pomiaru z bazy: 223 -> 221 plików.
// DWA pliki mają wpis WYŻSZY niż przed scaleniem, oba z `main` i oba sprzed
// istnienia tej bramki: `cart/cartStore.test.ts` (4 -> 5) oraz
// `routes/publicCatchAllRoute.test.tsx` (3 -> 4). Od tego commita zapadka
// trzyma je już w jedną stronę.
export const CLOCK_FREEZE_BASELINE: readonly (readonly [string, number])[] = [
  ["src/components/admin/__tests__/PostGeneralOverview.test.tsx", 2],
  ["src/components/admin/__tests__/TrendingTickerPane.selection.test.tsx", 2],
  ["src/components/admin/analytics/__tests__/audienceSegmentsDashboard.test.tsx", 15],
  ["src/components/admin/analytics/__tests__/footerAnalyticsPanel.test.tsx", 3],
  ["src/components/admin/analytics/__tests__/ga4BiDashboard.test.tsx", 5],
  ["src/components/admin/analytics/__tests__/gscBiDashboard.test.tsx", 49],
  ["src/components/admin/billing/__tests__/AdminBillingPanel.test.tsx", 6],
  ["src/components/admin/billing/__tests__/adminOrderPanels.test.tsx", 11],
  ["src/components/admin/billing/__tests__/AdminPaymentsDiagnosticsPanel.test.tsx", 4],
  ["src/components/admin/billing/__tests__/AdminWebhookLogPanel.test.tsx", 1],
  ["src/components/admin/builder/__tests__/sampleDataLeak.gate.test.tsx", 1],
  ["src/components/admin/builder/__tests__/settingsFidelity.gate.test.tsx", 2],
  [
    "src/components/admin/builder/ui/organisms/widget-properties/__tests__/eventScheduleEditor.test.tsx",
    1,
  ],
  ["src/components/admin/clubs/__tests__/ClubMembersTab.test.tsx", 3],
  ["src/components/admin/coupons/organisms/__tests__/CouponsListPage.test.tsx", 4],
  ["src/components/admin/donations/organisms/__tests__/AdminDonations.test.tsx", 3],
  ["src/components/admin/donations/organisms/__tests__/DonationsRecordsPanel.test.tsx", 4],
  ["src/components/admin/events/__tests__/EventAudienceGrantHistoryPanel.test.tsx", 8],
  ["src/components/admin/events/__tests__/EventAudienceGrantsPanel.test.tsx", 11],
  ["src/components/admin/events/__tests__/EventsListManager.test.tsx", 10],
  ["src/components/admin/events/__tests__/MeetingStatsPanel.test.tsx", 6],
  ["src/components/admin/events/__tests__/RegistrationsListPanel.test.tsx", 7],
  ["src/components/admin/events/organisms/__tests__/OnsiteLeadsPanel.test.tsx", 7],
  ["src/components/admin/gifting/__tests__/hooks.test.tsx", 1],
  ["src/components/admin/gifting/organisms/__tests__/AuditPanel.test.tsx", 3],
  ["src/components/admin/gifting/organisms/__tests__/GiftingAdmin.test.tsx", 2],
  ["src/components/admin/gifting/organisms/__tests__/SettingsPanel.test.tsx", 4],
  ["src/components/admin/media/__tests__/MediaPickerDialog.test.tsx", 1],
  ["src/components/admin/media/organisms/__tests__/MediaInfoPanel.test.tsx", 1],
  ["src/components/admin/membership/organisms/__tests__/AdminMembershipWorkspace.test.tsx", 1],
  ["src/components/admin/molecules/__tests__/RevisionDiffDialog.test.tsx", 12],
  ["src/components/admin/monetization/__tests__/AdminMonetizationLedger.test.tsx", 7],
  ["src/components/admin/newsletter/__tests__/SubscribersPanel.test.tsx", 2],
  ["src/components/admin/newsletter/auth-logs/__tests__/AuthEmailLogsPanel.test.tsx", 2],
  ["src/components/admin/newsletter/builder/__tests__/PropertiesPanel.test.tsx", 5],
  ["src/components/admin/newsletter/builder/__tests__/WidgetPreview.test.tsx", 1],
  ["src/components/admin/newsletter/deliverability/__tests__/deliverabilityPanels.test.tsx", 5],
  ["src/components/admin/newsletter/system-emails/__tests__/SystemEmailsPanel.test.tsx", 4],
  ["src/components/admin/newsletter/system-emails/__tests__/systemEmailsRules.test.ts", 5],
  ["src/components/admin/podcasts/__tests__/EpisodeEditorPane.test.tsx", 7],
  ["src/components/admin/podcasts/__tests__/EpisodeEditorPaneAudio.test.tsx", 1],
  ["src/components/admin/podcasts/__tests__/EpisodesListPane.test.tsx", 3],
  ["src/components/admin/post-editor/molecules/__tests__/PostSponsoredCard.disclosure.test.tsx", 1],
  ["src/components/admin/post-editor/molecules/__tests__/WorkflowStatusSection.test.tsx", 1],
  ["src/components/admin/post-editor/organisms/__tests__/PostSettingsCard.test.tsx", 2],
  ["src/components/admin/versions/__tests__/BuilderVersionsPane.test.tsx", 4],
  ["src/components/admin/versions/__tests__/CookieVersionsPane.test.tsx", 1],
  ["src/components/admin/versions/__tests__/PolicyVersionsPane.test.tsx", 1],
  ["src/components/admin/workflows/__tests__/atoms.test.tsx", 1],
  ["src/components/ads/__tests__/consentGate.test.tsx", 4],
  ["src/components/ads/__tests__/midPostAds.test.tsx", 4],
  ["src/components/atoms/__tests__/BrandIcon.test.tsx", 2],
  ["src/components/billing/__tests__/ChangePlanCard.test.tsx", 1],
  ["src/components/billing/__tests__/RetentionDialog.test.tsx", 1],
  ["src/components/billing/atoms/__tests__/billingAtoms.test.tsx", 6],
  ["src/components/blocks/__tests__/rendererBranches.test.tsx", 1],
  ["src/components/blocks/__tests__/siteAndUtilityViews.test.tsx", 1],
  ["src/components/builder/organisms/widget-view/__tests__/authorDisplayAcrossWidgets.test.tsx", 2],
  ["src/components/builder/organisms/widget-view/__tests__/branchClose.test.tsx", 2],
  ["src/components/builder/organisms/widget-view/__tests__/branchClose2.test.tsx", 1],
  ["src/components/builder/organisms/widget-view/__tests__/branchClose4.test.tsx", 1],
  ["src/components/builder/organisms/widget-view/__tests__/branchSweep.test.tsx", 1],
  ["src/components/builder/organisms/widget-view/__tests__/dataViews.test.tsx", 3],
  ["src/components/builder/organisms/widget-view/__tests__/dynamicTags.test.tsx", 1],
  ["src/components/builder/organisms/widget-view/__tests__/dynamicTagsSampleData.test.tsx", 1],
  ["src/components/builder/organisms/widget-view/__tests__/eventCountdownCard.test.tsx", 2],
  ["src/components/builder/organisms/widget-view/__tests__/eventWidgets.test.tsx", 4],
  ["src/components/builder/organisms/widget-view/__tests__/interactiveHandlers.test.tsx", 1],
  ["src/components/builder/organisms/widget-view/__tests__/meetingBookingActions.test.tsx", 2],
  ["src/components/builder/organisms/widget-view/__tests__/postListVariants2.test.tsx", 1],
  ["src/components/builder/organisms/widget-view/__tests__/postMetaViews.test.tsx", 1],
  ["src/components/careers/__tests__/careerCvField.test.tsx", 2],
  ["src/components/clubs/__tests__/clubPresentationWorkspaceRows.test.tsx", 1],
  ["src/components/comments/__tests__/CommentsSection.test.tsx", 2],
  ["src/components/events/__tests__/speakerProfileDialog.test.tsx", 3],
  ["src/components/events/scanner/__tests__/scannerCheckinPanel.test.tsx", 2],
  ["src/components/events/scanner/molecules/__tests__/scannerMolecules.test.tsx", 5],
  ["src/components/events/scanner/organisms/__tests__/ScannerApp.test.tsx", 2],
  ["src/components/experts/__tests__/expertLayoutHero.test.tsx", 1],
  ["src/components/notifications/__tests__/ConsentsPanel.test.tsx", 9],
  ["src/components/notifications/__tests__/NotificationsCenter.test.tsx", 10],
  ["src/components/post/__tests__/postComposition.test.tsx", 9],
  ["src/components/profile/__tests__/MediaMentionsSection.test.tsx", 2],
  ["src/components/profile/__tests__/ProfileExtraSections.test.tsx", 27],
  ["src/hooks/__tests__/useEditPresence.test.tsx", 1],
  ["src/lib/__tests__/contentFunctions.pages.test.ts", 6],
  ["src/lib/__tests__/contentFunctions.posts.test.ts", 4],
  ["src/lib/__tests__/contentFunctions.postUpdate.test.ts", 11],
  ["src/lib/__tests__/contentFunctions.schemas.test.ts", 2],
  ["src/lib/__tests__/contentFunctions.taxonomy.test.ts", 2],
  ["src/lib/__tests__/crmFunctions.test.ts", 7],
  ["src/lib/__tests__/crmFunnelSavedViewsFunctions.test.ts", 5],
  ["src/lib/__tests__/crmTasksFunctions.test.ts", 1],
  ["src/lib/__tests__/giftingAdminFunctions.test.ts", 6],
  ["src/lib/__tests__/newsletterAdminFunctions.test.ts", 3],
  ["src/lib/__tests__/newsletterCampaignCrud.test.ts", 2],
  ["src/lib/__tests__/newsletterStatusFunctions.test.ts", 4],
  ["src/lib/__tests__/relatedPosts.test.ts", 6],
  ["src/lib/__tests__/relatedPostsIdf.test.ts", 11],
  ["src/lib/__tests__/relatedPostsSignals.test.ts", 1],
  ["src/lib/__tests__/wpImportFunctions.test.ts", 2],
  ["src/lib/admin/__tests__/invitationsFunctions.test.ts", 2],
  ["src/lib/admin/__tests__/pricingRules.test.ts", 7],
  ["src/lib/admin/__tests__/workflows.test.ts", 14],
  ["src/lib/admin/__tests__/workflowsData.test.ts", 2],
  ["src/lib/admin/monetization/__tests__/ledgerServer.test.ts", 5],
  ["src/lib/ads/__tests__/queries.test.ts", 4],
  ["src/lib/analytics/__tests__/ga4Functions.test.ts", 4],
  ["src/lib/analytics/semantic/window.test.ts", 33],
  ["src/lib/billing/__tests__/accessPeriod.test.ts", 1],
  ["src/lib/billing/__tests__/audit.server.test.ts", 3],
  ["src/lib/billing/__tests__/billingDocuments.server.test.ts", 7],
  ["src/lib/billing/__tests__/catalogAutoSync.server.test.ts", 2],
  ["src/lib/billing/__tests__/catalogAutoSync.test.ts", 1],
  ["src/lib/billing/__tests__/checkoutOrderCoupon.test.ts", 1],
  ["src/lib/billing/__tests__/diagnostics.server.test.ts", 11],
  ["src/lib/billing/__tests__/discounts.server.test.ts", 2],
  ["src/lib/billing/__tests__/donationsLedger.server.test.ts", 12],
  ["src/lib/billing/__tests__/dunningDedupe.test.ts", 2],
  ["src/lib/billing/__tests__/entitlementSync.server.test.ts", 3],
  ["src/lib/billing/__tests__/grant.server.test.ts", 5],
  ["src/lib/billing/__tests__/membership.test.ts", 1],
  ["src/lib/billing/__tests__/notificationsGating.server.test.ts", 7],
  ["src/lib/billing/__tests__/notificationsPayload.server.test.ts", 22],
  ["src/lib/billing/__tests__/paymentHistory.test.ts", 12],
  ["src/lib/billing/__tests__/premiumNewsletter.test.ts", 3],
  ["src/lib/billing/__tests__/purchaseConfirmation.test.ts", 2],
  ["src/lib/billing/__tests__/queries.test.ts", 2],
  ["src/lib/billing/__tests__/refunds.server.test.ts", 1],
  ["src/lib/billing/__tests__/reminders.test.ts", 5],
  ["src/lib/billing/__tests__/remindersRun.server.test.ts", 5],
  ["src/lib/billing/__tests__/stripeEvents.server.test.ts", 10],
  ["src/lib/billing/__tests__/subscriptionProvider.server.test.ts", 1],
  ["src/lib/billing/__tests__/subscriptionStatus.test.ts", 3],
  ["src/lib/billing/__tests__/ticketOrders.functions.test.ts", 5],
  ["src/lib/billing/__tests__/ticketOrders.server.test.ts", 21],
  ["src/lib/billing/__tests__/webhookDispatch.server.test.ts", 6],
  ["src/lib/billing/__tests__/webhookRetry.functions.test.ts", 1],
  ["src/lib/builder/__tests__/eventsPrefetch.test.ts", 1],
  ["src/lib/cart/__tests__/cartStore.test.ts", 5],
  ["src/lib/chat/__tests__/conversationSettings.test.ts", 21],
  ["src/lib/chat/__tests__/messageCache.test.ts", 8],
  ["src/lib/chat/__tests__/receipts.test.ts", 3],
  ["src/lib/chat/__tests__/thread.test.ts", 2],
  ["src/lib/clubs/__tests__/activityStrip.test.ts", 1],
  ["src/lib/clubs/__tests__/clubWorkspaceHooks.test.tsx", 10],
  ["src/lib/clubs/__tests__/threadDynamics.test.ts", 1],
  ["src/lib/clubs/__tests__/threadPulse.test.ts", 1],
  ["src/lib/clubs/__tests__/workspaceForms.test.ts", 77],
  ["src/lib/comments/__tests__/tree.test.ts", 2],
  ["src/lib/community/calendar.test.ts", 15],
  ["src/lib/content/__tests__/brokenLinkPolicy.test.ts", 2],
  ["src/lib/content/__tests__/previewTokens.functions.test.ts", 5],
  ["src/lib/crm/__tests__/leadListParity.test.ts", 20],
  ["src/lib/crm/__tests__/leadTimeline.test.ts", 2],
  ["src/lib/crm/__tests__/leadViews.test.ts", 8],
  ["src/lib/crm/__tests__/panelRules.test.ts", 19],
  ["src/lib/email/__tests__/deliveryEvents.test.ts", 3],
  ["src/lib/events/__tests__/previewLiveData.test.ts", 6],
  ["src/lib/events/__tests__/scannerPlane.test.ts", 22],
  ["src/lib/events/__tests__/scannerStorage.test.ts", 2],
  ["src/lib/events/__tests__/ticketServer.test.ts", 4],
  ["src/lib/events/onsiteDraft.test.ts", 5],
  ["src/lib/experts/__tests__/expertHubQueries.test.ts", 4],
  ["src/lib/experts/__tests__/refreshOg.test.ts", 6],
  ["src/lib/greetings/__tests__/greetings.test.ts", 6],
  ["src/lib/greetings/__tests__/pickGreeting.test.ts", 1],
  ["src/lib/notifications/__tests__/grouping.test.ts", 2],
  ["src/lib/notifications/__tests__/notificationDeepLink.test.ts", 4],
  ["src/lib/notifications/__tests__/notificationText.test.ts", 2],
  ["src/lib/notifications/__tests__/pushDispatch.test.ts", 2],
  ["src/lib/notifications/__tests__/useConsents.test.tsx", 6],
  ["src/lib/notifications/__tests__/useNotifications.test.tsx", 1],
  ["src/lib/observability/__tests__/clientErrorsAggregate.test.ts", 14],
  ["src/lib/podcast/__tests__/queries.test.ts", 6],
  ["src/lib/queries/__tests__/blocks.test.ts", 2],
  ["src/lib/queries/__tests__/liveBlogs.test.ts", 2],
  ["src/lib/realtime/__tests__/useEntityPresence.test.tsx", 10],
  ["src/lib/realtime/__tests__/useEventConfirmedMutationBranches.test.tsx", 1],
  ["src/lib/server/__tests__/ttsServer.test.ts", 2],
  ["src/lib/tracker/__tests__/feedServer.test.ts", 2],
  ["src/routes/__tests__/adminBillingAuditRoute.test.tsx", 7],
  ["src/routes/__tests__/adminBillingReconcileRoute.test.tsx", 2],
  ["src/routes/__tests__/adminCareersRoute.test.tsx", 46],
  ["src/routes/__tests__/adminCommentsRoute.test.tsx", 1],
  ["src/routes/__tests__/adminCommunityChatRoute.test.tsx", 2],
  ["src/routes/__tests__/adminCommunityIndexRoute.test.tsx", 1],
  ["src/routes/__tests__/adminCommunityInsightRoutes.test.tsx", 7],
  ["src/routes/__tests__/adminCommunityPollsRoute.test.tsx", 8],
  ["src/routes/__tests__/adminCommunityQaRoute.test.tsx", 11],
  ["src/routes/__tests__/adminCompaniesRoutes.test.tsx", 13],
  ["src/routes/__tests__/adminContactRoute.test.tsx", 9],
  ["src/routes/__tests__/adminCouponsRedemptionsRoute.test.tsx", 2],
  ["src/routes/__tests__/adminCrmInboxRoute.test.tsx", 10],
  ["src/routes/__tests__/adminDonationsRoute.test.tsx", 2],
  ["src/routes/__tests__/adminExperimentsRoute.test.tsx", 2],
  ["src/routes/__tests__/adminImportWordpressRoute.test.tsx", 6],
  ["src/routes/__tests__/adminLibraryRoute.test.tsx", 1],
  ["src/routes/__tests__/adminLinkMonitorRoute.test.tsx", 1],
  ["src/routes/__tests__/adminLiveBlogRoute.test.tsx", 1],
  ["src/routes/__tests__/adminOrganizationsRoutes.test.tsx", 3],
  ["src/routes/__tests__/adminPageEditorRoute.test.tsx", 11],
  ["src/routes/__tests__/adminPostsListRoute.test.tsx", 19],
  ["src/routes/__tests__/adminRedirectsRoute.test.tsx", 6],
  ["src/routes/__tests__/adminSettingsRoutes.test.tsx", 1],
  ["src/routes/__tests__/adminUsersRoutes.test.tsx", 4],
  ["src/routes/__tests__/adminWebStoriesRoute.test.tsx", 5],
  ["src/routes/__tests__/eventsIndexRoute.test.tsx", 3],
  ["src/routes/__tests__/liveIndexRoute.test.tsx", 1],
  ["src/routes/__tests__/membershipJoinRoute.test.tsx", 2],
  ["src/routes/__tests__/podcastsIndexRoute.test.tsx", 5],
  ["src/routes/__tests__/pricingRoute.test.tsx", 2],
  ["src/routes/__tests__/profileDashboardRoute.test.tsx", 1],
  ["src/routes/__tests__/profileMembershipRoute.test.tsx", 13],
  ["src/routes/__tests__/publicCatchAllRoute.test.tsx", 4],
  ["src/routes/__tests__/trackerChangesRoute.test.tsx", 4],
  ["src/routes/-api.public.newsletter.confirm.test.ts", 5],
  ["src/routes/api/public/-webhooks.resend.test.ts", 3],
  ["src/routes/api/public/payments/-webhook.test.ts", 25],
  ["src/routes/platform/email/transactional/-send.test.ts", 2],
];
