// ZAMROŻONY DŁUG: rzutowania `as unknown as`, per plik.
//
// Stan po wdrożeniu wspólnego buildera zapytań Supabase (`lib/supabase/looseQuery.ts`)
// i przekierowaniu rzutowań na jsonb do `toJson()` / `toJsonArray()` - ZMIERZONY,
// nie przepisany (`bun run check:unknown-casts --print-baseline`).
//
// KOREKTA PO REVIEW PR-a #235. Pierwsza wersja skanera nie rozpoznawała celu
// będącego TYPEM FUNKCYJNYM (`as unknown as (fn: string, …) => …`), więc dziesięć
// takich rzutowań - m.in. cała rodzina wywołań RPC spoza wygenerowanych typów
// (`experts/materials.ts`, `builder/postListQuery.ts`, …) - było dla ratchetu
// niewidzialnych. To NIE jest nowy dług: te miejsca istniały wcześniej, tylko nie
// wchodziły do licznika. Baseline zapisuje więc liczbę PRAWDZIWĄ, a nie ładniejszą.
//
// Lista jest RATCHETEM: liczba w pliku może tylko maleć, a plik nieobecny na
// liście musi mieć ZERO. Uzasadnienie inwariantu (i trzy najczęstsze przyczyny
// tej klasy długu): `src/lib/ci/unknownCasts.ts`.
//
// Lista mieszka osobno, żeby ścięcie długu w kolejnym module było diffem
// w JEDNYM miejscu, a nie edycją runnera bramki.
export const UNKNOWN_CAST_BASELINE: readonly (readonly [string, number])[] = [
  ["src/components/admin/archiveLayout/ArchiveLayoutAdmin.tsx", 1],
  ["src/components/admin/blocks/edit/Buttons.tsx", 2],
  ["src/components/admin/blocks/edit/PostContextBlocks.tsx", 1],
  ["src/components/admin/blocks/edit/SocialIcons.tsx", 2],
  ["src/components/admin/builder/ui/organisms/widget-properties/EventScheduleEditor.tsx", 1],
  ["src/components/admin/builder/ui/organisms/widget-properties/PostListEditor.tsx", 1],
  ["src/components/admin/builder/ui/organisms/widget-properties/RichTextEditor.tsx", 1],
  ["src/components/admin/builder/ui/organisms/widget-properties/SpeakersEditor.tsx", 1],
  ["src/components/admin/builder/ui/organisms/widget-properties/SponsorsEditor.tsx", 1],
  ["src/components/admin/builder/ui/organisms/widget-properties/WorldMapEditor.tsx", 1],
  ["src/components/builder/organisms/widget-view/AuthorProfileCardWidget.tsx", 1],
  ["src/components/builder/organisms/widget-view/InteractiveCircleWidget.tsx", 1],
  ["src/components/builder/organisms/widget-view/SimpleWidgets.tsx", 1],
  ["src/components/builder/organisms/widget-view/SpeakersWidget.tsx", 1],
  ["src/components/builder/organisms/widget-view/TeamMemberWidget.tsx", 1],
  // 2, nie 1: drugie rzutowanie (`setThemedMode(...) as unknown as WidgetTypography
  // | undefined`) BYŁO tu od zawsze, ale Prettier 3.7 łamał tę unię na wiodący `|`,
  // a takiego celu skaner nie rozpoznawał. Podniesienie do 3.9.6 zlepiło unię
  // z powrotem w jedną linię i rzutowanie stało się policzalne. To NIE jest nowy
  // dług - to ta sama korekta co po review PR-a #235 (patrz nagłówek pliku):
  // baseline zapisuje liczbę PRAWDZIWĄ. Ratchet dalej trzyma kierunek: 2 -> mniej.
  ["src/components/admin/builder/WidgetProperties.tsx", 2],
  ["src/components/builder/organisms/WidgetView.tsx", 1],
  ["src/components/admin/crm/CrmPartnerEndpointsPanel.tsx", 1],
  ["src/components/admin/menu/AddItemPanel.tsx", 2],
  ["src/components/admin/menu/MenuManager.tsx", 1],
  ["src/components/admin/newsletter/builder/NewsletterBuilder.tsx", 1],
  ["src/components/admin/newsletter/builder/WidgetPreview.tsx", 1],
  ["src/components/admin/post-editor/hooks/usePostEditorData.ts", 1],
  ["src/components/admin/settings/fields.tsx", 1],
  ["src/components/admin/sidebarBuilder/SidebarBuilderPane.tsx", 2],
  ["src/components/admin/ThemeOptionsPane.tsx", 1],
  ["src/components/AlertBar.tsx", 1],
  ["src/components/blocks/renderer/data.ts", 1],
  ["src/components/blocks/renderer/organisms.tsx", 1],
  ["src/components/error/RenderErrorBoundary.tsx", 1],
  ["src/components/header/TrendingTicker.tsx", 2],
  ["src/components/megaMenu/MegaMenuShowcase.tsx", 3],
  ["src/components/newsletter/NewsletterDocRenderer.tsx", 1],
  ["src/components/profile/AuthorProfileEditor.tsx", 4],
  ["src/components/quiz/LazyQuizIframe.tsx", 1],
  ["src/hooks/useExpertLayoutSettings.ts", 1],
  ["src/hooks/useFaceAwarePosition.ts", 1],
  ["src/hooks/useNewsletterSettings.ts", 5],
  ["src/lib/admin/community.ts", 2],
  ["src/lib/ads/readingMode.ts", 1],
  ["src/lib/analytics/footerTracking.ts", 1],
  ["src/lib/analytics/ga4.functions.ts", 2],
  ["src/lib/analytics/gsc.functions.ts", 3],
  ["src/lib/analytics/semantic/snapshot.functions.ts", 1],
  ["src/lib/analytics/status.functions.ts", 1],
  ["src/lib/asyncBudget.ts", 1],
  ["src/lib/billing/discounts.server.ts", 1],
  ["src/lib/billing/invoice.server.ts", 1],
  ["src/lib/billing/notifications.server.ts", 5],
  ["src/lib/billing/oneTimeFulfilment.server.ts", 1],
  ["src/lib/billing/portalLink.server.ts", 2],
  ["src/lib/billing/reconcile.server.ts", 3],
  ["src/lib/billing/selfSync.server.ts", 1],
  ["src/lib/billing/transactions.server.ts", 1],
  ["src/lib/blocks/footnoteOrigins.ts", 3],
  ["src/lib/blocks/gutenberg.ts", 1],
  ["src/lib/blocks/nested.ts", 1],
  ["src/lib/blocks/patterns.ts", 1],
  ["src/lib/blocks/persistImages.ts", 2],
  ["src/lib/builder/contentRefs.ts", 1],
  ["src/lib/builder/designTokens.ts", 3],
  ["src/lib/builder/meetingsQuery.ts", 1],
  ["src/lib/builder/postListQuery.ts", 1],
  ["src/lib/builder/postViewCountQuery.ts", 1],
  ["src/lib/builder/prefetch.ts", 1],
  ["src/lib/builder/speakersQuery.ts", 1],
  ["src/lib/chat/stars.ts", 1],
  ["src/lib/chat/useExpertRequests.ts", 2],
  ["src/lib/ci/generatedTypesFreshness.ts", 1],
  ["src/lib/ci/unknownCasts.ts", 1],
  ["src/lib/consent/gpcClient.ts", 1],
  ["src/lib/content-model/json.ts", 2],
  ["src/lib/countries.ts", 2],
  ["src/lib/crm-tasks.functions.ts", 1],
  ["src/lib/crm.functions.ts", 1],
  ["src/lib/email/queueDrain.server.ts", 2],
  ["src/lib/email/reputationGate.server.ts", 1],
  ["src/lib/email/suppression.server.ts", 1],
  ["src/lib/experts/adminAuthorProfileRpc.ts", 1],
  ["src/lib/experts/materials.ts", 1],
  ["src/lib/experts/rpcHub.ts", 1],
  ["src/lib/http/middlewareResult.ts", 2],
  ["src/lib/icons/lucideIconNodes.generated.ts", 1],
  ["src/lib/lucide-shim.tsx", 1],
  ["src/lib/network/useProfileViews.ts", 1],
  ["src/lib/newsletter-campaigns.functions.ts", 4],
  ["src/lib/newsletter/emailDocResolve.ts", 3],
  ["src/lib/newsletter/trackingEvents.server.ts", 1],
  ["src/lib/notifications/dispatch.server.ts", 1],
  ["src/lib/notifications/useNotifications.ts", 1],
  ["src/lib/observability/redact.ts", 3],
  ["src/lib/observability/report.ts", 1],
  ["src/lib/observability/vitals.functions.ts", 2],
  ["src/lib/patterns/i18n.ts", 1],
  ["src/lib/platform-error-reporting.ts", 1],
  ["src/lib/profile/usePublicExposure.ts", 1],
  ["src/lib/queries/archives.ts", 1],
  ["src/lib/queries/podcasts.ts", 7],
  ["src/lib/queries/programs.ts", 8],
  ["src/lib/queries/public.ts", 2],
  ["src/lib/queries/series.ts", 1],
  ["src/lib/relatedInsights.functions.ts", 1],
  ["src/lib/search/useVoiceSearch.ts", 2],
  ["src/lib/seo/googleSourceBadgeAnalytics.ts", 1],
  ["src/lib/server/embeddings.server.ts", 2],
  ["src/lib/server/publishedContent.server.ts", 5],
  ["src/lib/social/globalSocialLinks.ts", 1],
  ["src/lib/tracker/queries.ts", 2],
  ["src/lib/webVitals.ts", 1],
  ["src/lib/wordpress-import.functions.ts", 1],
  ["src/routes/$.tsx", 1],
  ["src/routes/admin.audience.tsx", 3],
  ["src/routes/admin.coupons.redemptions.tsx", 1],
  ["src/routes/admin.link-monitor.tsx", 1],
  ["src/routes/admin.monetization.tsx", 1],
  ["src/routes/admin.pages.$slug.tsx", 1],
  ["src/routes/admin.pages.new.tsx", 1],
  ["src/routes/admin.podcasts.tsx", 1],
  ["src/routes/admin.research-programs.tsx", 2],
  ["src/routes/admin.tracker.tsx", 1],
  ["src/routes/author.$slug.tsx", 1],
  ["src/routes/network.mutual.$userId.tsx", 1],
  ["src/server.ts", 1],
  // Atrapa `XMLHttpRequest` w `xhrStub` (postęp wysyłki avatara/CV): `FakeXhr`
  // odgrywa tylko cztery użyte przez kod produkcyjny człony, nie pełny
  // interfejs przeglądarki - `tsc` sam odmawia pojedynczego `as` (TS2352,
  // niewystarczające pokrycie strukturalne). To legalny idiom testowy
  // podmiany globalnego konstruktora, nie dług do ścięcia.
  ["src/test/profile/fixtures.ts", 1],
  ["src/test/routeHarness.tsx", 1],
];
