// WYGENEROWANE przez scripts/generate-authz-snapshot.ts z supabase/migrations.
// Nie edytować ręcznie - zmiany nadpisze `bun run generate:authz-snapshot`.
//
// Snapshot bramek autoryzacji odtworzony ze SQL-a: role przechodzące każdą
// dokumentowaną bramkę oraz flagi `membership_tiers.features` realnie czytane
// przez bramki. Macierz uprawnień (/admin/permissions) renderuje się z tych
// danych, a test parytetu (src/lib/authz/__tests__) porównuje plik z ponownym
// odtworzeniem z migracji - rozjazd bazy i strony obleje CI.
import type { AuthzSnapshotModule } from "@/lib/authz/authzSnapshotTypes";

export const AUTHZ_SNAPSHOT: AuthzSnapshotModule = {
  appRoles: ["admin","author","editor","super_admin","user"],
  roleGates: [
    {"ref":"fn:admin_assert_verification_admin/0","kind":"function","object":"admin_assert_verification_admin","file":"20260806150000_profile_verification_authority.sql","anyRoles":["admin","super_admin"],"allRoles":[],"tenantRef":"caller","securityDefiner":true,"featureKeys":[]},
    {"ref":"fn:admin_community_stats/0","kind":"function","object":"admin_community_stats","file":"20260713200000_chat_admin_tenant_scope_fix.sql","anyRoles":["admin","editor","super_admin"],"allRoles":[],"tenantRef":"caller","securityDefiner":true,"featureKeys":[]},
    {"ref":"fn:admin_get_user_consent/1","kind":"function","object":"admin_get_user_consent","file":"20260715214120_2fd9eeb4-46f1-4217-92d0-37dd3e99727a.sql","anyRoles":["admin","super_admin"],"allRoles":[],"tenantRef":"none","securityDefiner":true,"featureKeys":[]},
    {"ref":"fn:admin_get_user/1","kind":"function","object":"admin_get_user","file":"20260703173228_0fa8ea9c-e96f-47a1-b7ad-b6f2ed3721c9.sql","anyRoles":["admin","super_admin"],"allRoles":[],"tenantRef":"caller","securityDefiner":true,"featureKeys":[]},
    {"ref":"fn:admin_grant_membership/4","kind":"function","object":"admin_grant_membership","file":"20260714130000_expert_hub.sql","anyRoles":[],"allRoles":["admin"],"tenantRef":"row","securityDefiner":true,"featureKeys":[]},
    {"ref":"fn:admin_grant_profile_badge/3","kind":"function","object":"admin_grant_profile_badge","file":"20260803113000_profile_badge_domain_sync.sql","anyRoles":["admin","super_admin"],"allRoles":[],"tenantRef":"caller","securityDefiner":true,"featureKeys":[]},
    {"ref":"fn:admin_list_membership_grants/0","kind":"function","object":"admin_list_membership_grants","file":"20260714130000_expert_hub.sql","anyRoles":[],"allRoles":["admin"],"tenantRef":"row","securityDefiner":true,"featureKeys":[]},
    {"ref":"fn:admin_list_users/0","kind":"function","object":"admin_list_users","file":"20260703090100_profiles_column_grants_and_role_audit.sql","anyRoles":["admin","super_admin"],"allRoles":[],"tenantRef":"caller","securityDefiner":true,"featureKeys":[]},
    {"ref":"fn:admin_set_content_password/5","kind":"function","object":"admin_set_content_password","file":"20260709093600_3a5ec36d-aa65-40ea-aaa7-2c91640ff33f.sql","anyRoles":["admin","editor","super_admin"],"allRoles":[],"tenantRef":"none","securityDefiner":true,"featureKeys":[]},
    {"ref":"fn:admin_set_expert_requests_enabled/2","kind":"function","object":"admin_set_expert_requests_enabled","file":"20260724130000_expert_request_visibility.sql","anyRoles":["admin"],"allRoles":[],"tenantRef":"row","securityDefiner":true,"featureKeys":[]},
    {"ref":"fn:admin_soft_delete_message/1","kind":"function","object":"admin_soft_delete_message","file":"20260713200000_chat_admin_tenant_scope_fix.sql","anyRoles":["admin","editor","super_admin"],"allRoles":[],"tenantRef":"caller","securityDefiner":true,"featureKeys":[]},
    {"ref":"fn:admin_update_user_avatar/2","kind":"function","object":"admin_update_user_avatar","file":"20260703175337_26cac59a-7e92-4f74-b66d-0f4f6cfeb098.sql","anyRoles":["admin","super_admin"],"allRoles":[],"tenantRef":"caller","securityDefiner":true,"featureKeys":[]},
    {"ref":"fn:authorize_resource_download/1","kind":"function","object":"authorize_resource_download","file":"20260724100000_fix_definer_header_tenant_scope.sql","anyRoles":["admin","editor"],"allRoles":[],"tenantRef":"caller","securityDefiner":true,"featureKeys":[]},
    {"ref":"fn:b2b_coupons_analytics/2","kind":"function","object":"b2b_coupons_analytics","file":"20260725090200_fix_coupon_analytics_applied_cents_inversion.sql","anyRoles":["admin","editor"],"allRoles":[],"tenantRef":"caller","securityDefiner":true,"featureKeys":[]},
    {"ref":"fn:bulk_generate_coupons_for_campaign/1","kind":"function","object":"bulk_generate_coupons_for_campaign","file":"20260724100000_fix_definer_header_tenant_scope.sql","anyRoles":["admin","editor"],"allRoles":[],"tenantRef":"caller","securityDefiner":true,"featureKeys":[]},
    {"ref":"fn:can_access_entity_presence/2","kind":"function","object":"can_access_entity_presence","file":"20260726121910_2aee5795-f498-4de1-b4b5-34b2b5422a50.sql","anyRoles":["admin","author","editor","super_admin"],"allRoles":[],"tenantRef":"caller","securityDefiner":true,"featureKeys":[]},
    {"ref":"fn:can_publish_content/1","kind":"function","object":"can_publish_content","file":"20260702113027_d3940358-76a0-4e77-bf9c-52f475d524b6.sql","anyRoles":["admin","super_admin"],"allRoles":[],"tenantRef":"none","securityDefiner":true,"featureKeys":[]},
    {"ref":"fn:change_user_role/2","kind":"function","object":"change_user_role","file":"20260703090100_profiles_column_grants_and_role_audit.sql","anyRoles":["admin","super_admin"],"allRoles":[],"tenantRef":"caller","securityDefiner":true,"featureKeys":[]},
    {"ref":"fn:club_capabilities/3","kind":"function","object":"club_capabilities","file":"20260808120000_discussion_clubs_a9_group_scope.sql","anyRoles":["editor"],"allRoles":[],"tenantRef":"caller","securityDefiner":true,"featureKeys":[]},
    {"ref":"fn:comments_guard_update/0","kind":"function","object":"comments_guard_update","file":"20260724090400_fix_comments_remoderate_on_edit.sql","anyRoles":["admin","editor"],"allRoles":[],"tenantRef":"row","securityDefiner":true,"featureKeys":[]},
    {"ref":"fn:crm_backfill_all_leads/0","kind":"function","object":"crm_backfill_all_leads","file":"20260722080948_7dc684cd-0761-4c1c-90a6-91dd2e940438.sql","anyRoles":["admin","super_admin"],"allRoles":[],"tenantRef":"none","securityDefiner":true,"featureKeys":[]},
    {"ref":"fn:crm_set_merydian_secret/2","kind":"function","object":"crm_set_merydian_secret","file":"20260712175237_8b79ff74-c8a7-46f4-9f02-8ebbaac10629.sql","anyRoles":["admin","super_admin"],"allRoles":[],"tenantRef":"caller","securityDefiner":true,"featureKeys":[]},
    {"ref":"fn:get_engagement_overview/0","kind":"function","object":"get_engagement_overview","file":"20260713099000_engagement_overview.sql","anyRoles":["admin","editor"],"allRoles":[],"tenantRef":"caller","securityDefiner":true,"featureKeys":[]},
    {"ref":"fn:get_event_access/1","kind":"function","object":"get_event_access","file":"20260724100000_fix_definer_header_tenant_scope.sql","anyRoles":["admin","editor"],"allRoles":[],"tenantRef":"caller","securityDefiner":true,"featureKeys":["pro_briefings","recordings"]},
    {"ref":"fn:get_poll_results/1","kind":"function","object":"get_poll_results","file":"20260724091000_harden_security_definer_tenant_scope.sql","anyRoles":["admin","editor"],"allRoles":[],"tenantRef":"caller","securityDefiner":true,"featureKeys":[]},
    {"ref":"fn:get_user_monthly_metering_count/1","kind":"function","object":"get_user_monthly_metering_count","file":"20260724100000_fix_definer_header_tenant_scope.sql","anyRoles":["admin","editor","super_admin"],"allRoles":[],"tenantRef":"caller","securityDefiner":true,"featureKeys":[]},
    {"ref":"fn:integration_endpoint_set_secret/2","kind":"function","object":"integration_endpoint_set_secret","file":"20260714090000_integration_endpoints_secret_vault.sql","anyRoles":["admin","super_admin"],"allRoles":[],"tenantRef":"caller","securityDefiner":true,"featureKeys":[]},
    {"ref":"fn:is_club_admin/1","kind":"function","object":"is_club_admin","file":"20260808090000_discussion_clubs_a1_structure.sql","anyRoles":["admin","super_admin"],"allRoles":[],"tenantRef":"none","securityDefiner":true,"featureKeys":[]},
    {"ref":"fn:is_staff/0","kind":"function","object":"is_staff","file":"20260628230000_tenant_isolation_and_authz.sql","anyRoles":["admin","author","editor"],"allRoles":[],"tenantRef":"none","securityDefiner":true,"featureKeys":[]},
    {"ref":"fn:job_scheduler_health/0","kind":"function","object":"job_scheduler_health","file":"20260731210000_community_cron_db_schedule.sql","anyRoles":["admin","editor","super_admin"],"allRoles":[],"tenantRef":"caller","securityDefiner":true,"featureKeys":[]},
    {"ref":"fn:list_gift_links_admin/4","kind":"function","object":"list_gift_links_admin","file":"20260806205328_8865e928-2b12-4e88-a855-d3b4309c82f4.sql","anyRoles":["admin","editor"],"allRoles":[],"tenantRef":"caller","securityDefiner":true,"featureKeys":[]},
    {"ref":"fn:metering_impact_preview/1","kind":"function","object":"metering_impact_preview","file":"20260725090100_fix_metering_preview_app_role_enum.sql","anyRoles":["admin","editor","super_admin"],"allRoles":[],"tenantRef":"caller","securityDefiner":true,"featureKeys":[]},
    {"ref":"fn:monetization_dashboard/4","kind":"function","object":"monetization_dashboard","file":"20260724100000_fix_definer_header_tenant_scope.sql","anyRoles":["admin","editor"],"allRoles":[],"tenantRef":"caller","securityDefiner":true,"featureKeys":[]},
    {"ref":"fn:org_set_seats_limit/3","kind":"function","object":"org_set_seats_limit","file":"20260729204314_73c57056-a7c4-4055-9612-6a43a0d588d2.sql","anyRoles":["admin"],"allRoles":[],"tenantRef":"caller","securityDefiner":true,"featureKeys":[]},
    {"ref":"fn:payment_orders_guard_status/0","kind":"function","object":"payment_orders_guard_status","file":"20260724143429_ac474056-b701-40c9-978d-5244c18df2f7.sql","anyRoles":["admin"],"allRoles":[],"tenantRef":"none","securityDefiner":true,"featureKeys":[]},
    {"ref":"fn:profiles_guard_privileged_columns/0","kind":"function","object":"profiles_guard_privileged_columns","file":"20260806190257_9386c9cc-9f1f-4ce8-8320-b3abad5ecc3f.sql","anyRoles":["admin","editor","super_admin"],"allRoles":[],"tenantRef":"caller","securityDefiner":true,"featureKeys":[]},
    {"ref":"fn:profiles_guard_verification/0","kind":"function","object":"profiles_guard_verification","file":"20260806190257_9386c9cc-9f1f-4ce8-8320-b3abad5ecc3f.sql","anyRoles":["admin","super_admin"],"allRoles":[],"tenantRef":"caller","securityDefiner":true,"featureKeys":[]},
    {"ref":"fn:profiles_pin_tenant_id/0","kind":"function","object":"profiles_pin_tenant_id","file":"20260721052806_67afab94-0343-483e-95f0-f2a6687a54a3.sql","anyRoles":["super_admin"],"allRoles":[],"tenantRef":"row","securityDefiner":true,"featureKeys":[]},
    {"ref":"fn:publish_legal_version/1","kind":"function","object":"publish_legal_version","file":"20260730205424_55821b5e-04d7-47c6-9853-ec7cc030d4bc.sql","anyRoles":["admin","editor","super_admin"],"allRoles":[],"tenantRef":"caller","securityDefiner":true,"featureKeys":[]},
    {"ref":"fn:publish_qa_session_summary/2","kind":"function","object":"publish_qa_session_summary","file":"20260724100000_fix_definer_header_tenant_scope.sql","anyRoles":["admin","editor","super_admin"],"allRoles":[],"tenantRef":"caller","securityDefiner":true,"featureKeys":[]},
    {"ref":"fn:related_posts_signals/2","kind":"function","object":"related_posts_signals","file":"20260716212125_f12862d5-3c6a-44b8-a8fc-b84dc49c318e.sql","anyRoles":["admin"],"allRoles":[],"tenantRef":"row","securityDefiner":true,"featureKeys":[]},
    {"ref":"fn:revoke_gift_link_admin/1","kind":"function","object":"revoke_gift_link_admin","file":"20260722113410_35a7de44-0ce9-40d8-a126-62eb892cca51.sql","anyRoles":["admin","editor"],"allRoles":[],"tenantRef":"caller","securityDefiner":true,"featureKeys":[]},
    {"ref":"fn:tg_comments_owner_edit/0","kind":"function","object":"tg_comments_owner_edit","file":"20260713098000_comments_editing.sql","anyRoles":["admin","editor"],"allRoles":[],"tenantRef":"row","securityDefiner":true,"featureKeys":[]},
  ],
  featureGates: [
    {"capability":"chat_direct_gated","ref":"fn:get_or_create_direct_conversation/1","kind":"function","object":"get_or_create_direct_conversation","file":"20260807054859_a72ef6bd-541a-4d59-a822-616f71e003f7.sql","bypassRoles":["super_admin"],"tenantRef":"row"},
    {"capability":"chat_direct_gated","ref":"fn:my_expert_request_quota/0","kind":"function","object":"my_expert_request_quota","file":"20260806185055_1272fb55-fdb9-4eac-9035-66377484ac2c.sql","bypassRoles":["super_admin"],"tenantRef":"row"},
    {"capability":"chat_enabled","ref":"fn:get_or_create_direct_conversation/1","kind":"function","object":"get_or_create_direct_conversation","file":"20260807054859_a72ef6bd-541a-4d59-a822-616f71e003f7.sql","bypassRoles":["super_admin"],"tenantRef":"row"},
    {"capability":"chat_inmail_quota_2","ref":"fn:my_expert_request_quota/0","kind":"function","object":"my_expert_request_quota","file":"20260806185055_1272fb55-fdb9-4eac-9035-66377484ac2c.sql","bypassRoles":["super_admin"],"tenantRef":"row"},
    {"capability":"chat_inmail_quota_5","ref":"fn:my_expert_request_quota/0","kind":"function","object":"my_expert_request_quota","file":"20260806185055_1272fb55-fdb9-4eac-9035-66377484ac2c.sql","bypassRoles":["super_admin"],"tenantRef":"row"},
    {"capability":"expert_request_quota","ref":"fn:my_expert_request_quota/0","kind":"function","object":"my_expert_request_quota","file":"20260806185055_1272fb55-fdb9-4eac-9035-66377484ac2c.sql","bypassRoles":["super_admin"],"tenantRef":"row"},
    {"capability":"gift_links","ref":"fn:can_gift_articles/0","kind":"function","object":"can_gift_articles","file":"20260723170000_expert_request_capability.sql","bypassRoles":[],"tenantRef":"none"},
    {"capability":"premium_content","ref":"fn:has_content_access/2","kind":"function","object":"has_content_access","file":"20260723090000_tier_content_gating_tracker.sql","bypassRoles":[],"tenantRef":"row"},
    {"capability":"pro_briefings","ref":"fn:get_event_access/1","kind":"function","object":"get_event_access","file":"20260724100000_fix_definer_header_tenant_scope.sql","bypassRoles":["admin","editor"],"tenantRef":"caller"},
    {"capability":"pro_briefings","ref":"fn:rsvp_event/2","kind":"function","object":"rsvp_event","file":"20260721150000_events_waitlist_recordings_gate.sql","bypassRoles":[],"tenantRef":"row"},
    {"capability":"qa_priority","ref":"fn:list_qa_questions/1","kind":"function","object":"list_qa_questions","file":"20260724090700_qa_list_my_vote.sql","bypassRoles":[],"tenantRef":"row"},
    {"capability":"recordings","ref":"fn:get_event_access/1","kind":"function","object":"get_event_access","file":"20260724100000_fix_definer_header_tenant_scope.sql","bypassRoles":["admin","editor"],"tenantRef":"caller"},
    {"capability":"regulatory_monitoring","ref":"policy:eu_policy_follows/policy follows owner all","kind":"policy","object":"eu_policy_follows","file":"20260723090000_tier_content_gating_tracker.sql","bypassRoles":[],"tenantRef":"row"},
  ],
  stats: {"migrations":744,"functions":822,"policies":522},
};
