// Mapowanie nazw ikon (zapisanych w treści dokumentu) na komponenty lucide.
// Nazwa nieznana -> neutralna ikona dokumentu, żeby wersja z bazy nigdy nie
// wywróciła renderu strony prawnej.
import {
  Activity,
  AlarmClock,
  BadgeCheck,
  Ban,
  BellRing,
  Bot,
  Building2,
  CalendarClock,
  CalendarDays,
  ClipboardList,
  Cookie,
  Copyright,
  CreditCard,
  Database,
  Download,
  EyeOff,
  FileCheck2,
  FileText,
  Fingerprint,
  Gavel,
  Globe2,
  HeartHandshake,
  History,
  Landmark,
  ListChecks,
  Lock,
  Mail,
  Megaphone,
  MessageSquare,
  MessageSquareWarning,
  MonitorSmartphone,
  QrCode,
  RotateCcw,
  Scale,
  Send,
  Server,
  Share2,
  ShieldAlert,
  ShieldCheck,
  SlidersHorizontal,
  Store,
  Ticket,
  Timer,
  Trash2,
  UserCheck,
  UserX,
  Users,
  Wallet,
  type LucideIcon,
} from "lucide-react";

export const LEGAL_ICONS: Record<string, LucideIcon> = {
  Activity,
  AlarmClock,
  BadgeCheck,
  Ban,
  BellRing,
  Bot,
  Building2,
  CalendarClock,
  CalendarDays,
  ClipboardList,
  Cookie,
  Copyright,
  CreditCard,
  Database,
  Download,
  EyeOff,
  FileCheck2,
  FileText,
  Fingerprint,
  Gavel,
  Globe2,
  HeartHandshake,
  History,
  Landmark,
  ListChecks,
  Lock,
  Mail,
  Megaphone,
  MessageSquare,
  MessageSquareWarning,
  MonitorSmartphone,
  QrCode,
  RotateCcw,
  Scale,
  Send,
  Server,
  Share2,
  ShieldAlert,
  ShieldCheck,
  SlidersHorizontal,
  Store,
  Ticket,
  Timer,
  Trash2,
  UserCheck,
  UserX,
  Users,
  Wallet,
};

/** Lista nazw do wyboru w panelu (posortowana alfabetycznie). */
export const LEGAL_ICON_NAMES = Object.keys(LEGAL_ICONS).sort();

export function resolveLegalIcon(name: string): LucideIcon {
  return LEGAL_ICONS[name] ?? FileText;
}
