/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PostSlugRouteImport } from './routes/post.$slug'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTagsRouteImport } from './routes/admin.tags'
import { Route as AdminPostsRouteImport } from './routes/admin.posts'
import { Route as AdminPagesRouteImport } from './routes/admin.pages'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as ApiPublicSitemapDotxmlRouteImport } from './routes/api/public/sitemap[.]xml'
import { Route as ApiPublicRobotsDottxtRouteImport } from './routes/api/public/robots[.]txt'
import { Route as AdminPostsNewRouteImport } from './routes/admin.posts.new'
import { Route as AdminPostsIdRouteImport } from './routes/admin.posts.$id'
import { Route as AdminPagesNewRouteImport } from './routes/admin.pages.new'
import { Route as AdminPagesIdRouteImport } from './routes/admin.pages.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PostSlugRoute = PostSlugRouteImport.update({
  id: '/post/$slug',
  path: '/post/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTagsRoute = AdminTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsRoute = AdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicSitemapDotxmlRoute = ApiPublicSitemapDotxmlRouteImport.update({
  id: '/api/public/sitemap.xml',
  path: '/api/public/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRobotsDottxtRoute = ApiPublicRobotsDottxtRouteImport.update({
  id: '/api/public/robots.txt',
  path: '/api/public/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPostsNewRoute = AdminPostsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminPostsRoute,
} as any)
const AdminPostsIdRoute = AdminPostsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminPostsRoute,
} as any)
const AdminPagesNewRoute = AdminPagesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminPagesRoute,
} as any)
const AdminPagesIdRoute = AdminPagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminPagesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/pages': typeof AdminPagesRouteWithChildren
  '/admin/posts': typeof AdminPostsRouteWithChildren
  '/admin/tags': typeof AdminTagsRoute
  '/admin/users': typeof AdminUsersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/post/$slug': typeof PostSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/pages/$id': typeof AdminPagesIdRoute
  '/admin/pages/new': typeof AdminPagesNewRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/api/public/robots.txt': typeof ApiPublicRobotsDottxtRoute
  '/api/public/sitemap.xml': typeof ApiPublicSitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/login': typeof LoginRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/pages': typeof AdminPagesRouteWithChildren
  '/admin/posts': typeof AdminPostsRouteWithChildren
  '/admin/tags': typeof AdminTagsRoute
  '/admin/users': typeof AdminUsersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/post/$slug': typeof PostSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/admin/pages/$id': typeof AdminPagesIdRoute
  '/admin/pages/new': typeof AdminPagesNewRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/api/public/robots.txt': typeof ApiPublicRobotsDottxtRoute
  '/api/public/sitemap.xml': typeof ApiPublicSitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/pages': typeof AdminPagesRouteWithChildren
  '/admin/posts': typeof AdminPostsRouteWithChildren
  '/admin/tags': typeof AdminTagsRoute
  '/admin/users': typeof AdminUsersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/post/$slug': typeof PostSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/pages/$id': typeof AdminPagesIdRoute
  '/admin/pages/new': typeof AdminPagesNewRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/api/public/robots.txt': typeof ApiPublicRobotsDottxtRoute
  '/api/public/sitemap.xml': typeof ApiPublicSitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/admin'
    | '/login'
    | '/admin/categories'
    | '/admin/media'
    | '/admin/pages'
    | '/admin/posts'
    | '/admin/tags'
    | '/admin/users'
    | '/blog/$slug'
    | '/p/$slug'
    | '/post/$slug'
    | '/admin/'
    | '/blog/'
    | '/admin/pages/$id'
    | '/admin/pages/new'
    | '/admin/posts/$id'
    | '/admin/posts/new'
    | '/api/public/robots.txt'
    | '/api/public/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/login'
    | '/admin/categories'
    | '/admin/media'
    | '/admin/pages'
    | '/admin/posts'
    | '/admin/tags'
    | '/admin/users'
    | '/blog/$slug'
    | '/p/$slug'
    | '/post/$slug'
    | '/admin'
    | '/blog'
    | '/admin/pages/$id'
    | '/admin/pages/new'
    | '/admin/posts/$id'
    | '/admin/posts/new'
    | '/api/public/robots.txt'
    | '/api/public/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/admin'
    | '/login'
    | '/admin/categories'
    | '/admin/media'
    | '/admin/pages'
    | '/admin/posts'
    | '/admin/tags'
    | '/admin/users'
    | '/blog/$slug'
    | '/p/$slug'
    | '/post/$slug'
    | '/admin/'
    | '/blog/'
    | '/admin/pages/$id'
    | '/admin/pages/new'
    | '/admin/posts/$id'
    | '/admin/posts/new'
    | '/api/public/robots.txt'
    | '/api/public/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  BlogSlugRoute: typeof BlogSlugRoute
  PSlugRoute: typeof PSlugRoute
  PostSlugRoute: typeof PostSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiPublicRobotsDottxtRoute: typeof ApiPublicRobotsDottxtRoute
  ApiPublicSitemapDotxmlRoute: typeof ApiPublicSitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/post/$slug': {
      id: '/post/$slug'
      path: '/post/$slug'
      fullPath: '/post/$slug'
      preLoaderRoute: typeof PostSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tags': {
      id: '/admin/tags'
      path: '/tags'
      fullPath: '/admin/tags'
      preLoaderRoute: typeof AdminTagsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/sitemap.xml': {
      id: '/api/public/sitemap.xml'
      path: '/api/public/sitemap.xml'
      fullPath: '/api/public/sitemap.xml'
      preLoaderRoute: typeof ApiPublicSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/robots.txt': {
      id: '/api/public/robots.txt'
      path: '/api/public/robots.txt'
      fullPath: '/api/public/robots.txt'
      preLoaderRoute: typeof ApiPublicRobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/posts/new': {
      id: '/admin/posts/new'
      path: '/new'
      fullPath: '/admin/posts/new'
      preLoaderRoute: typeof AdminPostsNewRouteImport
      parentRoute: typeof AdminPostsRoute
    }
    '/admin/posts/$id': {
      id: '/admin/posts/$id'
      path: '/$id'
      fullPath: '/admin/posts/$id'
      preLoaderRoute: typeof AdminPostsIdRouteImport
      parentRoute: typeof AdminPostsRoute
    }
    '/admin/pages/new': {
      id: '/admin/pages/new'
      path: '/new'
      fullPath: '/admin/pages/new'
      preLoaderRoute: typeof AdminPagesNewRouteImport
      parentRoute: typeof AdminPagesRoute
    }
    '/admin/pages/$id': {
      id: '/admin/pages/$id'
      path: '/$id'
      fullPath: '/admin/pages/$id'
      preLoaderRoute: typeof AdminPagesIdRouteImport
      parentRoute: typeof AdminPagesRoute
    }
  }
}

interface AdminPagesRouteChildren {
  AdminPagesIdRoute: typeof AdminPagesIdRoute
  AdminPagesNewRoute: typeof AdminPagesNewRoute
}

const AdminPagesRouteChildren: AdminPagesRouteChildren = {
  AdminPagesIdRoute: AdminPagesIdRoute,
  AdminPagesNewRoute: AdminPagesNewRoute,
}

const AdminPagesRouteWithChildren = AdminPagesRoute._addFileChildren(
  AdminPagesRouteChildren,
)

interface AdminPostsRouteChildren {
  AdminPostsIdRoute: typeof AdminPostsIdRoute
  AdminPostsNewRoute: typeof AdminPostsNewRoute
}

const AdminPostsRouteChildren: AdminPostsRouteChildren = {
  AdminPostsIdRoute: AdminPostsIdRoute,
  AdminPostsNewRoute: AdminPostsNewRoute,
}

const AdminPostsRouteWithChildren = AdminPostsRoute._addFileChildren(
  AdminPostsRouteChildren,
)

interface AdminRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminPagesRoute: typeof AdminPagesRouteWithChildren
  AdminPostsRoute: typeof AdminPostsRouteWithChildren
  AdminTagsRoute: typeof AdminTagsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminPagesRoute: AdminPagesRouteWithChildren,
  AdminPostsRoute: AdminPostsRouteWithChildren,
  AdminTagsRoute: AdminTagsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  BlogSlugRoute: BlogSlugRoute,
  PSlugRoute: PSlugRoute,
  PostSlugRoute: PostSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiPublicRobotsDottxtRoute: ApiPublicRobotsDottxtRoute,
  ApiPublicSitemapDotxmlRoute: ApiPublicSitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
