// This file is automatically generated. Do not edit it directly.
// EXCEPTIONS (restore after every regeneration):
//   1. (see tenant-host-fetch.ts and correlation-fetch.ts)
//      `global: { fetch: fetchWithTenantHostAndCorrelation }` must be passed to
//      createClient, or anon traffic loses the x-tenant-host header (every RLS
//      policy based on public_tenant_id() silently resolves to the DEFAULT
//      tenant on other domains) and mutations lose the x-correlation-id header
//      (domain_events stop carrying correlation ids end-to-end).
//   2. (see lib/supabasePublicConfig.ts) URL/key MUST come from
//      resolveSupabasePublicConfig(), not from import.meta.env alone - the
//      publish build does not inline VITE_* into the client bundle, so the
//      browser needs the SSR window.__SUPABASE_CONFIG__ handoff or the whole
//      published site crashes into the root error boundary at first touch.
//   3. (zob. sessionHint.ts, P1.7) Proxy niżej woła
//      `markSupabaseClientCreated()` zaraz po utworzeniu klienta, a moduł
//      reeksportuje `onSupabaseClientCreated`. `AuthProvider` NIE dotyka
//      `supabase` u gościa (pusty magazyn, adres bez parametrów auth) - nasłuch
//      `onAuthStateChange` podpina z tego haka w chwili, gdy klienta utworzy
//      ktokolwiek inny (formularz logowania, zapytanie o dane). Bez tego
//      wywołania gość, który zaloguje się w tej karcie, zostaje w UI
//      wylogowany do przeładowania strony.
import { createClient } from "@supabase/supabase-js";
import { fetchWithTenantHostAndCorrelation } from "./correlation-fetch";
import { resolveSupabasePublicConfig } from "@/lib/supabasePublicConfig";
import type { Database } from "./types";
import { brokeredPreviewStorage } from "./previewAuthStorage";
import { markSupabaseClientCreated } from "./sessionHint";

export { onSupabaseClientCreated } from "./sessionHint";

function createSupabaseClient() {
  // Build-time VITE_* -> SSR-injected window config -> server process.env.
  const { url: SUPABASE_URL, key: SUPABASE_PUBLISHABLE_KEY } = resolveSupabasePublicConfig();

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in the neweuropeanstrategies.com environment.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    },
    // Multi-tenant: każde żądanie anon niesie x-tenant-host, żeby RLS
    // (tenant_id = public_tenant_id()) rozwiązywało tenanta per domena.
    // Korelacja: mutacje w runWithCorrelation niosą x-correlation-id, który
    // emitery zdarzeń domenowych zapisują w domain_events.correlation_id.
    global: { fetch: fetchWithTenantHostAndCorrelation },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) {
      _supabase = createSupabaseClient();
      // Po przypisaniu, przed zwrotem dostępu: słuchacz (nasłuch auth
      // w `AuthProvider`) dostaje klienta, zanim SDK wyemituje pierwsze
      // zdarzenie. Wyjątek z `createSupabaseClient()` nie dochodzi tutaj.
      markSupabaseClientCreated();
    }
    return Reflect.get(_supabase, prop, receiver);
  },
});
